-- +goose Up
-- ═══════════════════════════════════════════════════════════════════════════════
-- RADIOLEDGER REFERENCE DATA
-- NOTE: This reference data is now included in 001_initial_schema.sql.
-- This file is kept for standalone seeding/re-seeding outside of migrations.
-- Consolidated from seed files 001_bands.sql, 002_modes.sql, 003_dxcc_entities.sql.
-- ═══════════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────────
-- BANDS
-- Frequencies are in MHz.
-- ─────────────────────────────────────────────────────────────────────────────
-- NOTE: This seed data matches 001_initial_schema.sql. If you update one, update both.
INSERT INTO bands (name, lower_freq, upper_freq, band_group, warc, is_common, sort_order) VALUES
('2190m', 0.1357, 0.1378, 'LF', FALSE, FALSE, 50),
('630m', 0.472, 0.479, 'MF', FALSE, FALSE, 51),
('560m', 0.501, 0.504, 'MF', FALSE, FALSE, 52),
('160m', 1.800, 2.000, 'HF', FALSE, TRUE, 1),
('80m', 3.500, 4.000, 'HF', FALSE, TRUE, 2),
('60m', 5.060, 5.450, 'HF', TRUE, TRUE, 3),
('40m', 7.000, 7.300, 'HF', FALSE, TRUE, 4),
('30m', 10.100, 10.150, 'HF', TRUE, TRUE, 5),
('20m', 14.000, 14.350, 'HF', FALSE, TRUE, 6),
('17m', 18.068, 18.168, 'HF', TRUE, TRUE, 7),
('15m', 21.000, 21.450, 'HF', FALSE, TRUE, 8),
('12m', 24.890, 24.990, 'HF', TRUE, TRUE, 9),
('10m', 28.000, 29.700, 'HF', FALSE, TRUE, 10),
('8m', 40.000, 45.000, 'VHF', FALSE, FALSE, 53),
('6m', 50.000, 54.000, 'VHF', FALSE, TRUE, 11),
('5m', 54.000, 69.900, 'VHF', FALSE, FALSE, 54),
('4m', 70.000, 71.000, 'VHF', FALSE, FALSE, 12),
('2m', 144.000, 148.000, 'VHF', FALSE, TRUE, 13),
('1.25m', 222.000, 225.000, 'VHF', FALSE, TRUE, 14),
('70cm', 420.000, 450.000, 'UHF', FALSE, TRUE, 15),
('33cm', 902.000, 928.000, 'UHF', FALSE, FALSE, 16),
('23cm', 1240.000, 1300.000, 'UHF', FALSE, TRUE, 17),
('13cm', 2300.000, 2450.000, 'SHF', FALSE, FALSE, 18),
('9cm', 3300.000, 3500.000, 'SHF', FALSE, FALSE, 55),
('6cm', 5650.000, 5925.000, 'SHF', FALSE, FALSE, 56),
('3cm', 10000.000, 10500.000, 'SHF', FALSE, FALSE, 57),
('1.25cm', 24000.000, 24050.000, 'microwave', FALSE, FALSE, 58),
('6mm', 47000.000, 47200.000, 'microwave', FALSE, FALSE, 59),
('4mm', 75500.000, 81000.000, 'microwave', FALSE, FALSE, 60),
('2.5mm', 119980.000, 120020.000, 'microwave', FALSE, FALSE, 61),
('2mm', 142000.000, 149000.000, 'microwave', FALSE, FALSE, 62),
('1mm', 241000.000, 250000.000, 'microwave', FALSE, FALSE, 63),
('submm', 300000.000, 7500000.000, 'microwave', FALSE, FALSE, 64)
ON CONFLICT (name) DO UPDATE SET
    lower_freq = EXCLUDED.lower_freq,
    upper_freq = EXCLUDED.upper_freq,
    band_group = EXCLUDED.band_group,
    warc = EXCLUDED.warc,
    is_common = EXCLUDED.is_common,
    sort_order = EXCLUDED.sort_order;


-- ─────────────────────────────────────────────────────────────────────────────
-- MODES
-- Common operating modes and ADIF mapping.
-- ─────────────────────────────────────────────────────────────────────────────
-- NOTE: This seed data matches 001_initial_schema.sql. If you update one, update both.
INSERT INTO modes (name, category, adif_mode, adif_submode, submodes, is_analog, is_popular, sort_order) VALUES
('FT8',          'DIGITAL', 'FT8',          NULL,          NULL,                                                                 FALSE, TRUE,  1),
('SSB',          'PHONE',   'SSB',          NULL,          ARRAY['USB','LSB'],                                                   TRUE,  TRUE,  2),
('CW',           'CW',      'CW',           NULL,          NULL,                                                                 TRUE,  TRUE,  3),
('FT4',          'DIGITAL', 'MFSK',         'FT4',         NULL,                                                                 FALSE, TRUE,  4),
('FM',           'PHONE',   'FM',           NULL,          NULL,                                                                 TRUE,  TRUE,  5),
('RTTY',         'DIGITAL', 'RTTY',         NULL,          ARRAY['ASCI'],                                                       FALSE, TRUE,  6),
('PSK31',        'DIGITAL', 'PSK',          'PSK31',       NULL,                                                                 FALSE, TRUE,  7),
('DMR',          'DIGITAL', 'DIGITALVOICE', 'DMR',         NULL,                                                                 FALSE, TRUE,  8),
('VARAHF',       'DIGITAL', 'DYNAMIC',      'VARA HF',     NULL,                                                                 FALSE, TRUE,  9),
('JS8',          'DIGITAL', 'MFSK',         'JS8',         NULL,                                                                 FALSE, TRUE, 10),
('WSPR',         'DIGITAL', 'WSPR',         NULL,          NULL,                                                                 FALSE, TRUE, 11),
('C4FM',         'DIGITAL', 'DIGITALVOICE', 'C4FM',        NULL,                                                                 FALSE, TRUE, 12),
('DSTAR',        'DIGITAL', 'DIGITALVOICE', 'DSTAR',       NULL,                                                                 FALSE, TRUE, 13),
('SSTV',         'IMAGE',   'SSTV',         NULL,          NULL,                                                                 FALSE, TRUE, 14),
('PACKET',       'DATA',    'PKT',          NULL,          NULL,                                                                 FALSE, TRUE, 15),
('DIGITALVOICE', 'DIGITAL', 'DIGITALVOICE', NULL,          ARRAY['C4FM','DMR','DSTAR','FREEDV','M17'],                        FALSE, FALSE, 16),
('DYNAMIC',      'DATA',    'DYNAMIC',      NULL,          ARRAY['FREEDATA','VARA HF','VARA SATELLITE','VARA FM 1200','VARA FM 9600'], FALSE, FALSE, 17),
('FSK',          'DATA',    'FSK',          NULL,          ARRAY['SCAMP_FAST','SCAMP_SLOW','SCAMP_VSLOW'],                    FALSE, FALSE, 18),
('MTONE',        'DATA',    'MTONE',        NULL,          ARRAY['SCAMP_OO','SCAMP_OO_SLW'],                                  FALSE, FALSE, 19),
('OFDM',         'DATA',    'OFDM',         NULL,          ARRAY['RIBBIT_PIX','RIBBIT_SMS'],                                  FALSE, FALSE, 20),
('PKT',          'DATA',    'PKT',          NULL,          NULL,                                                                 FALSE, FALSE, 21),
('AM',           'PHONE',   'AM',           NULL,          NULL,                                                                 TRUE,  FALSE, 100),
('LSB',          'PHONE',   'SSB',          'LSB',         NULL,                                                                 TRUE,  FALSE, 101),
('USB',          'PHONE',   'SSB',          'USB',         NULL,                                                                 TRUE,  FALSE, 102),
('PSK63',        'DIGITAL', 'PSK',          'PSK63',       NULL,                                                                 FALSE, FALSE, 103),
('JT65',         'DIGITAL', 'JT65',         NULL,          ARRAY['JT65A','JT65B','JT65C'],                                    FALSE, FALSE, 104),
('JT9',          'DIGITAL', 'JT9',          NULL,          NULL,                                                                 FALSE, FALSE, 105),
('OLIVIA',       'DIGITAL', 'OLIVIA',       NULL,          NULL,                                                                 FALSE, FALSE, 106),
('THOR',         'DIGITAL', 'THOR',         NULL,          NULL,                                                                 FALSE, FALSE, 107),
('HELL',         'DIGITAL', 'HELL',         NULL,          ARRAY['FMHELL','HELL80','HFSK','PSKHELL'],                         FALSE, FALSE, 108),
('DOMINO',       'DIGITAL', 'DOMINO',       NULL,          ARRAY['DOMINOF'],                                                   FALSE, FALSE, 109),
('MFSK',         'DIGITAL', 'MFSK',         NULL,          ARRAY['FT4','FT2','JS8','Q65'],                                    FALSE, FALSE, 110),
('ARDOP',        'DIGITAL', 'ARDOP',        NULL,          NULL,                                                                 FALSE, FALSE, 111),
('FREEDV',       'DIGITAL', 'DIGITALVOICE', 'FREEDV',      NULL,                                                                 FALSE, FALSE, 112),
('M17',          'DIGITAL', 'DIGITALVOICE', 'M17',         NULL,                                                                 FALSE, FALSE, 113),
('Q65',          'DIGITAL', 'MFSK',         'Q65',         NULL,                                                                 FALSE, FALSE, 114),
('ATV',          'IMAGE',   'ATV',          NULL,          NULL,                                                                 FALSE, FALSE, 115),
('FAX',          'IMAGE',   'FAX',          NULL,          NULL,                                                                 FALSE, FALSE, 116),
('FT2',          'DIGITAL', 'MFSK',         'FT2',         NULL,                                                                 FALSE, FALSE, 117),
('FREEDATA',     'DATA',    'DYNAMIC',      'FREEDATA',    NULL,                                                                 FALSE, FALSE, 118),
('CHIP',         'DATA',    'CHIP',         NULL,          ARRAY['CHIP64','CHIP128'],                                          FALSE, FALSE, 119),
('CLO',          'DIGITAL', 'CLO',          NULL,          NULL,                                                                 FALSE, FALSE, 120),
('CONTESTI',     'DATA',    'CONTESTI',     NULL,          NULL,                                                                 FALSE, FALSE, 121),
('FSK441',       'DIGITAL', 'FSK441',       NULL,          NULL,                                                                 FALSE, FALSE, 122),
('ISCAT',        'DIGITAL', 'ISCAT',        NULL,          NULL,                                                                 FALSE, FALSE, 123),
('JT4',          'DIGITAL', 'JT4',          NULL,          ARRAY['JT4A','JT4B','JT4C','JT4D','JT4E','JT4F','JT4G'],         FALSE, FALSE, 124),
('JT44',         'DIGITAL', 'JT44',         NULL,          NULL,                                                                 FALSE, FALSE, 125),
('JT6M',         'DIGITAL', 'JT6M',         NULL,          NULL,                                                                 FALSE, FALSE, 126),
('MSK144',       'DIGITAL', 'MSK144',       NULL,          NULL,                                                                 FALSE, FALSE, 127),
('MT63',         'DIGITAL', 'MT63',         NULL,          NULL,                                                                 FALSE, FALSE, 128),
('OPERA',        'DIGITAL', 'OPERA',        NULL,          NULL,                                                                 FALSE, FALSE, 129),
('PAC',          'DATA',    'PAC',          NULL,          ARRAY['PAC2','PAC3'],                                               FALSE, FALSE, 130),
('PAX',          'DATA',    'PAX',          NULL,          ARRAY['PAX2'],                                                      FALSE, FALSE, 131),
('PSK',          'DIGITAL', 'PSK',          NULL,          ARRAY['PSK31','PSK63','FSK31','PSK10','PSK63F','PSK125','PSKAM10','PSKAM31','PSKAM50','PSKFEC31','QPSK31','QPSK63','QPSK125'], FALSE, FALSE, 132),
('PSK2K',        'DIGITAL', 'PSK2K',        NULL,          NULL,                                                                 FALSE, FALSE, 133),
('Q15',          'DIGITAL', 'Q15',          NULL,          NULL,                                                                 FALSE, FALSE, 134),
('QRA64',        'DIGITAL', 'QRA64',        NULL,          NULL,                                                                 FALSE, FALSE, 135),
('ROS',          'DIGITAL', 'ROS',          NULL,          NULL,                                                                 FALSE, FALSE, 136),
('RTTYM',        'DIGITAL', 'RTTYM',        NULL,          NULL,                                                                 FALSE, FALSE, 137),
('T10',          'DIGITAL', 'T10',          NULL,          NULL,                                                                 FALSE, FALSE, 138),
('THRB',         'DIGITAL', 'THRB',         NULL,          ARRAY['THRBX'],                                                     FALSE, FALSE, 139),
('TOR',          'DATA',    'TOR',          NULL,          ARRAY['AMTORFEC','GTOR'],                                          FALSE, FALSE, 140),
('V4',           'DIGITAL', 'V4',           NULL,          NULL,                                                                 FALSE, FALSE, 141),
('VOI',          'PHONE',   'VOI',          NULL,          NULL,                                                                 TRUE,  FALSE, 142),
('WINMOR',       'DATA',    'WINMOR',       NULL,          NULL,                                                                 FALSE, FALSE, 143)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    adif_mode = EXCLUDED.adif_mode,
    adif_submode = EXCLUDED.adif_submode,
    submodes = EXCLUDED.submodes,
    is_analog = EXCLUDED.is_analog,
    is_popular = EXCLUDED.is_popular,
    sort_order = EXCLUDED.sort_order;


-- ─────────────────────────────────────────────────────────────────────────────
-- DXCC ENTITIES
-- Source: k0swe/dxcc-json (dxcc-2020-02.csv), current entities.
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO dxcc_entities (entity_id, name, lotw_entity_name, prefix, continent, cq_zone, itu_zone, deleted, valid_from, valid_to)
VALUES
    (1,   'Canada',                                   'Canada',                                   'VA',   'NA', 1,  2,  FALSE, NULL,         NULL),
    (3,   'Afghanistan',                              'Afghanistan',                              'YA',   'AS', 21, 40, FALSE, NULL,         NULL),
    (4,   'Agaléga and Saint Brandon',               'Agaléga and Saint Brandon',               '3B6',  'AF', 39, 53, FALSE, NULL,         NULL),
    (5,   'Åland Islands',                            'Åland Islands',                            'OH0',  'EU', 15, 18, FALSE, NULL,         NULL),
    (6,   'Alaska',                                   'Alaska',                                   'KL',   'NA', 1,  1,  FALSE, NULL,         NULL),
    (7,   'Albania',                                  'Albania',                                  'ZA',   'EU', 15, 28, FALSE, NULL,         NULL),
    (9,   'American Samoa',                           'American Samoa',                           'KH8',  'OC', 32, 62, FALSE, NULL,         NULL),
    (10,  'Amsterdam and Saint-Paul Islands',         'Amsterdam and Saint-Paul Islands',         'FT/Z', 'AF', 39, 68, FALSE, NULL,         NULL),
    (11,  'Andaman and Nicobar Islands',              'Andaman and Nicobar Islands',              'VU4',  'AS', 26, 49, FALSE, NULL,         NULL),
    (12,  'Anguilla',                                 'Anguilla',                                 'VP2E', 'NA', 8,  11, FALSE, NULL,         NULL),
    (13,  'Antarctica',                               'Antarctica',                               'CE9',  'AN', 12, 67, FALSE, NULL,         NULL),
    (14,  'Armenia',                                  'Armenia',                                  'EK',   'AS', 21, 29, FALSE, NULL,         NULL),
    (15,  'Asiatic Russia',                           'Asiatic Russia',                           'UA0',  'AS', 16, 20, FALSE, NULL,         NULL),
    (16,  'New Zealand Subantarctic Islands',         'New Zealand Subantarctic Islands',         'ZL9',  'OC', 32, 60, FALSE, NULL,         NULL),
    (17,  'Isla de Aves',                             'Isla de Aves',                             'YV0',  'NA', 8,  11, FALSE, NULL,         NULL),
    (18,  'Azerbaijan',                               'Azerbaijan',                               '4J',   'AS', 21, 29, FALSE, NULL,         NULL),
    (20,  'Howland and Baker Islands',                'Howland and Baker Islands',                'KH1',  'OC', 31, 61, FALSE, NULL,         NULL),
    (21,  'Balearic Islands',                         'Balearic Islands',                         'EA6',  'EU', 14, 37, FALSE, NULL,         NULL),
    (22,  'Palau',                                    'Palau',                                    'T8',   'OC', 27, 64, FALSE, '1994-01-01', NULL),
    (24,  'Bouvet Island',                            'Bouvet Island',                            '3Y',   'AF', 38, 67, FALSE, NULL,         NULL),
    (27,  'Belarus',                                  'Belarus',                                  'EU',   'EU', 16, 29, FALSE, NULL,         NULL),
    (29,  'Canary Islands',                           'Canary Islands',                           'EA8',  'AF', 33, 36, FALSE, NULL,         NULL),
    (31,  'Phoenix Islands',                          'Phoenix Islands',                          'T31',  'OC', 31, 62, FALSE, NULL,         NULL),
    (32,  'Ceuta and Melilla',                        'Ceuta and Melilla',                        'EA9',  'AF', 33, 37, FALSE, NULL,         NULL),
    (33,  'Chagos Islands',                           'Chagos Islands',                           'VQ9',  'AF', 39, 41, FALSE, NULL,         NULL),
    (34,  'Chatham Islands',                          'Chatham Islands',                          'ZL7',  'OC', 32, 60, FALSE, NULL,         NULL),
    (35,  'Christmas Island',                         'Christmas Island',                         'VK9X', 'OC', 29, 54, FALSE, NULL,         NULL),
    (36,  'Clipperton Island',                        'Clipperton Island',                        'FO',   'NA', 7,  10, FALSE, NULL,         NULL),
    (37,  'Cocos Island',                             'Cocos Island',                             'TI9',  'NA', 7,  12, FALSE, NULL,         NULL),
    (38,  'Cocos (Keeling) Islands',                  'Cocos (Keeling) Islands',                  'VK9C', 'OC', 29, 54, FALSE, NULL,         NULL),
    (40,  'Crete',                                    'Crete',                                    'SV9',  'EU', 20, 28, FALSE, NULL,         NULL),
    (41,  'Crozet Islands',                           'Crozet Islands',                           'FT/W', 'AF', 39, 68, FALSE, NULL,         NULL),
    (43,  'Desecheo Island',                          'Desecheo Island',                          'KP5',  'NA', 8,  11, FALSE, '1979-03-01', NULL),
    (45,  'Dodecanese',                               'Dodecanese',                               'SV5',  'EU', 20, 28, FALSE, NULL,         NULL),
    (46,  'East Malaysia',                            'East Malaysia',                            '9M6',  'OC', 28, 54, FALSE, '1963-09-16', NULL),
    (47,  'Easter Island',                            'Easter Island',                            'CE0',  'SA', 12, 63, FALSE, NULL,         NULL),
    (48,  'Line Islands',                             'Line Islands',                             'T32',  'OC', 31, 61, FALSE, NULL,         NULL),
    (49,  'Equatorial Guinea',                        'Equatorial Guinea',                        '3C',   'AF', 36, 47, FALSE, NULL,         NULL),
    (50,  'Mexico',                                   'Mexico',                                   'XA',   'NA', 6,  10, FALSE, NULL,         NULL),
    (51,  'Eritrea',                                  'Eritrea',                                  'E3',   'AF', 37, 48, FALSE, NULL,         NULL),
    (52,  'Estonia',                                  'Estonia',                                  'ES',   'EU', 15, 29, FALSE, NULL,         NULL),
    (53,  'Ethiopia',                                 'Ethiopia',                                 'ET',   'AF', 37, 48, FALSE, NULL,         NULL),
    (54,  'European Russia',                          'European Russia',                          'UA1',  'EU', 16, 19, FALSE, NULL,         NULL),
    (56,  'Fernando de Noronha',                      'Fernando de Noronha',                      'PP0F', 'SA', 11, 13, FALSE, NULL,         NULL),
    (60,  'Bahamas',                                  'Bahamas',                                  'C6',   'NA', 8,  11, FALSE, NULL,         NULL),
    (61,  'Franz Josef Land',                         'Franz Josef Land',                         'R1/F', 'EU', 40, 75, FALSE, NULL,         NULL),
    (62,  'Barbados',                                 'Barbados',                                 '8P',   'NA', 8,  11, FALSE, NULL,         NULL),
    (63,  'French Guiana',                            'French Guiana',                            'FY',   'SA', 9,  12, FALSE, NULL,         NULL),
    (64,  'Bermuda',                                  'Bermuda',                                  'VP9',  'NA', 5,  11, FALSE, NULL,         NULL),
    (65,  'British Virgin Is.',                       'British Virgin Is.',                       'VP2V', 'NA', 8,  11, FALSE, NULL,         NULL),
    (66,  'Belize',                                   'Belize',                                   'V3',   'NA', 7,  11, FALSE, NULL,         NULL),
    (69,  'Cayman Islands',                           'Cayman Islands',                           'ZF',   'NA', 8,  11, FALSE, NULL,         NULL),
    (70,  'Cuba',                                     'Cuba',                                     'CM',   'NA', 8,  11, FALSE, NULL,         NULL),
    (71,  'Galápagos Islands',                        'Galápagos Islands',                        'HC8',  'SA', 10, 12, FALSE, NULL,         NULL),
    (72,  'Dominican Republic',                       'Dominican Republic',                       'HI',   'NA', 8,  11, FALSE, NULL,         NULL),
    (74,  'El Salvador',                              'El Salvador',                              'YS',   'NA', 7,  11, FALSE, NULL,         NULL),
    (75,  'Georgia',                                  'Georgia',                                  '4L',   'AS', 21, 29, FALSE, NULL,         NULL),
    (76,  'Guatemala',                                'Guatemala',                                'TG',   'NA', 7,  12, FALSE, NULL,         NULL),
    (77,  'Grenada',                                  'Grenada',                                  'J3',   'NA', 8,  11, FALSE, NULL,         NULL),
    (78,  'Haiti',                                    'Haiti',                                    'HH',   'NA', 8,  11, FALSE, NULL,         NULL),
    (79,  'Guadeloupe',                               'Guadeloupe',                               'FG',   'NA', 8,  11, FALSE, NULL,         NULL),
    (80,  'Honduras',                                 'Honduras',                                 'HQ',   'NA', 7,  11, FALSE, NULL,         NULL),
    (82,  'Jamaica',                                  'Jamaica',                                  '6Y',   'NA', 8,  11, FALSE, NULL,         NULL),
    (84,  'Martinique',                               'Martinique',                               'FM',   'NA', 8,  11, FALSE, NULL,         NULL),
    (86,  'Nicaragua',                                'Nicaragua',                                'YN',   'NA', 7,  11, FALSE, NULL,         NULL),
    (88,  'Panama',                                   'Panama',                                   'HO',   'NA', 7,  11, FALSE, NULL,         NULL),
    (89,  'Turks and Caicos Islands',                 'Turks and Caicos Islands',                 'VP5',  'NA', 8,  11, FALSE, NULL,         NULL),
    (90,  'Trinidad and Tobago',                      'Trinidad and Tobago',                      '9Y',   'SA', 9,  11, FALSE, NULL,         NULL),
    (91,  'Aruba',                                    'Aruba',                                    'P4',   'SA', 9,  11, FALSE, '1986-01-01', NULL),
    (94,  'Antigua and Barbuda',                      'Antigua and Barbuda',                      'V2',   'NA', 8,  11, FALSE, NULL,         NULL),
    (95,  'Dominica',                                 'Dominica',                                 'J7',   'NA', 8,  11, FALSE, NULL,         NULL),
    (96,  'Montserrat',                               'Montserrat',                               'VP2M', 'NA', 8,  11, FALSE, NULL,         NULL),
    (97,  'Saint Lucia',                              'Saint Lucia',                              'J6',   'NA', 8,  11, FALSE, NULL,         NULL),
    (98,  'Saint Vincent and the Grenadines',         'Saint Vincent and the Grenadines',         'J8',   'NA', 8,  11, FALSE, NULL,         NULL),
    (99,  'Glorioso Islands',                         'Glorioso Islands',                         'FT/G', 'AF', 39, 53, FALSE, '1960-06-25', NULL),
    (100, 'Argentina',                                'Argentina',                                'LO',   'SA', 13, 14, FALSE, NULL,         NULL),
    (103, 'Guam',                                     'Guam',                                     'KH2',  'OC', 27, 64, FALSE, NULL,         NULL),
    (104, 'Bolivia',                                  'Bolivia',                                  'CP',   'SA', 10, 12, FALSE, NULL,         NULL),
    (105, 'Guantanamo Bay',                           'Guantanamo Bay',                           'KG4',  'NA', 8,  11, FALSE, NULL,         NULL),
    (106, 'Guernsey',                                 'Guernsey',                                 'GU',   'EU', 14, 27, FALSE, NULL,         NULL),
    (107, 'Guinea',                                   'Guinea',                                   '3X',   'AF', 35, 46, FALSE, NULL,         NULL),
    (108, 'Brazil',                                   'Brazil',                                   'PP',   'SA', 11, 12, FALSE, NULL,         NULL),
    (109, 'Guinea-Bissau',                            'Guinea-Bissau',                            'J5',   'AF', 35, 46, FALSE, NULL,         NULL),
    (110, 'Hawaii',                                   'Hawaii',                                   'KH6',  'OC', 31, 61, FALSE, NULL,         NULL),
    (111, 'Heard Island and McDonald Islands',        'Heard Island and McDonald Islands',        'VK0',  'AF', 39, 68, FALSE, NULL,         NULL),
    (112, 'Chile',                                    'Chile',                                    'CA',   'SA', 12, 14, FALSE, NULL,         NULL),
    (114, 'Isle of Man',                              'Isle of Man',                              'GD',   'EU', 14, 27, FALSE, NULL,         NULL),
    (116, 'Colombia',                                 'Colombia',                                 'HJ',   'SA', 9,  12, FALSE, NULL,         NULL),
    (117, 'International Telecommunication Union Headquarters', 'International Telecommunication Union Headquarters', '4U', 'EU', 14, 28, FALSE, NULL, NULL),
    (118, 'Jan Mayen',                                'Jan Mayen',                                'JX',   'EU', 40, 18, FALSE, NULL,         NULL),
    (120, 'Ecuador',                                  'Ecuador',                                  'HC',   'SA', 10, 12, FALSE, NULL,         NULL),
    (122, 'Jersey',                                   'Jersey',                                   'GJ',   'EU', 14, 27, FALSE, NULL,         NULL),
    (123, 'Johnston Atoll',                           'Johnston Atoll',                           'KH3',  'OC', 31, 61, FALSE, NULL,         NULL),
    (124, 'Juan de Nova and Europa Islands',          'Juan de Nova and Europa Islands',          'FT/J', 'AF', 39, 53, FALSE, '1960-06-25', NULL),
    (125, 'Juan Fernández Islands',                   'Juan Fernández Islands',                   'CE0',  'SA', 12, 14, FALSE, NULL,         NULL),
    (126, 'Kaliningrad',                              'Kaliningrad',                              'UA2',  'EU', 15, 29, FALSE, NULL,         NULL),
    (129, 'Guyana',                                   'Guyana',                                   '8R',   'SA', 9,  12, FALSE, NULL,         NULL),
    (130, 'Kazakhstan',                               'Kazakhstan',                               'UN',   'AS', 17, 29, FALSE, NULL,         NULL),
    (131, 'Kerguelen Islands',                        'Kerguelen Islands',                        'FT/X', 'AF', 39, 68, FALSE, NULL,         NULL),
    (132, 'Paraguay',                                 'Paraguay',                                 'ZP',   'SA', 11, 14, FALSE, NULL,         NULL),
    (133, 'Kermadec Islands',                         'Kermadec Islands',                         'ZL8',  'OC', 32, 60, FALSE, NULL,         NULL),
    (135, 'Kyrgyzstan',                               'Kyrgyzstan',                               'EX',   'AS', 17, 30, FALSE, NULL,         NULL),
    (136, 'Peru',                                     'Peru',                                     'OA',   'SA', 10, 12, FALSE, NULL,         NULL),
    (137, 'South Korea',                              'South Korea',                              'HL',   'AS', 25, 44, FALSE, NULL,         NULL),
    (138, 'Kure Atoll',                               'Kure Atoll',                               'KH7K', 'OC', 31, 61, FALSE, NULL,         NULL),
    (140, 'Suriname',                                 'Suriname',                                 'PZ',   'SA', 9,  12, FALSE, NULL,         NULL),
    (141, 'Falkland Islands',                         'Falkland Islands',                         'VP8',  'SA', 13, 16, FALSE, NULL,         NULL),
    (142, 'Lakshadweep',                              'Lakshadweep',                              'VU7',  'AS', 22, 41, FALSE, NULL,         NULL),
    (143, 'Laos',                                     'Laos',                                     'XW',   'AS', 26, 49, FALSE, NULL,         NULL),
    (144, 'Uruguay',                                  'Uruguay',                                  'CV',   'SA', 13, 14, FALSE, NULL,         NULL),
    (145, 'Latvia',                                   'Latvia',                                   'YL',   'EU', 15, 29, FALSE, NULL,         NULL),
    (146, 'Lithuania',                                'Lithuania',                                'LY',   'EU', 15, 29, FALSE, NULL,         NULL),
    (147, 'Lord Howe Island',                         'Lord Howe Island',                         'VK9L', 'OC', 30, 60, FALSE, NULL,         NULL),
    (148, 'Venezuela',                                'Venezuela',                                'YV',   'SA', 9,  12, FALSE, NULL,         NULL),
    (149, 'Azores',                                   'Azores',                                   'CU',   'EU', 14, 36, FALSE, NULL,         NULL),
    (150, 'Australia',                                'Australia',                                'VK',   'OC', 29, 55, FALSE, NULL,         NULL),
    (152, 'Macao',                                    'Macao',                                    'XX9',  'AS', 24, 44, FALSE, NULL,         NULL),
    (153, 'Macquarie Island',                         'Macquarie Island',                         'VK0',  'OC', 30, 60, FALSE, NULL,         NULL),
    (157, 'Nauru',                                    'Nauru',                                    'C2',   'OC', 31, 65, FALSE, NULL,         NULL),
    (158, 'Vanuatu',                                  'Vanuatu',                                  'YJ',   'OC', 32, 56, FALSE, NULL,         NULL),
    (159, 'Maldives',                                 'Maldives',                                 '8Q',   'AS', 22, 41, FALSE, NULL,         NULL),
    (160, 'Tonga',                                    'Tonga',                                    'A3',   'OC', 32, 62, FALSE, NULL,         NULL),
    (161, 'Malpelo Island',                           'Malpelo Island',                           'HK0',  'SA', 9,  12, FALSE, NULL,         NULL),
    (162, 'New Caledonia',                            'New Caledonia',                            'FK',   'OC', 32, 56, FALSE, NULL,         NULL),
    (163, 'Papua New Guinea',                         'Papua New Guinea',                         'P2',   'OC', 28, 51, FALSE, '1975-09-16', NULL),
    (165, 'Mauritius',                                'Mauritius',                                '3B8',  'AF', 39, 53, FALSE, NULL,         NULL),
    (166, 'Mariana Islands',                          'Mariana Islands',                          'KH0',  'OC', 27, 64, FALSE, NULL,         NULL),
    (167, 'Märket Island',                            'Märket Island',                            'OJ0',  'EU', 15, 18, FALSE, NULL,         NULL),
    (168, 'Marshall Islands',                         'Marshall Islands',                         'V7',   'OC', 31, 65, FALSE, NULL,         NULL),
    (169, 'Mayotte',                                  'Mayotte',                                  'FH',   'AF', 39, 53, FALSE, '1975-07-06', NULL),
    (170, 'New Zealand',                              'New Zealand',                              'ZL',   'OC', 32, 60, FALSE, NULL,         NULL),
    (171, 'Mellish Reef',                             'Mellish Reef',                             'VK9M', 'OC', 30, 56, FALSE, NULL,         NULL),
    (172, 'Pitcairn Islands',                         'Pitcairn Islands',                         'VP6',  'OC', 32, 63, FALSE, NULL,         NULL),
    (173, 'Micronesia',                               'Micronesia',                               'V6',   'OC', 27, 65, FALSE, NULL,         NULL),
    (174, 'Midway Atoll',                             'Midway Atoll',                             'KH4',  'OC', 31, 61, FALSE, NULL,         NULL),
    (175, 'French Polynesia',                         'French Polynesia',                         'FO',   'OC', 32, 63, FALSE, NULL,         NULL),
    (176, 'Fiji',                                     'Fiji',                                     '3D2',  'OC', 32, 56, FALSE, NULL,         NULL),
    (177, 'Minami-Tori-shima',                        'Minami-Tori-shima',                        'JD1',  'OC', 27, 90, FALSE, NULL,         NULL),
    (179, 'Moldova',                                  'Moldova',                                  'ER',   'EU', 16, 29, FALSE, NULL,         NULL),
    (180, 'Mount Athos',                              'Mount Athos',                              'SV/A', 'EU', 20, 28, FALSE, NULL,         NULL),
    (181, 'Mozambique',                               'Mozambique',                               'C8',   'AF', 37, 53, FALSE, NULL,         NULL),
    (182, 'Navassa Island',                           'Navassa Island',                           'KP1',  'NA', 8,  11, FALSE, NULL,         NULL),
    (185, 'Solomon Islands',                          'Solomon Islands',                          'H4',   'OC', 28, 51, FALSE, NULL,         NULL),
    (187, 'Niger',                                    'Niger',                                    '5U',   'AF', 35, 46, FALSE, '1960-08-03', NULL),
    (188, 'Niue',                                     'Niue',                                     'E6',   'OC', 32, 62, FALSE, NULL,         NULL),
    (189, 'Norfolk Island',                           'Norfolk Island',                           'VK9N', 'OC', 32, 60, FALSE, NULL,         NULL),
    (190, 'Samoa',                                    'Samoa',                                    '5W',   'OC', 32, 62, FALSE, NULL,         NULL),
    (191, 'North Cook Islands',                       'North Cook Islands',                       'E5',   'OC', 32, 62, FALSE, NULL,         NULL),
    (192, 'Ogasawara Islands',                        'Ogasawara Islands',                        'JD1',  'AS', 27, 45, FALSE, NULL,         NULL),
    (195, 'Annobón',                                  'Annobón',                                  '3C0',  'AF', 36, 52, FALSE, NULL,         NULL),
    (197, 'Palmyra and Jarvis Islands',               'Palmyra and Jarvis Islands',               'KH5',  'OC', 31, 61, FALSE, NULL,         NULL),
    (199, 'Peter I Island',                           'Peter I Island',                           '3Y',   'AN', 12, 72, FALSE, NULL,         NULL),
    (201, 'Prince Edward and Marion Islands',         'Prince Edward and Marion Islands',         'ZS8',  'AF', 38, 57, FALSE, NULL,         NULL),
    (202, 'Puerto Rico',                              'Puerto Rico',                              'KP3',  'NA', 8,  11, FALSE, NULL,         NULL),
    (203, 'Andorra',                                  'Andorra',                                  'C3',   'EU', 14, 27, FALSE, NULL,         NULL),
    (204, 'Revillagigedo Islands',                    'Revillagigedo Islands',                    'XA4',  'NA', 6,  10, FALSE, NULL,         NULL),
    (205, 'Ascension Island',                         'Ascension Island',                         'ZD8',  'AF', 36, 66, FALSE, NULL,         NULL),
    (206, 'Austria',                                  'Austria',                                  'OE',   'EU', 15, 28, FALSE, NULL,         NULL),
    (207, 'Rodrigues Island',                         'Rodrigues Island',                         '3B9',  'AF', 39, 53, FALSE, NULL,         NULL),
    (209, 'Belgium',                                  'Belgium',                                  'ON',   'EU', 14, 27, FALSE, NULL,         NULL),
    (211, 'Sable Island',                             'Sable Island',                             'CY0',  'NA', 5,  9,  FALSE, NULL,         NULL),
    (212, 'Bulgaria',                                 'Bulgaria',                                 'LZ',   'EU', 20, 28, FALSE, NULL,         NULL),
    (213, 'Saint Martin',                             'Saint Martin',                             'FS',   'NA', 8,  11, FALSE, NULL,         NULL),
    (214, 'Corsica',                                  'Corsica',                                  'TK',   'EU', 15, 28, FALSE, NULL,         NULL),
    (215, 'Cyprus',                                   'Cyprus',                                   '5B',   'AS', 20, 39, FALSE, NULL,         NULL),
    (216, 'San Andrés and Providencia',               'San Andrés and Providencia',               'HK0',  'NA', 7,  11, FALSE, NULL,         NULL),
    (217, 'Desventuradas Islands',                    'Desventuradas Islands',                    'CE0',  'SA', 12, 14, FALSE, NULL,         NULL),
    (219, 'Sao Tome and Principe',                    'Sao Tome and Principe',                    'S9',   'AF', 36, 47, FALSE, NULL,         NULL),
    (221, 'Denmark',                                  'Denmark',                                  'OU',   'EU', 14, 18, FALSE, NULL,         NULL),
    (222, 'Faroe Islands',                            'Faroe Islands',                            'OY',   'EU', 14, 18, FALSE, NULL,         NULL),
    (223, 'England',                                  'England',                                  'G',    'EU', 14, 27, FALSE, NULL,         NULL),
    (224, 'Finland',                                  'Finland',                                  'OF',   'EU', 15, 18, FALSE, NULL,         NULL),
    (225, 'Sardinia',                                 'Sardinia',                                 'IS0',  'EU', 15, 28, FALSE, NULL,         NULL),
    (227, 'France',                                   'France',                                   'F',    'EU', 14, 27, FALSE, NULL,         NULL),
    (230, 'Germany',                                  'Germany',                                  'DA',   'EU', 14, 28, FALSE, NULL,         NULL),
    (232, 'Somalia',                                  'Somalia',                                  'T5',   'AF', 37, 48, FALSE, NULL,         NULL),
    (233, 'Gibraltar',                                'Gibraltar',                                'ZB2',  'EU', 14, 37, FALSE, NULL,         NULL),
    (234, 'South Cook Islands',                       'South Cook Islands',                       'E5',   'OC', 32, 62, FALSE, NULL,         NULL),
    (235, 'South Georgia Island',                     'South Georgia Island',                     'VP8',  'SA', 13, 73, FALSE, NULL,         NULL),
    (236, 'Greece',                                   'Greece',                                   'SV',   'EU', 20, 28, FALSE, NULL,         NULL),
    (237, 'Greenland',                                'Greenland',                                'OX',   'NA', 40, 5,  FALSE, NULL,         NULL),
    (238, 'South Orkney Islands',                     'South Orkney Islands',                     'VP8',  'SA', 13, 73, FALSE, NULL,         NULL),
    (239, 'Hungary',                                  'Hungary',                                  'HA',   'EU', 15, 28, FALSE, NULL,         NULL),
    (240, 'South Sandwich Islands',                   'South Sandwich Islands',                   'VP8',  'SA', 13, 73, FALSE, NULL,         NULL),
    (241, 'South Shetland Islands',                   'South Shetland Islands',                   'VP8',  'SA', 13, 73, FALSE, NULL,         NULL),
    (242, 'Iceland',                                  'Iceland',                                  'TF',   'EU', 40, 17, FALSE, NULL,         NULL),
    (245, 'Ireland',                                  'Ireland',                                  'EI',   'EU', 14, 27, FALSE, NULL,         NULL),
    (246, 'Sovereign Military Order of Malta',        'Sovereign Military Order of Malta',        '1A',   'EU', 15, 28, FALSE, NULL,         NULL),
    (247, 'Spratly Islands',                          'Spratly Islands',                          '',     'AS', 26, 50, FALSE, NULL,         NULL),
    (248, 'Italy',                                    'Italy',                                    'I',    'EU', 15, 28, FALSE, NULL,         NULL),
    (249, 'Saint Kitts and Nevis',                    'Saint Kitts and Nevis',                    'V4',   'NA', 8,  11, FALSE, NULL,         NULL),
    (250, 'St. Helena',                               'St. Helena',                               'ZD7',  'AF', 36, 66, FALSE, NULL,         NULL),
    (251, 'Liechtenstein',                            'Liechtenstein',                            'HB0',  'EU', 14, 28, FALSE, NULL,         NULL),
    (252, 'St. Paul Island',                          'St. Paul Island',                          'CY9',  'NA', 5,  9,  FALSE, NULL,         NULL),
    (253, 'Saint Peter and Saint Paul Archipelago',   'Saint Peter and Saint Paul Archipelago',   'PP0S', 'SA', 11, 13, FALSE, NULL,         NULL),
    (254, 'Luxembourg',                               'Luxembourg',                               'LX',   'EU', 14, 27, FALSE, NULL,         NULL),
    (256, 'Madeira',                                  'Madeira',                                  'CT3',  'AF', 33, 36, FALSE, NULL,         NULL),
    (257, 'Malta',                                    'Malta',                                    '9H',   'EU', 15, 28, FALSE, NULL,         NULL),
    (259, 'Svalbard',                                 'Svalbard',                                 'JW',   'EU', 40, 18, FALSE, NULL,         NULL),
    (260, 'Monaco',                                   'Monaco',                                   '3A',   'EU', 14, 27, FALSE, NULL,         NULL),
    (262, 'Tajikistan',                               'Tajikistan',                               'EY',   'AS', 17, 30, FALSE, NULL,         NULL),
    (263, 'Netherlands',                              'Netherlands',                              'PA',   'EU', 14, 27, FALSE, NULL,         NULL),
    (265, 'Northern Ireland',                         'Northern Ireland',                         'GI',   'EU', 14, 27, FALSE, NULL,         NULL),
    (266, 'Norway',                                   'Norway',                                   'LA',   'EU', 14, 18, FALSE, NULL,         NULL),
    (269, 'Poland',                                   'Poland',                                   'SN',   'EU', 15, 28, FALSE, NULL,         NULL),
    (270, 'Tokelau',                                  'Tokelau',                                  'ZK3',  'OC', 31, 62, FALSE, NULL,         NULL),
    (272, 'Portugal',                                 'Portugal',                                 'CT',   'EU', 14, 37, FALSE, NULL,         NULL),
    (273, 'Trindade and Martin Vaz',                  'Trindade and Martin Vaz',                  'PP0T', 'SA', 11, 15, FALSE, NULL,         NULL),
    (274, 'Tristan da Cunha and Gough Islands',       'Tristan da Cunha and Gough Islands',       'ZD9',  'AF', 38, 66, FALSE, NULL,         NULL),
    (275, 'Romania',                                  'Romania',                                  'YO',   'EU', 20, 28, FALSE, NULL,         NULL),
    (276, 'Tromelin Island',                          'Tromelin Island',                          'FT/T', 'AF', 39, 53, FALSE, NULL,         NULL),
    (277, 'Saint Pierre and Miquelon',                'Saint Pierre and Miquelon',                'FP',   'NA', 5,  9,  FALSE, NULL,         NULL),
    (278, 'San Marino',                               'San Marino',                               'T7',   'EU', 15, 28, FALSE, NULL,         NULL),
    (279, 'Scotland',                                 'Scotland',                                 'GM',   'EU', 14, 27, FALSE, NULL,         NULL),
    (280, 'Turkmenistan',                             'Turkmenistan',                             'EZ',   'AS', 17, 30, FALSE, NULL,         NULL),
    (281, 'Spain',                                    'Spain',                                    'EA',   'EU', 14, 37, FALSE, NULL,         NULL),
    (282, 'Tuvalu',                                   'Tuvalu',                                   'T2',   'OC', 31, 65, FALSE, '1976-01-01', NULL),
    (283, 'Sovereign Base Areas of Akrotiri and Dhekelia', 'Sovereign Base Areas of Akrotiri and Dhekelia', 'ZC4', 'AS', 20, 39, FALSE, '1960-08-16', NULL),
    (284, 'Sweden',                                   'Sweden',                                   'SA',   'EU', 14, 18, FALSE, NULL,         NULL),
    (285, 'US Virgin Islands',                        'US Virgin Islands',                        'KP2',  'NA', 8,  11, FALSE, NULL,         NULL),
    (286, 'Uganda',                                   'Uganda',                                   '5X',   'AF', 37, 48, FALSE, NULL,         NULL),
    (287, 'Switzerland',                              'Switzerland',                              'HB',   'EU', 14, 28, FALSE, NULL,         NULL),
    (288, 'Ukraine',                                  'Ukraine',                                  'UR',   'EU', 16, 29, FALSE, NULL,         NULL),
    (289, 'United Nations Headquarters',              'United Nations Headquarters',              '4U',   'NA', 5,  8,  FALSE, NULL,         NULL),
    (291, 'United States of America',                 'United States of America',                 'K',    'NA', 3,  6,  FALSE, NULL,         NULL),
    (292, 'Uzbekistan',                               'Uzbekistan',                               'UJ',   'AS', 17, 30, FALSE, NULL,         NULL),
    (293, 'Viet Nam',                                 'Viet Nam',                                 '3W',   'AS', 26, 49, FALSE, NULL,         NULL),
    (294, 'Wales',                                    'Wales',                                    'GW',   'EU', 14, 27, FALSE, NULL,         NULL),
    (295, 'Vatican',                                  'Vatican',                                  'HV',   'EU', 15, 28, FALSE, NULL,         NULL),
    (296, 'Serbia',                                   'Serbia',                                   'YT',   'EU', 15, 28, FALSE, NULL,         NULL),
    (297, 'Wake Island',                              'Wake Island',                              'KH9',  'OC', 31, 65, FALSE, NULL,         NULL),
    (298, 'Wallis and Futuna Islands',                'Wallis and Futuna Islands',                'FW',   'OC', 32, 62, FALSE, NULL,         NULL),
    (299, 'West Malaysia',                            'West Malaysia',                            '9M2',  'AS', 28, 54, FALSE, '1963-09-16', NULL),
    (301, 'Gilbert Islands',                          'Gilbert Islands',                          'T30',  'OC', 31, 65, FALSE, NULL,         NULL),
    (302, 'Western Sahara',                           'Western Sahara',                           'S0',   'AF', 33, 46, FALSE, NULL,         NULL),
    (303, 'Willis Island',                            'Willis Island',                            'VK9W', 'OC', 30, 55, FALSE, NULL,         NULL),
    (304, 'Bahrain',                                  'Bahrain',                                  'A9',   'AS', 21, 39, FALSE, NULL,         NULL),
    (305, 'Bangladesh',                               'Bangladesh',                               'S2',   'AS', 22, 41, FALSE, NULL,         NULL),
    (306, 'Bhutan',                                   'Bhutan',                                   'A5',   'AS', 22, 41, FALSE, NULL,         NULL),
    (308, 'Costa Rica',                               'Costa Rica',                               'TI',   'NA', 7,  11, FALSE, NULL,         NULL),
    (309, 'Myanmar',                                  'Myanmar',                                  'XY',   'AS', 26, 49, FALSE, NULL,         NULL),
    (312, 'Cambodia',                                 'Cambodia',                                 'XU',   'AS', 26, 49, FALSE, NULL,         NULL),
    (315, 'Sri Lanka',                                'Sri Lanka',                                '4S',   'AS', 22, 41, FALSE, NULL,         NULL),
    (318, 'China',                                    'China',                                    'B',    'AS', 23, 33, FALSE, NULL,         NULL),
    (321, 'Hong Kong',                                'Hong Kong',                                'VR',   'AS', 24, 44, FALSE, NULL,         NULL),
    (324, 'India',                                    'India',                                    'VU',   'AS', 22, 41, FALSE, NULL,         NULL),
    (327, 'Indonesia',                                'Indonesia',                                'YB',   'OC', 28, 51, FALSE, '1963-05-01', NULL),
    (330, 'Iran',                                     'Iran',                                     'EP',   'AS', 21, 40, FALSE, NULL,         NULL),
    (333, 'Iraq',                                     'Iraq',                                     'YI',   'AS', 21, 39, FALSE, NULL,         NULL),
    (336, 'Israel',                                   'Israel',                                   '4X',   'AS', 20, 39, FALSE, NULL,         NULL),
    (339, 'Japan',                                    'Japan',                                    'JA',   'AS', 25, 45, FALSE, NULL,         NULL),
    (342, 'Jordan',                                   'Jordan',                                   'JY',   'AS', 20, 39, FALSE, NULL,         NULL),
    (344, 'Democratic People''s Republic of Korea',   'Democratic People''s Republic of Korea',   'P5',   'AS', 25, 44, FALSE, '1995-05-14', NULL),
    (345, 'Brunei Darussalam',                        'Brunei Darussalam',                        'V8',   'OC', 28, 54, FALSE, NULL,         NULL),
    (348, 'Kuwait',                                   'Kuwait',                                   '9K',   'AS', 21, 39, FALSE, NULL,         NULL),
    (354, 'Lebanon',                                  'Lebanon',                                  'OD',   'AS', 20, 39, FALSE, NULL,         NULL),
    (363, 'Mongolia',                                 'Mongolia',                                 'JT',   'AS', 23, 32, FALSE, NULL,         NULL),
    (369, 'Nepal',                                    'Nepal',                                    '9N',   'AS', 22, 42, FALSE, NULL,         NULL),
    (370, 'Oman',                                     'Oman',                                     'A4',   'AS', 21, 39, FALSE, NULL,         NULL),
    (372, 'Pakistan',                                 'Pakistan',                                 'AP',   'AS', 21, 41, FALSE, NULL,         NULL),
    (375, 'Philippines',                              'Philippines',                              'DU',   'OC', 27, 50, FALSE, NULL,         NULL),
    (376, 'Qatar',                                    'Qatar',                                    'A7',   'AS', 21, 39, FALSE, NULL,         NULL),
    (378, 'Saudi Arabia',                             'Saudi Arabia',                             'HZ',   'AS', 21, 39, FALSE, NULL,         NULL),
    (379, 'Seychelles',                               'Seychelles',                               'S7',   'AF', 39, 53, FALSE, NULL,         NULL),
    (381, 'Singapore',                                'Singapore',                                '9V',   'AS', 28, 54, FALSE, '1965-08-08', NULL),
    (382, 'Djibouti',                                 'Djibouti',                                 'J2',   'AF', 37, 48, FALSE, NULL,         NULL),
    (384, 'Syria',                                    'Syria',                                    'YK',   'AS', 20, 39, FALSE, NULL,         NULL),
    (386, 'Taiwan',                                   'Taiwan',                                   'BU',   'AS', 24, 44, FALSE, NULL,         NULL),
    (387, 'Thailand',                                 'Thailand',                                 'HS',   'AS', 26, 49, FALSE, NULL,         NULL),
    (390, 'Turkey',                                   'Turkey',                                   'TA',   'EU', 20, 39, FALSE, NULL,         NULL),
    (391, 'United Arab Emirates',                     'United Arab Emirates',                     'A6',   'AS', 21, 39, FALSE, NULL,         NULL),
    (400, 'Algeria',                                  'Algeria',                                  '7T',   'AF', 33, 37, FALSE, NULL,         NULL),
    (401, 'Angola',                                   'Angola',                                   'D2',   'AF', 36, 52, FALSE, NULL,         NULL),
    (402, 'Botswana',                                 'Botswana',                                 'A2',   'AF', 38, 57, FALSE, NULL,         NULL),
    (404, 'Burundi',                                  'Burundi',                                  '9U',   'AF', 36, 52, FALSE, '1962-07-01', NULL),
    (406, 'Cameroon',                                 'Cameroon',                                 'TJ',   'AF', 36, 47, FALSE, NULL,         NULL),
    (408, 'Central African Republic',                 'Central African Republic',                 'TL',   'AF', 36, 47, FALSE, '1960-08-13', NULL),
    (409, 'Cape Verde',                               'Cape Verde',                               'D4',   'AF', 35, 46, FALSE, NULL,         NULL),
    (410, 'Chad',                                     'Chad',                                     'TT',   'AF', 36, 47, FALSE, '1960-08-11', NULL),
    (411, 'Comoros',                                  'Comoros',                                  'D6',   'AF', 39, 53, FALSE, '1975-07-06', NULL),
    (412, 'Republic of the Congo',                    'Republic of the Congo',                    'TN',   'AF', 36, 52, FALSE, '1960-08-15', NULL),
    (414, 'Democratic Republic of the Congo',         'Democratic Republic of the Congo',         '9Q',   'AF', 36, 52, FALSE, NULL,         NULL),
    (416, 'Benin',                                    'Benin',                                    'TY',   'AF', 35, 46, FALSE, '1960-08-01', NULL),
    (420, 'Gabon',                                    'Gabon',                                    'TR',   'AF', 36, 52, FALSE, '1960-08-17', NULL),
    (422, 'The Gambia',                               'The Gambia',                               'C5',   'AF', 35, 46, FALSE, NULL,         NULL),
    (424, 'Ghana',                                    'Ghana',                                    '9G',   'AF', 35, 46, FALSE, '1957-03-05', NULL),
    (428, 'Côte d''Ivoire',                           'Côte d''Ivoire',                           'TU',   'AF', 35, 46, FALSE, '1960-08-07', NULL),
    (430, 'Kenya',                                    'Kenya',                                    '5Y',   'AF', 37, 48, FALSE, NULL,         NULL),
    (432, 'Lesotho',                                  'Lesotho',                                  '7P',   'AF', 38, 57, FALSE, NULL,         NULL),
    (434, 'Liberia',                                  'Liberia',                                  'EL',   'AF', 35, 46, FALSE, NULL,         NULL),
    (436, 'Libya',                                    'Libya',                                    '5A',   'AF', 34, 38, FALSE, NULL,         NULL),
    (438, 'Madagascar',                               'Madagascar',                               '5R',   'AF', 39, 53, FALSE, NULL,         NULL),
    (440, 'Malawi',                                   'Malawi',                                   '7Q',   'AF', 37, 53, FALSE, NULL,         NULL),
    (442, 'Mali',                                     'Mali',                                     'TZ',   'AF', 35, 46, FALSE, '1960-06-20', NULL),
    (444, 'Mauritania',                               'Mauritania',                               '5T',   'AF', 35, 46, FALSE, '1960-06-20', NULL),
    (446, 'Morocco',                                  'Morocco',                                  'CN',   'AF', 33, 37, FALSE, NULL,         NULL),
    (450, 'Nigeria',                                  'Nigeria',                                  '5N',   'AF', 35, 46, FALSE, NULL,         NULL),
    (452, 'Zimbabwe',                                 'Zimbabwe',                                 'Z2',   'AF', 38, 53, FALSE, NULL,         NULL),
    (453, 'Réunion',                                  'Réunion',                                  'FR',   'AF', 39, 53, FALSE, NULL,         NULL),
    (454, 'Rwanda',                                   'Rwanda',                                   '9X',   'AF', 36, 52, FALSE, '1962-07-01', NULL),
    (456, 'Senegal',                                  'Senegal',                                  '6V',   'AF', 35, 46, FALSE, '1960-06-20', NULL),
    (458, 'Sierra Leone',                             'Sierra Leone',                             '9L',   'AF', 35, 46, FALSE, NULL,         NULL),
    (460, 'Rotuma Island',                            'Rotuma Island',                            '3D2',  'OC', 32, 56, FALSE, NULL,         NULL),
    (462, 'South Africa',                             'South Africa',                             'ZR',   'AF', 38, 57, FALSE, NULL,         NULL),
    (464, 'Namibia',                                  'Namibia',                                  'V5',   'AF', 38, 57, FALSE, NULL,         NULL),
    (466, 'Sudan',                                    'Sudan',                                    'ST',   'AF', 34, 47, FALSE, NULL,         NULL),
    (468, 'Eswatini',                                 'Eswatini',                                 '3DA',  'AF', 38, 57, FALSE, NULL,         NULL),
    (470, 'Tanzania',                                 'Tanzania',                                 '5H',   'AF', 37, 53, FALSE, NULL,         NULL),
    (474, 'Tunisia',                                  'Tunisia',                                  '3V',   'AF', 33, 37, FALSE, NULL,         NULL),
    (478, 'Egypt',                                    'Egypt',                                    'SU',   'AF', 34, 38, FALSE, NULL,         NULL),
    (480, 'Burkina Faso',                             'Burkina Faso',                             'XT',   'AF', 35, 46, FALSE, '1960-08-16', NULL),
    (482, 'Zambia',                                   'Zambia',                                   '9I',   'AF', 36, 53, FALSE, NULL,         NULL),
    (483, 'Togo',                                     'Togo',                                     '5V',   'AF', 35, 46, FALSE, NULL,         NULL),
    (489, 'Conway Reef',                              'Conway Reef',                              '3D2',  'OC', 32, 56, FALSE, NULL,         NULL),
    (490, 'Banaba',                                   'Banaba',                                   'T33',  'OC', 31, 65, FALSE, NULL,         NULL),
    (492, 'Yemen',                                    'Yemen',                                    '7O',   'AS', 21, 39, FALSE, '1990-05-22', NULL),
    (497, 'Croatia',                                  'Croatia',                                  '9A',   'EU', 15, 28, FALSE, '1991-06-26', NULL),
    (499, 'Slovenia',                                 'Slovenia',                                 'S5',   'EU', 15, 28, FALSE, '1991-06-26', NULL),
    (501, 'Bosnia-Herzegovina',                       'Bosnia-Herzegovina',                       'E7',   'EU', 15, 28, FALSE, '1991-10-15', NULL),
    (502, 'North Macedonia',                          'North Macedonia',                          'Z3',   'EU', 15, 28, FALSE, '1991-09-08', NULL),
    (503, 'Czech Republic',                           'Czech Republic',                           'OK',   'EU', 15, 28, FALSE, '1993-01-01', NULL),
    (504, 'Slovakia',                                 'Slovakia',                                 'OM',   'EU', 15, 28, FALSE, '1993-01-01', NULL),
    (505, 'Pratas Island',                            'Pratas Island',                            'BV9P', 'AS', 24, 44, FALSE, '1994-01-01', NULL),
    (506, 'Scarborough Shoal',                        'Scarborough Shoal',                        'BS7',  'AS', 27, 50, FALSE, '1995-01-01', NULL),
    (507, 'Temotu Province',                          'Temotu Province',                          'H40',  'OC', 32, 51, FALSE, '1998-04-01', NULL),
    (508, 'Austral Islands',                          'Austral Islands',                          'FO',   'OC', 32, 63, FALSE, '1998-04-01', NULL),
    (509, 'Marquesas Islands',                        'Marquesas Islands',                        'FO',   'OC', 31, 63, FALSE, '1998-04-01', NULL),
    (510, 'Palestine',                                'Palestine',                                'E4',   'AS', 20, 39, FALSE, '1999-02-01', NULL),
    (511, 'Timor-Leste',                              'Timor-Leste',                              '4W',   'OC', 28, 54, FALSE, '2000-03-01', NULL),
    (512, 'Chesterfield Islands',                     'Chesterfield Islands',                     'FK',   'OC', 30, 56, FALSE, '2000-03-23', NULL),
    (513, 'Ducie Island',                             'Ducie Island',                             'VP6',  'OC', 32, 63, FALSE, '2001-11-16', NULL),
    (514, 'Montenegro',                               'Montenegro',                               '4O',   'EU', 15, 28, FALSE, '2006-06-28', NULL),
    (515, 'Swains Island',                            'Swains Island',                            'KH8',  'OC', 32, 62, FALSE, '2006-07-22', NULL),
    (516, 'Saint Barthélemy',                         'Saint Barthélemy',                         'FJ',   'NA', 8,  11, FALSE, '2007-12-14', NULL),
    (517, 'Curaçao',                                  'Curaçao',                                  'PJ2',  'SA', 9,  11, FALSE, '2010-10-10', NULL),
    (518, 'Sint Maarten',                             'Sint Maarten',                             'PJ7',  'NA', 8,  11, FALSE, '2010-10-10', NULL),
    (519, 'Saba and Sint Eustatius',                  'Saba and Sint Eustatius',                  'PJ5',  'NA', 8,  11, FALSE, '2010-10-10', NULL),
    (520, 'Bonaire',                                  'Bonaire',                                  'PJ4',  'SA', 9,  11, FALSE, '2010-10-10', NULL),
    (521, 'South Sudan',                              'South Sudan',                              'Z8',   'AF', 34, 48, FALSE, '2011-07-14', NULL),
    (522, 'Kosovo',                                   'Kosovo',                                   'Z6',   'EU', 15, 28, FALSE, '2018-01-21', NULL)
ON CONFLICT (entity_id) DO UPDATE SET
    name             = EXCLUDED.name,
    lotw_entity_name = EXCLUDED.lotw_entity_name,
    prefix           = EXCLUDED.prefix,
    continent        = EXCLUDED.continent,
    cq_zone          = EXCLUDED.cq_zone,
    itu_zone         = EXCLUDED.itu_zone,
    deleted          = EXCLUDED.deleted,
    valid_from       = EXCLUDED.valid_from,
    valid_to         = EXCLUDED.valid_to;


-- ─────────────────────────────────────────────────────────────────────────────
-- DXCC PREFIX ALIASES
-- Derived from dxcc_entities + high-impact manual aliases.
-- Must run after dxcc_entities seed.
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO dxcc_prefixes (prefix, entity_id, source)
SELECT prefix, entity_id, 'dxcc_entities'
FROM (
    SELECT DISTINCT ON (UPPER(BTRIM(prefix)))
           UPPER(BTRIM(prefix)) AS prefix,
           entity_id
    FROM dxcc_entities
    WHERE NULLIF(BTRIM(prefix), '') IS NOT NULL
      AND deleted = FALSE
    ORDER BY UPPER(BTRIM(prefix)), entity_id
) deduped
ON CONFLICT (prefix) DO UPDATE
SET entity_id = EXCLUDED.entity_id,
    source = EXCLUDED.source;

INSERT INTO dxcc_prefixes (prefix, entity_id, source)
VALUES
    -- United States of America (DXCC 291)
    ('W', 291, 'alias'),
    ('N', 291, 'alias'),
    ('AA', 291, 'alias'),
    ('AB', 291, 'alias'),
    ('AC', 291, 'alias'),
    ('AD', 291, 'alias'),
    ('AE', 291, 'alias'),
    ('AF', 291, 'alias'),
    ('AG', 291, 'alias'),
    ('AI', 291, 'alias'),
    ('AJ', 291, 'alias'),
    ('AK', 291, 'alias'),
    ('AL', 291, 'alias'),

    -- Canada (DXCC 1)
    ('VE', 1, 'alias'),
    ('VO', 1, 'alias'),
    ('VY', 1, 'alias'),
    ('CF', 1, 'alias'),
    ('CG', 1, 'alias'),
    ('CH', 1, 'alias'),
    ('CI', 1, 'alias'),
    ('CJ', 1, 'alias'),
    ('CK', 1, 'alias'),

    -- Japan (DXCC 339)
    ('JE', 339, 'alias'),
    ('JF', 339, 'alias'),
    ('JG', 339, 'alias'),
    ('JH', 339, 'alias'),
    ('JI', 339, 'alias'),
    ('JJ', 339, 'alias'),
    ('JK', 339, 'alias'),
    ('JL', 339, 'alias'),
    ('JM', 339, 'alias'),
    ('JN', 339, 'alias'),
    ('JO', 339, 'alias'),
    ('JP', 339, 'alias'),
    ('JQ', 339, 'alias'),
    ('JR', 339, 'alias'),
    ('JS', 339, 'alias'),
    ('7J', 339, 'alias'),
    ('7K', 339, 'alias'),
    ('7L', 339, 'alias'),
    ('7M', 339, 'alias'),
    ('7N', 339, 'alias'),
    ('8J', 339, 'alias')
ON CONFLICT (prefix) DO UPDATE
SET entity_id = EXCLUDED.entity_id,
    source = EXCLUDED.source;


-- +goose Down
-- Reference data is non-destructive; goose down is intentionally a no-op.
-- Data was inserted with ON CONFLICT DO UPDATE and can be re-run safely.
-- To remove: TRUNCATE bands, modes, dxcc_entities, dxcc_prefixes CASCADE;
