//! System tray icon/menu with live sync, UDP and rig status.

use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    AppHandle, Manager,
};
use tracing::{debug, error, info, warn};

use crate::auth;
use crate::rig::RigStatus;
use crate::AppState;

/// Embedded tray icon PNGs (generated by build.rs).
const ICON_IDLE: &[u8] = include_bytes!("../icons/tray/tray-idle.png");
const ICON_PENDING: &[u8] = include_bytes!("../icons/tray/tray-pending.png");
const ICON_ERROR: &[u8] = include_bytes!("../icons/tray/tray-error.png");
const ICON_DISCONNECTED: &[u8] = include_bytes!("../icons/tray/tray-disconnected.png");

/// Menu IDs.
const MENU_OPEN: &str = "open";
const MENU_TOGGLE_WSJTX: &str = "toggle_wsjtx";
const MENU_TOGGLE_JS8CALL: &str = "toggle_js8call";
const MENU_TOGGLE_N1MM: &str = "toggle_n1mm";
const MENU_SYNC_NOW: &str = "sync_now";
const MENU_QUIT: &str = "quit";

#[derive(Debug, Clone, Copy)]
enum TrayVisualState {
    Idle,
    Pending,
    Error,
    Disconnected,
}

#[derive(Debug, Clone)]
struct TraySnapshot {
    logged_in: bool,
    pending: i64,
    last_error: Option<String>,
    wsjtx_listening: bool,
    js8call_listening: bool,
    n1mm_listening: bool,
    rig: RigStatus,
}

/// Build and register the tray icon + menu.
pub fn setup_tray(app: &mut tauri::App) -> tauri::Result<()> {
    let handle = app.handle();

    // Build an initial menu synchronously, then refresh asynchronously with live data.
    let snapshot = TraySnapshot {
        logged_in: false,
        pending: 0,
        last_error: None,
        wsjtx_listening: false,
        js8call_listening: false,
        n1mm_listening: false,
        rig: RigStatus::default(),
    };

    let (menu, tooltip, visual_state) = build_menu(handle, &snapshot)?;

    let icon = icon_for_state(visual_state)?;

    let tray = TrayIconBuilder::new()
        .icon(icon)
        .menu(&menu)
        .tooltip(tooltip)
        .on_menu_event(|app, event| {
            handle_menu_event(app, event.id().as_ref());
        })
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                let app = tray.app_handle();
                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.show();
                    let _ = window.set_focus();
                }
            }
        })
        .build(app)?;

    {
        let state: tauri::State<'_, AppState> = handle.state();
        tauri::async_runtime::block_on(async {
            let mut slot = state.tray.lock().await;
            *slot = Some(tray.clone());
        });
    }

    // Pull real status after startup.
    let app_handle = handle.clone();
    tauri::async_runtime::spawn(async move {
        refresh_tray(&app_handle).await;
    });

    info!("System tray initialised");
    Ok(())
}

/// Rebuild icon + menu + tooltip from current runtime state.
pub async fn refresh_tray(app: &AppHandle) {
    let snapshot = snapshot(app).await;

    let Some(tray) = tray_handle(app).await else {
        debug!("Tray handle not ready yet; skipping refresh");
        return;
    };

    let Ok((menu, tooltip, visual_state)) = build_menu(app, &snapshot) else {
        warn!("Failed to build tray menu");
        return;
    };

    if let Err(e) = tray.set_menu(Some(menu)) {
        warn!("Failed to update tray menu: {e}");
    }

    if let Ok(icon) = icon_for_state(visual_state) {
        if let Err(e) = tray.set_icon(Some(icon)) {
            warn!("Failed to update tray icon: {e}");
        }
    }

    if let Err(e) = tray.set_tooltip(Some(tooltip)) {
        warn!("Failed to update tray tooltip: {e}");
    }
}

async fn tray_handle(app: &AppHandle) -> Option<tauri::tray::TrayIcon> {
    let state: tauri::State<'_, AppState> = app.state();
    let slot = state.tray.lock().await;
    slot.clone()
}

async fn snapshot(app: &AppHandle) -> TraySnapshot {
    let state: tauri::State<'_, AppState> = app.state();

    let logged_in = auth::load_access_token().ok().flatten().is_some();

    let (pending, last_error) = {
        let sync = state.sync.lock().await;
        let pending = sync.db.pending_count().unwrap_or(0);
        (pending, sync.last_error.clone())
    };

    let (wsjtx_listening, js8call_listening, n1mm_listening) = {
        let udp = state.udp.lock().await;
        (
            udp.is_wsjtx_listening(),
            udp.is_js8call_listening(),
            udp.is_n1mm_listening(),
        )
    };

    let rig = {
        let rig = state.rig.lock().await;
        rig.status()
    };

    TraySnapshot {
        logged_in,
        pending,
        last_error,
        wsjtx_listening,
        js8call_listening,
        n1mm_listening,
        rig,
    }
}

fn build_menu(
    app: &AppHandle,
    snapshot: &TraySnapshot,
) -> tauri::Result<(Menu<tauri::Wry>, String, TrayVisualState)> {
    let status_line = status_line(snapshot);
    let tooltip = tooltip(snapshot);

    let top_status = MenuItem::with_id(app, "status", &status_line, false, None::<&str>)?;
    let open_item = MenuItem::with_id(app, MENU_OPEN, "Open Window", true, None::<&str>)?;

    let udp_line = format!(
        "UDP: WSJT-X {}  JS8Call {}  N1MM+ {}",
        dot(snapshot.wsjtx_listening),
        dot(snapshot.js8call_listening),
        dot(snapshot.n1mm_listening),
    );
    let udp_status = MenuItem::with_id(app, "udp_status", udp_line, false, None::<&str>)?;

    let rig_status = MenuItem::with_id(
        app,
        "rig_status",
        rig_line(&snapshot.rig),
        false,
        None::<&str>,
    )?;

    let wsjtx_toggle = MenuItem::with_id(
        app,
        MENU_TOGGLE_WSJTX,
        if snapshot.wsjtx_listening {
            "Stop WSJT-X Listener"
        } else {
            "Start WSJT-X Listener"
        },
        true,
        None::<&str>,
    )?;

    let js8call_toggle = MenuItem::with_id(
        app,
        MENU_TOGGLE_JS8CALL,
        if snapshot.js8call_listening {
            "Stop JS8Call Listener"
        } else {
            "Start JS8Call Listener"
        },
        true,
        None::<&str>,
    )?;

    let n1mm_toggle = MenuItem::with_id(
        app,
        MENU_TOGGLE_N1MM,
        if snapshot.n1mm_listening {
            "Stop N1MM+ Listener"
        } else {
            "Start N1MM+ Listener"
        },
        true,
        None::<&str>,
    )?;

    let sync_label = if snapshot.pending > 0 {
        format!("Sync Now ({} pending)", snapshot.pending)
    } else {
        "Sync Now".to_string()
    };
    let sync_now = MenuItem::with_id(app, MENU_SYNC_NOW, sync_label, true, None::<&str>)?;

    let quit_item = MenuItem::with_id(app, MENU_QUIT, "Quit", true, None::<&str>)?;

    let sep_a = PredefinedMenuItem::separator(app)?;
    let sep_b = PredefinedMenuItem::separator(app)?;
    let sep_c = PredefinedMenuItem::separator(app)?;
    let sep_d = PredefinedMenuItem::separator(app)?;

    let menu = Menu::with_items(
        app,
        &[
            &top_status,
            &sep_a,
            &open_item,
            &sep_b,
            &udp_status,
            &rig_status,
            &sep_c,
            &wsjtx_toggle,
            &js8call_toggle,
            &n1mm_toggle,
            &sync_now,
            &sep_d,
            &quit_item,
        ],
    )?;

    Ok((menu, tooltip, visual_state(snapshot)))
}

fn status_line(snapshot: &TraySnapshot) -> String {
    if !snapshot.logged_in {
        "RadioLedger - Disconnected".to_string()
    } else if snapshot.last_error.is_some() {
        "RadioLedger - Sync error".to_string()
    } else if snapshot.pending > 0 {
        format!("RadioLedger - {} QSOs pending", snapshot.pending)
    } else {
        "RadioLedger - Synced ✓".to_string()
    }
}

fn tooltip(snapshot: &TraySnapshot) -> String {
    if !snapshot.logged_in {
        "RadioLedger - Disconnected".to_string()
    } else if snapshot.last_error.is_some() {
        "RadioLedger - Sync error".to_string()
    } else if snapshot.pending > 0 {
        format!("RadioLedger - {} QSOs pending", snapshot.pending)
    } else {
        "RadioLedger - Synced".to_string()
    }
}

fn visual_state(snapshot: &TraySnapshot) -> TrayVisualState {
    if !snapshot.logged_in {
        TrayVisualState::Disconnected
    } else if snapshot.last_error.is_some() {
        TrayVisualState::Error
    } else if snapshot.pending > 0 {
        TrayVisualState::Pending
    } else {
        TrayVisualState::Idle
    }
}

fn icon_for_state(state: TrayVisualState) -> tauri::Result<Image<'static>> {
    let bytes = match state {
        TrayVisualState::Idle => ICON_IDLE,
        TrayVisualState::Pending => ICON_PENDING,
        TrayVisualState::Error => ICON_ERROR,
        TrayVisualState::Disconnected => ICON_DISCONNECTED,
    };

    Image::from_bytes(bytes).map(|img| img.to_owned())
}

fn dot(active: bool) -> &'static str {
    if active { "●" } else { "○" }
}

fn rig_line(rig: &RigStatus) -> String {
    if !rig.connected {
        return "Rig: Disconnected".to_string();
    }

    let mut line = String::from("Rig: ");

    if let Some(freq) = &rig.frequency_display {
        line.push_str(freq);
        line.push_str(" MHz");
    } else {
        line.push_str("Connected");
    }

    if let Some(mode) = &rig.mode {
        line.push_str(" [");
        line.push_str(mode);
        line.push(']');
    }

    line
}

fn handle_menu_event(app: &AppHandle, id: &str) {
    match id {
        MENU_OPEN => {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }
        MENU_TOGGLE_WSJTX => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                toggle_wsjtx_listener(&app).await;
            });
        }
        MENU_TOGGLE_JS8CALL => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                toggle_js8call_listener(&app).await;
            });
        }
        MENU_TOGGLE_N1MM => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                toggle_n1mm_listener(&app).await;
            });
        }
        MENU_SYNC_NOW => {
            let app = app.clone();
            tauri::async_runtime::spawn(async move {
                trigger_sync(&app).await;
            });
        }
        MENU_QUIT => {
            info!("Quit requested from tray menu");
            app.exit(0);
        }
        other => {
            error!("Unknown tray menu event: {other}");
        }
    }
}

async fn toggle_wsjtx_listener(app: &AppHandle) {
    use crate::udp;

    let state: tauri::State<'_, AppState> = app.state();
    let is_listening = state.udp.lock().await.is_wsjtx_listening();

    if is_listening {
        let _ = udp::stop_udp_listener(state, app.clone()).await;
        info!("WSJT-X listener stopped from tray");
    } else {
        let _ = udp::start_udp_listener(None, state, app.clone()).await;
        info!("WSJT-X listener started from tray");
    }
}

async fn toggle_js8call_listener(app: &AppHandle) {
    use crate::udp;

    let state: tauri::State<'_, AppState> = app.state();
    let is_listening = state.udp.lock().await.is_js8call_listening();

    if is_listening {
        let _ = udp::stop_js8call_listener(state, app.clone()).await;
        info!("JS8Call listener stopped from tray");
    } else {
        let _ = udp::start_js8call_listener(None, state, app.clone()).await;
        info!("JS8Call listener started from tray");
    }
}

async fn toggle_n1mm_listener(app: &AppHandle) {
    use crate::udp;

    let state: tauri::State<'_, AppState> = app.state();
    let is_listening = state.udp.lock().await.is_n1mm_listening();

    if is_listening {
        let _ = udp::stop_n1mm_listener(state, app.clone()).await;
        info!("N1MM+ listener stopped from tray");
    } else {
        let _ = udp::start_n1mm_listener(None, state, app.clone()).await;
        info!("N1MM+ listener started from tray");
    }
}

async fn trigger_sync(app: &AppHandle) {
    use crate::sync;

    let state: tauri::State<'_, AppState> = app.state();
    let _ = sync::sync_now(state, app.clone()).await;
}
