// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivation = `-- name: CreateActivation :one
INSERT INTO activations (
    user_id,
    logbook_id,
    program,
    reference,
    activation_date,
    station_location_id,
    notes,
    status
)
VALUES (
    $1,
    $2,
    $3,
    UPPER($4::text),
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    uuid,
    user_id,
    logbook_id,
    program,
    reference,
    activation_date,
    station_location_id,
    notes,
    status,
    qso_count,
    unique_callsigns,
    created_at,
    updated_at
`

type CreateActivationParams struct {
	UserID            int64       `json:"user_id"`
	LogbookID         int64       `json:"logbook_id"`
	Program           string      `json:"program"`
	Reference         string      `json:"reference"`
	ActivationDate    pgtype.Date `json:"activation_date"`
	StationLocationID *int64      `json:"station_location_id"`
	Notes             *string     `json:"notes"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateActivation(ctx context.Context, arg CreateActivationParams) (Activation, error) {
	row := q.db.QueryRow(ctx, createActivation,
		arg.UserID,
		arg.LogbookID,
		arg.Program,
		arg.Reference,
		arg.ActivationDate,
		arg.StationLocationID,
		arg.Notes,
		arg.Status,
	)
	var i Activation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.Program,
		&i.Reference,
		&i.ActivationDate,
		&i.StationLocationID,
		&i.Notes,
		&i.Status,
		&i.QsoCount,
		&i.UniqueCallsigns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivationByUUIDAndProgram = `-- name: GetActivationByUUIDAndProgram :one
SELECT
    a.id,
    a.uuid,
    a.user_id,
    a.logbook_id,
    l.uuid AS logbook_uuid,
    a.program,
    a.reference,
    a.activation_date,
    a.station_location_id,
    sl.uuid AS station_location_uuid,
    a.notes,
    a.status,
    a.qso_count,
    a.unique_callsigns,
    a.created_at,
    a.updated_at
FROM activations a
JOIN logbooks l ON l.id = a.logbook_id
LEFT JOIN station_locations sl ON sl.id = a.station_location_id
WHERE a.uuid = $1
  AND a.program = $2
`

type GetActivationByUUIDAndProgramParams struct {
	ActivationUuid uuid.UUID `json:"activation_uuid"`
	Program        string    `json:"program"`
}

type GetActivationByUUIDAndProgramRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	LogbookUuid         uuid.UUID          `json:"logbook_uuid"`
	Program             string             `json:"program"`
	Reference           string             `json:"reference"`
	ActivationDate      pgtype.Date        `json:"activation_date"`
	StationLocationID   *int64             `json:"station_location_id"`
	StationLocationUuid pgtype.UUID        `json:"station_location_uuid"`
	Notes               *string            `json:"notes"`
	Status              string             `json:"status"`
	QsoCount            int32              `json:"qso_count"`
	UniqueCallsigns     int32              `json:"unique_callsigns"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActivationByUUIDAndProgram(ctx context.Context, arg GetActivationByUUIDAndProgramParams) (GetActivationByUUIDAndProgramRow, error) {
	row := q.db.QueryRow(ctx, getActivationByUUIDAndProgram, arg.ActivationUuid, arg.Program)
	var i GetActivationByUUIDAndProgramRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.LogbookUuid,
		&i.Program,
		&i.Reference,
		&i.ActivationDate,
		&i.StationLocationID,
		&i.StationLocationUuid,
		&i.Notes,
		&i.Status,
		&i.QsoCount,
		&i.UniqueCallsigns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivationStatusByUUIDAndProgram = `-- name: GetActivationStatusByUUIDAndProgram :one
WITH act AS (
    SELECT
        a.id,
        a.uuid,
        a.logbook_id,
        a.program,
        a.reference,
        a.activation_date,
        a.status,
        l.callsign AS logbook_callsign,
        sl.callsign AS station_location_callsign,
        sl.grid_square AS station_location_grid_square
    FROM activations a
    JOIN logbooks l ON l.id = a.logbook_id
    LEFT JOIN station_locations sl ON sl.id = a.station_location_id
    WHERE a.uuid = $1
      AND a.program = $2
)
SELECT
    act.id,
    act.uuid,
    act.program,
    act.reference,
    act.activation_date,
    act.status,
    COALESCE(stats.qso_count, 0)::bigint AS qso_count,
    COALESCE(stats.unique_callsigns, 0)::bigint AS unique_callsigns,
    COALESCE(stats.missing_station_callsign, 0)::bigint AS missing_station_callsign,
    COALESCE(stats.missing_my_gridsquare, 0)::bigint AS missing_my_gridsquare,
    COALESCE(stats.s2s_count, 0)::bigint AS s2s_count
FROM act
LEFT JOIN LATERAL (
    SELECT
        COUNT(*)::bigint AS qso_count,
        COUNT(DISTINCT UPPER(BTRIM(q.callsign)))::bigint AS unique_callsigns,
        COUNT(*) FILTER (
            WHERE NULLIF(BTRIM(COALESCE(q.station_callsign, act.logbook_callsign, act.station_location_callsign)), '') IS NULL
        )::bigint AS missing_station_callsign,
        COUNT(*) FILTER (
            WHERE NULLIF(BTRIM(COALESCE(q.my_gridsquare, act.station_location_grid_square)), '') IS NULL
        )::bigint AS missing_my_gridsquare,
        COUNT(*) FILTER (
            WHERE NULLIF(BTRIM(q.sota_ref), '') IS NOT NULL
        )::bigint AS s2s_count
    FROM qsos q
    WHERE q.deleted_at IS NULL
      AND q.logbook_id = act.logbook_id
      AND (
          q.activation_id = act.id
          OR (
              act.program = 'POTA'
              AND (q.datetime_on AT TIME ZONE 'UTC')::date = act.activation_date
              AND EXISTS (
                  SELECT 1
                  FROM unnest(COALESCE(q.my_pota_refs, ARRAY[]::text[])) AS ref
                  WHERE UPPER(BTRIM(ref)) = UPPER(BTRIM(act.reference))
              )
          )
          OR (
              act.program = 'SOTA'
              AND (q.datetime_on AT TIME ZONE 'UTC')::date = act.activation_date
              AND UPPER(BTRIM(COALESCE(q.my_sota_ref, ''))) = UPPER(BTRIM(act.reference))
          )
      )
) stats ON TRUE
`

type GetActivationStatusByUUIDAndProgramParams struct {
	ActivationUuid uuid.UUID `json:"activation_uuid"`
	Program        string    `json:"program"`
}

type GetActivationStatusByUUIDAndProgramRow struct {
	ID                     int64       `json:"id"`
	Uuid                   uuid.UUID   `json:"uuid"`
	Program                string      `json:"program"`
	Reference              string      `json:"reference"`
	ActivationDate         pgtype.Date `json:"activation_date"`
	Status                 string      `json:"status"`
	QsoCount               int64       `json:"qso_count"`
	UniqueCallsigns        int64       `json:"unique_callsigns"`
	MissingStationCallsign int64       `json:"missing_station_callsign"`
	MissingMyGridsquare    int64       `json:"missing_my_gridsquare"`
	S2sCount               int64       `json:"s2s_count"`
}

func (q *Queries) GetActivationStatusByUUIDAndProgram(ctx context.Context, arg GetActivationStatusByUUIDAndProgramParams) (GetActivationStatusByUUIDAndProgramRow, error) {
	row := q.db.QueryRow(ctx, getActivationStatusByUUIDAndProgram, arg.ActivationUuid, arg.Program)
	var i GetActivationStatusByUUIDAndProgramRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Program,
		&i.Reference,
		&i.ActivationDate,
		&i.Status,
		&i.QsoCount,
		&i.UniqueCallsigns,
		&i.MissingStationCallsign,
		&i.MissingMyGridsquare,
		&i.S2sCount,
	)
	return i, err
}

const getPOTAAwardSummary = `-- name: GetPOTAAwardSummary :one
WITH activation_stats AS (
    SELECT
        a.id,
        UPPER(BTRIM(a.reference)) AS reference,
        COUNT(DISTINCT UPPER(BTRIM(q.callsign)))::bigint AS unique_callsigns
    FROM activations a
    LEFT JOIN qsos q ON q.deleted_at IS NULL
      AND q.logbook_id = a.logbook_id
      AND (
          q.activation_id = a.id
          OR (
              (q.datetime_on AT TIME ZONE 'UTC')::date = a.activation_date
              AND EXISTS (
                  SELECT 1
                  FROM unnest(COALESCE(q.my_pota_refs, ARRAY[]::text[])) AS ref
                  WHERE UPPER(BTRIM(ref)) = UPPER(BTRIM(a.reference))
              )
          )
      )
    WHERE a.program = 'POTA'
    GROUP BY a.id, UPPER(BTRIM(a.reference))
),
hunted_refs AS (
    SELECT DISTINCT UPPER(BTRIM(ref)) AS reference
    FROM qsos q
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(q.sig_info, ''), '\\s*,\\s*') AS ref
    WHERE q.deleted_at IS NULL
      AND UPPER(BTRIM(COALESCE(q.sig, ''))) = 'POTA'
      AND NULLIF(BTRIM(ref), '') IS NOT NULL
      AND UPPER(BTRIM(ref)) ~ '^[A-Z]{1,3}-[0-9]{1,5}$'
)
SELECT
    COUNT(DISTINCT activation_stats.reference)::bigint AS parks_activated,
    COUNT(*)::bigint AS activations_total,
    COUNT(*) FILTER (WHERE activation_stats.unique_callsigns >= 10)::bigint AS valid_activations,
    COALESCE((SELECT COUNT(*)::bigint FROM hunted_refs), 0)::bigint AS parks_hunted
FROM activation_stats
`

type GetPOTAAwardSummaryRow struct {
	ParksActivated   int64 `json:"parks_activated"`
	ActivationsTotal int64 `json:"activations_total"`
	ValidActivations int64 `json:"valid_activations"`
	ParksHunted      int64 `json:"parks_hunted"`
}

func (q *Queries) GetPOTAAwardSummary(ctx context.Context) (GetPOTAAwardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPOTAAwardSummary)
	var i GetPOTAAwardSummaryRow
	err := row.Scan(
		&i.ParksActivated,
		&i.ActivationsTotal,
		&i.ValidActivations,
		&i.ParksHunted,
	)
	return i, err
}

const listActivationQSOsByUUIDAndProgram = `-- name: ListActivationQSOsByUUIDAndProgram :many
WITH act AS (
    SELECT
        a.id,
        a.logbook_id,
        a.program,
        a.reference,
        a.activation_date,
        l.callsign AS logbook_callsign,
        sl.callsign AS station_location_callsign,
        sl.grid_square AS station_location_grid_square
    FROM activations a
    JOIN logbooks l ON l.id = a.logbook_id
    LEFT JOIN station_locations sl ON sl.id = a.station_location_id
    WHERE a.uuid = $1
      AND a.program = $2
)
SELECT
    q.id,
    q.uuid,
    q.callsign,
    q.band,
    q.mode,
    q.submode,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.frequency_hz,
    q.comment,
    q.notes,
    q.sota_ref,
    q.my_sota_ref,
    q.sig,
    q.sig_info,
    q.pota_refs,
    q.my_pota_refs,
    COALESCE(NULLIF(BTRIM(q.station_callsign), ''), NULLIF(BTRIM(act.logbook_callsign), ''), NULLIF(BTRIM(act.station_location_callsign), ''))::text AS station_callsign_export,
    COALESCE(NULLIF(BTRIM(q.my_gridsquare), ''), NULLIF(BTRIM(act.station_location_grid_square), ''))::text AS my_gridsquare_export
FROM qsos q
CROSS JOIN act
WHERE q.deleted_at IS NULL
  AND q.logbook_id = act.logbook_id
  AND (
      q.activation_id = act.id
      OR (
          act.program = 'POTA'
          AND (q.datetime_on AT TIME ZONE 'UTC')::date = act.activation_date
          AND EXISTS (
              SELECT 1
              FROM unnest(COALESCE(q.my_pota_refs, ARRAY[]::text[])) AS ref
              WHERE UPPER(BTRIM(ref)) = UPPER(BTRIM(act.reference))
          )
      )
      OR (
          act.program = 'SOTA'
          AND (q.datetime_on AT TIME ZONE 'UTC')::date = act.activation_date
          AND UPPER(BTRIM(COALESCE(q.my_sota_ref, ''))) = UPPER(BTRIM(act.reference))
      )
  )
ORDER BY q.datetime_on ASC, q.id ASC
`

type ListActivationQSOsByUUIDAndProgramParams struct {
	ActivationUuid uuid.UUID `json:"activation_uuid"`
	Program        string    `json:"program"`
}

type ListActivationQSOsByUUIDAndProgramRow struct {
	ID                    int64              `json:"id"`
	Uuid                  uuid.UUID          `json:"uuid"`
	Callsign              string             `json:"callsign"`
	Band                  string             `json:"band"`
	Mode                  string             `json:"mode"`
	Submode               *string            `json:"submode"`
	DatetimeOn            pgtype.Timestamptz `json:"datetime_on"`
	RstSent               *string            `json:"rst_sent"`
	RstRcvd               *string            `json:"rst_rcvd"`
	FrequencyHz           *int64             `json:"frequency_hz"`
	Comment               *string            `json:"comment"`
	Notes                 *string            `json:"notes"`
	SotaRef               *string            `json:"sota_ref"`
	MySotaRef             *string            `json:"my_sota_ref"`
	Sig                   *string            `json:"sig"`
	SigInfo               *string            `json:"sig_info"`
	PotaRefs              []string           `json:"pota_refs"`
	MyPotaRefs            []string           `json:"my_pota_refs"`
	StationCallsignExport string             `json:"station_callsign_export"`
	MyGridsquareExport    string             `json:"my_gridsquare_export"`
}

func (q *Queries) ListActivationQSOsByUUIDAndProgram(ctx context.Context, arg ListActivationQSOsByUUIDAndProgramParams) ([]ListActivationQSOsByUUIDAndProgramRow, error) {
	rows, err := q.db.Query(ctx, listActivationQSOsByUUIDAndProgram, arg.ActivationUuid, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivationQSOsByUUIDAndProgramRow{}
	for rows.Next() {
		var i ListActivationQSOsByUUIDAndProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.Submode,
			&i.DatetimeOn,
			&i.RstSent,
			&i.RstRcvd,
			&i.FrequencyHz,
			&i.Comment,
			&i.Notes,
			&i.SotaRef,
			&i.MySotaRef,
			&i.Sig,
			&i.SigInfo,
			&i.PotaRefs,
			&i.MyPotaRefs,
			&i.StationCallsignExport,
			&i.MyGridsquareExport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivationsByProgram = `-- name: ListActivationsByProgram :many
SELECT
    a.id,
    a.uuid,
    a.user_id,
    a.logbook_id,
    l.uuid AS logbook_uuid,
    a.program,
    a.reference,
    a.activation_date,
    a.station_location_id,
    sl.uuid AS station_location_uuid,
    a.notes,
    a.status,
    a.qso_count,
    a.unique_callsigns,
    a.created_at,
    a.updated_at
FROM activations a
JOIN logbooks l ON l.id = a.logbook_id
LEFT JOIN station_locations sl ON sl.id = a.station_location_id
WHERE a.user_id = $1
  AND a.program = $2
ORDER BY a.activation_date DESC, a.created_at DESC
`

type ListActivationsByProgramParams struct {
	UserID  int64  `json:"user_id"`
	Program string `json:"program"`
}

type ListActivationsByProgramRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	LogbookUuid         uuid.UUID          `json:"logbook_uuid"`
	Program             string             `json:"program"`
	Reference           string             `json:"reference"`
	ActivationDate      pgtype.Date        `json:"activation_date"`
	StationLocationID   *int64             `json:"station_location_id"`
	StationLocationUuid pgtype.UUID        `json:"station_location_uuid"`
	Notes               *string            `json:"notes"`
	Status              string             `json:"status"`
	QsoCount            int32              `json:"qso_count"`
	UniqueCallsigns     int32              `json:"unique_callsigns"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActivationsByProgram(ctx context.Context, arg ListActivationsByProgramParams) ([]ListActivationsByProgramRow, error) {
	rows, err := q.db.Query(ctx, listActivationsByProgram, arg.UserID, arg.Program)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivationsByProgramRow{}
	for rows.Next() {
		var i ListActivationsByProgramRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.LogbookID,
			&i.LogbookUuid,
			&i.Program,
			&i.Reference,
			&i.ActivationDate,
			&i.StationLocationID,
			&i.StationLocationUuid,
			&i.Notes,
			&i.Status,
			&i.QsoCount,
			&i.UniqueCallsigns,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivationByUUIDAndProgram = `-- name: UpdateActivationByUUIDAndProgram :one
UPDATE activations a
SET
    reference = UPPER($1::text),
    activation_date = $2,
    station_location_id = $3,
    notes = $4,
    status = $5,
    updated_at = NOW()
WHERE a.uuid = $6
  AND a.program = $7
RETURNING
    a.id,
    a.uuid,
    a.user_id,
    a.logbook_id,
    a.program,
    a.reference,
    a.activation_date,
    a.station_location_id,
    a.notes,
    a.status,
    a.qso_count,
    a.unique_callsigns,
    a.created_at,
    a.updated_at
`

type UpdateActivationByUUIDAndProgramParams struct {
	Reference         string      `json:"reference"`
	ActivationDate    pgtype.Date `json:"activation_date"`
	StationLocationID *int64      `json:"station_location_id"`
	Notes             *string     `json:"notes"`
	Status            string      `json:"status"`
	ActivationUuid    uuid.UUID   `json:"activation_uuid"`
	Program           string      `json:"program"`
}

func (q *Queries) UpdateActivationByUUIDAndProgram(ctx context.Context, arg UpdateActivationByUUIDAndProgramParams) (Activation, error) {
	row := q.db.QueryRow(ctx, updateActivationByUUIDAndProgram,
		arg.Reference,
		arg.ActivationDate,
		arg.StationLocationID,
		arg.Notes,
		arg.Status,
		arg.ActivationUuid,
		arg.Program,
	)
	var i Activation
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.Program,
		&i.Reference,
		&i.ActivationDate,
		&i.StationLocationID,
		&i.Notes,
		&i.Status,
		&i.QsoCount,
		&i.UniqueCallsigns,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
