// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    user_id,
    name,
    key_hash,
    key_prefix,
    scopes,
    expires_at
)
VALUES (
    $1,  -- user_id
    $2,  -- name (user-visible label)
    $3,  -- key_hash (SHA-256 hex of full key)
    $4,  -- key_prefix (first 8 chars of plaintext key, for display)
    $5,  -- scopes (TEXT[])
    $6   -- expires_at (NULL = no expiry)
)
RETURNING id, uuid, user_id, name, key_hash, key_prefix, scopes, allowed_ips, expires_at, last_used_at, last_used_ip, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    int64              `json:"user_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries for api_keys table.
// API keys use a show-once pattern: the plaintext key is returned once at creation,
// only the SHA-256 hash is ever stored. Authentication hashes the incoming bearer
// token and compares against key_hash.
//
// Schema reference: docs/SCHEMA.md § api_keys
// Security spec: docs/ARCHITECTURE.md § "Token architecture" (API Keys row)
// Insert a new API key record. The plaintext key has already been generated and
// hashed by the application layer before this query is called.
// key_hash = hex(SHA-256(full_plaintext_key))
// key_prefix = first 8 chars of full_plaintext_key (for display identification)
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.AllowedIps,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, uuid, user_id, name, key_hash, key_prefix, scopes, allowed_ips, expires_at, last_used_at, last_used_ip, revoked_at, created_at
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

// Look up an API key by its SHA-256 hash for authentication.
// Called by the auth middleware when it receives a "Bearer rl_..." token.
// Returns the full row including user_id (needed to set RLS context).
// Filters out revoked and expired keys.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.AllowedIps,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT uuid, user_id, name, key_prefix, scopes, expires_at, last_used_at, revoked_at, created_at
FROM api_keys
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	Uuid       uuid.UUID          `json:"uuid"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// List API keys for a user — never returns key_hash (the secret hash).
// Returns prefix, name, scopes, timestamps for display.
// Revoked keys are excluded by default (revoked_at IS NULL).
func (q *Queries) ListAPIKeys(ctx context.Context, userID int64) ([]ListAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = NOW()
WHERE uuid = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

// Revoke an API key by UUID. Sets revoked_at to the current time.
// RLS ensures only the owning user can revoke their own keys.
func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.Uuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW(),
    last_used_ip = $2
WHERE id = $1
`

type UpdateAPIKeyLastUsedParams struct {
	ID         int64       `json:"id"`
	LastUsedIp *netip.Addr `json:"last_used_ip"`
}

// Record the last-used timestamp and source IP for an API key.
// Called after every successful API key authentication.
// Uses a direct id (internal PK) for efficiency — id is already known from GetAPIKeyByHash.
func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedIp)
	return err
}
