// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: awards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAwardProgressByType = `-- name: DeleteAwardProgressByType :exec
DELETE FROM award_progress
WHERE user_id = $1::bigint
  AND award_type = $2::text
`

type DeleteAwardProgressByTypeParams struct {
	UserID    int64  `json:"user_id"`
	AwardType string `json:"award_type"`
}

// Clears cached progress for a specific award type before full recalculation.
func (q *Queries) DeleteAwardProgressByType(ctx context.Context, arg DeleteAwardProgressByTypeParams) error {
	_, err := q.db.Exec(ctx, deleteAwardProgressByType, arg.UserID, arg.AwardType)
	return err
}

const getAwardProgressSummary = `-- name: GetAwardProgressSummary :many
SELECT
    award_type,
    COUNT(*) FILTER (WHERE worked = TRUE)::bigint              AS worked_count,
    COUNT(*) FILTER (WHERE confirmed = TRUE)::bigint           AS confirmed_count,
    MAX(last_qso_at)::timestamptz                              AS latest_qso_at,
    MAX(updated_at)::timestamptz                               AS cache_updated_at
FROM award_progress
GROUP BY award_type
ORDER BY award_type ASC
`

type GetAwardProgressSummaryRow struct {
	AwardType      string             `json:"award_type"`
	WorkedCount    int64              `json:"worked_count"`
	ConfirmedCount int64              `json:"confirmed_count"`
	LatestQsoAt    pgtype.Timestamptz `json:"latest_qso_at"`
	CacheUpdatedAt pgtype.Timestamptz `json:"cache_updated_at"`
}

// Unified summary of all award types for a user (for GET /v1/awards).
// Returns one row per award_type with aggregate counts.
func (q *Queries) GetAwardProgressSummary(ctx context.Context) ([]GetAwardProgressSummaryRow, error) {
	rows, err := q.db.Query(ctx, getAwardProgressSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAwardProgressSummaryRow{}
	for rows.Next() {
		var i GetAwardProgressSummaryRow
		if err := rows.Scan(
			&i.AwardType,
			&i.WorkedCount,
			&i.ConfirmedCount,
			&i.LatestQsoAt,
			&i.CacheUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDXCCSummary = `-- name: GetDXCCSummary :one
WITH qso_entities AS (
    SELECT
        COALESCE(q.dxcc, d_match.entity_id)::int AS entity_id,
        q.lotw_qsl_rcvd,
        q.qsl_rcvd,
        q.eqsl_qsl_rcvd
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN LATERAL (
        SELECT d.entity_id
        FROM dxcc_entities d
        WHERE NULLIF(BTRIM(q.country), '') IS NOT NULL
          AND (
              UPPER(BTRIM(d.name)) = UPPER(BTRIM(q.country))
              OR (
                  d.lotw_entity_name IS NOT NULL
                  AND UPPER(BTRIM(d.lotw_entity_name)) = UPPER(BTRIM(q.country))
              )
          )
        ORDER BY d.entity_id
        LIMIT 1
    ) d_match ON TRUE
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
)
SELECT
    COUNT(DISTINCT entity_id) FILTER (WHERE entity_id IS NOT NULL)::bigint AS worked,
    COUNT(DISTINCT entity_id) FILTER (
        WHERE entity_id IS NOT NULL
          AND (
              lotw_qsl_rcvd = 'Y'
              OR qsl_rcvd = 'Y'
              OR eqsl_qsl_rcvd = 'Y'
          )
    )::bigint AS confirmed
FROM qso_entities
`

type GetDXCCSummaryRow struct {
	Worked    int64 `json:"worked"`
	Confirmed int64 `json:"confirmed"`
}

func (q *Queries) GetDXCCSummary(ctx context.Context) (GetDXCCSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDXCCSummary)
	var i GetDXCCSummaryRow
	err := row.Scan(&i.Worked, &i.Confirmed)
	return i, err
}

const getDXCCTotalEntities = `-- name: GetDXCCTotalEntities :one
SELECT COUNT(*)::bigint AS total_entities
FROM dxcc_entities
`

func (q *Queries) GetDXCCTotalEntities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDXCCTotalEntities)
	var total_entities int64
	err := row.Scan(&total_entities)
	return total_entities, err
}

const listActivatedPOTAParks = `-- name: ListActivatedPOTAParks :many
SELECT
    UPPER(BTRIM(ref))::text                 AS park_ref,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
CROSS JOIN LATERAL unnest(COALESCE(q.my_pota_refs, ARRAY[]::text[])) AS ref
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND NULLIF(BTRIM(ref), '') IS NOT NULL
  AND UPPER(BTRIM(ref)) ~ '^[A-Z]{1,3}-[0-9]{1,5}$'
GROUP BY UPPER(BTRIM(ref))
ORDER BY park_ref ASC
`

type ListActivatedPOTAParksRow struct {
	ParkRef  string             `json:"park_ref"`
	QsoCount int64              `json:"qso_count"`
	FirstQso pgtype.Timestamptz `json:"first_qso"`
}

// POTA activator: parks activated from the operator-side MY_POTA_REF ADIF field.
func (q *Queries) ListActivatedPOTAParks(ctx context.Context) ([]ListActivatedPOTAParksRow, error) {
	rows, err := q.db.Query(ctx, listActivatedPOTAParks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivatedPOTAParksRow{}
	for rows.Next() {
		var i ListActivatedPOTAParksRow
		if err := rows.Scan(&i.ParkRef, &i.QsoCount, &i.FirstQso); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivatedSOTASummits = `-- name: ListActivatedSOTASummits :many
SELECT
    UPPER(BTRIM(q.my_sota_ref))::text       AS summit_ref,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND NULLIF(BTRIM(q.my_sota_ref), '') IS NOT NULL
GROUP BY UPPER(BTRIM(q.my_sota_ref))
ORDER BY summit_ref ASC
`

type ListActivatedSOTASummitsRow struct {
	SummitRef string             `json:"summit_ref"`
	QsoCount  int64              `json:"qso_count"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
}

// SOTA activator: summits activated (my_sota_ref from activator QSOs).
func (q *Queries) ListActivatedSOTASummits(ctx context.Context) ([]ListActivatedSOTASummitsRow, error) {
	rows, err := q.db.Query(ctx, listActivatedSOTASummits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivatedSOTASummitsRow{}
	for rows.Next() {
		var i ListActivatedSOTASummitsRow
		if err := rows.Scan(&i.SummitRef, &i.QsoCount, &i.FirstQso); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAwardProgressByType = `-- name: ListAwardProgressByType :many
SELECT
    id,
    award_type,
    entity_key,
    band,
    mode,
    worked,
    confirmed,
    qso_count,
    last_qso_at,
    updated_at
FROM award_progress
WHERE award_type = $1::text
ORDER BY entity_key ASC, band ASC NULLS LAST, mode ASC NULLS LAST
`

type ListAwardProgressByTypeRow struct {
	ID        int64              `json:"id"`
	AwardType string             `json:"award_type"`
	EntityKey string             `json:"entity_key"`
	Band      *string            `json:"band"`
	Mode      *string            `json:"mode"`
	Worked    bool               `json:"worked"`
	Confirmed bool               `json:"confirmed"`
	QsoCount  int64              `json:"qso_count"`
	LastQsoAt pgtype.Timestamptz `json:"last_qso_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Detailed progress rows for a specific award type (for GET /v1/awards/:type).
func (q *Queries) ListAwardProgressByType(ctx context.Context, awardType string) ([]ListAwardProgressByTypeRow, error) {
	rows, err := q.db.Query(ctx, listAwardProgressByType, awardType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAwardProgressByTypeRow{}
	for rows.Next() {
		var i ListAwardProgressByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.AwardType,
			&i.EntityKey,
			&i.Band,
			&i.Mode,
			&i.Worked,
			&i.Confirmed,
			&i.QsoCount,
			&i.LastQsoAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDXCCByBand = `-- name: ListDXCCByBand :many
WITH qso_entities AS (
    SELECT
        q.band,
        COALESCE(q.dxcc, d_match.entity_id)::int AS entity_id,
        q.lotw_qsl_rcvd,
        q.qsl_rcvd,
        q.eqsl_qsl_rcvd
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN LATERAL (
        SELECT d.entity_id
        FROM dxcc_entities d
        WHERE NULLIF(BTRIM(q.country), '') IS NOT NULL
          AND (
              UPPER(BTRIM(d.name)) = UPPER(BTRIM(q.country))
              OR (
                  d.lotw_entity_name IS NOT NULL
                  AND UPPER(BTRIM(d.lotw_entity_name)) = UPPER(BTRIM(q.country))
              )
          )
        ORDER BY d.entity_id
        LIMIT 1
    ) d_match ON TRUE
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
      AND NULLIF(BTRIM(q.band), '') IS NOT NULL
)
SELECT
    band,
    COUNT(DISTINCT entity_id) FILTER (WHERE entity_id IS NOT NULL)::bigint AS worked,
    COUNT(DISTINCT entity_id) FILTER (
        WHERE entity_id IS NOT NULL
          AND (
              lotw_qsl_rcvd = 'Y'
              OR qsl_rcvd = 'Y'
              OR eqsl_qsl_rcvd = 'Y'
          )
    )::bigint AS confirmed
FROM qso_entities
GROUP BY band
ORDER BY band ASC
`

type ListDXCCByBandRow struct {
	Band      string `json:"band"`
	Worked    int64  `json:"worked"`
	Confirmed int64  `json:"confirmed"`
}

func (q *Queries) ListDXCCByBand(ctx context.Context) ([]ListDXCCByBandRow, error) {
	rows, err := q.db.Query(ctx, listDXCCByBand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDXCCByBandRow{}
	for rows.Next() {
		var i ListDXCCByBandRow
		if err := rows.Scan(&i.Band, &i.Worked, &i.Confirmed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDXCCEntitiesProgress = `-- name: ListDXCCEntitiesProgress :many
WITH qso_entities AS (
    SELECT
        q.band,
        q.datetime_on,
        COALESCE(q.dxcc, d_match.entity_id)::int AS entity_id,
        q.lotw_qsl_rcvd,
        q.qsl_rcvd,
        q.eqsl_qsl_rcvd
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN LATERAL (
        SELECT d.entity_id
        FROM dxcc_entities d
        WHERE NULLIF(BTRIM(q.country), '') IS NOT NULL
          AND (
              UPPER(BTRIM(d.name)) = UPPER(BTRIM(q.country))
              OR (
                  d.lotw_entity_name IS NOT NULL
                  AND UPPER(BTRIM(d.lotw_entity_name)) = UPPER(BTRIM(q.country))
              )
          )
        ORDER BY d.entity_id
        LIMIT 1
    ) d_match ON TRUE
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
),
entity_work AS (
    SELECT
        entity_id,
        TRUE AS worked,
        BOOL_OR(lotw_qsl_rcvd = 'Y' OR qsl_rcvd = 'Y' OR eqsl_qsl_rcvd = 'Y') AS confirmed,
        ARRAY_AGG(DISTINCT band ORDER BY band) FILTER (WHERE NULLIF(BTRIM(band), '') IS NOT NULL) AS bands,
        MIN(datetime_on)::timestamptz AS first_qso,
        COUNT(*)::bigint AS qso_count
    FROM qso_entities
    WHERE entity_id IS NOT NULL
    GROUP BY entity_id
)
SELECT
    d.entity_id,
    d.name,
    d.prefix,
    d.continent,
    COALESCE(w.worked, FALSE) AS worked,
    COALESCE(w.confirmed, FALSE) AS confirmed,
    COALESCE(w.bands, ARRAY[]::text[])::text[] AS bands,
    w.first_qso,
    COALESCE(w.qso_count, 0)::bigint AS qso_count
FROM dxcc_entities d
LEFT JOIN entity_work w ON w.entity_id = d.entity_id
ORDER BY d.name ASC
`

type ListDXCCEntitiesProgressRow struct {
	EntityID  int32              `json:"entity_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Continent string             `json:"continent"`
	Worked    bool               `json:"worked"`
	Confirmed bool               `json:"confirmed"`
	Bands     []string           `json:"bands"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
	QsoCount  int64              `json:"qso_count"`
}

func (q *Queries) ListDXCCEntitiesProgress(ctx context.Context) ([]ListDXCCEntitiesProgressRow, error) {
	rows, err := q.db.Query(ctx, listDXCCEntitiesProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDXCCEntitiesProgressRow{}
	for rows.Next() {
		var i ListDXCCEntitiesProgressRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Name,
			&i.Prefix,
			&i.Continent,
			&i.Worked,
			&i.Confirmed,
			&i.Bands,
			&i.FirstQso,
			&i.QsoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDXCCEntityQSODetails = `-- name: ListDXCCEntityQSODetails :many
WITH qso_entities AS (
    SELECT
        q.uuid,
        q.callsign,
        q.band,
        q.mode,
        q.datetime_on,
        COALESCE(q.dxcc, d_match.entity_id)::int AS entity_id
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN LATERAL (
        SELECT d.entity_id
        FROM dxcc_entities d
        WHERE NULLIF(BTRIM(q.country), '') IS NOT NULL
          AND (
              UPPER(BTRIM(d.name)) = UPPER(BTRIM(q.country))
              OR (
                  d.lotw_entity_name IS NOT NULL
                  AND UPPER(BTRIM(d.lotw_entity_name)) = UPPER(BTRIM(q.country))
              )
          )
        ORDER BY d.entity_id
        LIMIT 1
    ) d_match ON TRUE
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
)
SELECT
    entity_id,
    uuid,
    callsign,
    band,
    mode,
    datetime_on
FROM qso_entities
WHERE entity_id IS NOT NULL
ORDER BY entity_id ASC, datetime_on DESC
`

type ListDXCCEntityQSODetailsRow struct {
	EntityID   int32              `json:"entity_id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Callsign   string             `json:"callsign"`
	Band       string             `json:"band"`
	Mode       string             `json:"mode"`
	DatetimeOn pgtype.Timestamptz `json:"datetime_on"`
}

func (q *Queries) ListDXCCEntityQSODetails(ctx context.Context) ([]ListDXCCEntityQSODetailsRow, error) {
	rows, err := q.db.Query(ctx, listDXCCEntityQSODetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDXCCEntityQSODetailsRow{}
	for rows.Next() {
		var i ListDXCCEntityQSODetailsRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Uuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.DatetimeOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHuntedPOTAParks = `-- name: ListHuntedPOTAParks :many
SELECT
    UPPER(BTRIM(ref))::text                 AS park_ref,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso,
    BOOL_OR(
        q.lotw_qsl_rcvd = 'Y'
        OR q.qsl_rcvd = 'Y'
        OR q.eqsl_qsl_rcvd = 'Y'
    )                                       AS confirmed
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
CROSS JOIN LATERAL regexp_split_to_table(COALESCE(q.sig_info, ''), '\s*,\s*') AS ref
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND UPPER(BTRIM(COALESCE(q.sig, ''))) = 'POTA'
  AND NULLIF(BTRIM(ref), '') IS NOT NULL
  AND UPPER(BTRIM(ref)) ~ '^[A-Z]{1,3}-[0-9]{1,5}$'
GROUP BY UPPER(BTRIM(ref))
ORDER BY park_ref ASC
`

type ListHuntedPOTAParksRow struct {
	ParkRef   string             `json:"park_ref"`
	QsoCount  int64              `json:"qso_count"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
	Confirmed bool               `json:"confirmed"`
}

// POTA hunter: parks worked (sig=POTA, sig_info has park reference).
func (q *Queries) ListHuntedPOTAParks(ctx context.Context) ([]ListHuntedPOTAParksRow, error) {
	rows, err := q.db.Query(ctx, listHuntedPOTAParks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHuntedPOTAParksRow{}
	for rows.Next() {
		var i ListHuntedPOTAParksRow
		if err := rows.Scan(
			&i.ParkRef,
			&i.QsoCount,
			&i.FirstQso,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkedGridSquares = `-- name: ListWorkedGridSquares :many
SELECT
    UPPER(LEFT(BTRIM(q.gridsquare), 4))::text AS grid_square,
    COUNT(*)::bigint AS qso_count,
    MIN(q.datetime_on)::timestamptz AS first_qso,
    MAX(q.datetime_on)::timestamptz AS last_qso
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND q.gridsquare ~* '^[A-R]{2}[0-9]{2}'
GROUP BY UPPER(LEFT(BTRIM(q.gridsquare), 4))::text
ORDER BY qso_count DESC, grid_square ASC
`

type ListWorkedGridSquaresRow struct {
	GridSquare string             `json:"grid_square"`
	QsoCount   int64              `json:"qso_count"`
	FirstQso   pgtype.Timestamptz `json:"first_qso"`
	LastQso    pgtype.Timestamptz `json:"last_qso"`
}

func (q *Queries) ListWorkedGridSquares(ctx context.Context) ([]ListWorkedGridSquaresRow, error) {
	rows, err := q.db.Query(ctx, listWorkedGridSquares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkedGridSquaresRow{}
	for rows.Next() {
		var i ListWorkedGridSquaresRow
		if err := rows.Scan(
			&i.GridSquare,
			&i.QsoCount,
			&i.FirstQso,
			&i.LastQso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkedSOTASummits = `-- name: ListWorkedSOTASummits :many
SELECT
    UPPER(BTRIM(q.sota_ref))::text          AS summit_ref,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso,
    BOOL_OR(
        q.lotw_qsl_rcvd = 'Y'
        OR q.qsl_rcvd = 'Y'
        OR q.eqsl_qsl_rcvd = 'Y'
    )                                       AS confirmed
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND NULLIF(BTRIM(q.sota_ref), '') IS NOT NULL
GROUP BY UPPER(BTRIM(q.sota_ref))
ORDER BY summit_ref ASC
`

type ListWorkedSOTASummitsRow struct {
	SummitRef string             `json:"summit_ref"`
	QsoCount  int64              `json:"qso_count"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
	Confirmed bool               `json:"confirmed"`
}

// SOTA chaser: summits worked as chaser from sig/sig_info fields.
func (q *Queries) ListWorkedSOTASummits(ctx context.Context) ([]ListWorkedSOTASummitsRow, error) {
	rows, err := q.db.Query(ctx, listWorkedSOTASummits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkedSOTASummitsRow{}
	for rows.Next() {
		var i ListWorkedSOTASummitsRow
		if err := rows.Scan(
			&i.SummitRef,
			&i.QsoCount,
			&i.FirstQso,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkedStates = `-- name: ListWorkedStates :many
WITH state_rows AS (
    SELECT
        COALESCE(
            NULLIF(BTRIM(q.state), ''),
            NULLIF(BTRIM(cr.state_province), '')
        ) AS derived_state,
        q.datetime_on
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN callsign_records cr
        ON UPPER(BTRIM(q.callsign)) = UPPER(BTRIM(cr.callsign))
       AND cr.country = 'US'
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
      AND COALESCE(
          NULLIF(BTRIM(q.state), ''),
          NULLIF(BTRIM(cr.state_province), '')
      ) IS NOT NULL
)
SELECT
    UPPER(BTRIM(derived_state))::text AS state_value,
    COUNT(*)::bigint AS qso_count,
    MIN(datetime_on)::timestamptz AS first_qso
FROM state_rows
GROUP BY UPPER(BTRIM(derived_state))::text
ORDER BY state_value ASC
`

type ListWorkedStatesRow struct {
	StateValue string             `json:"state_value"`
	QsoCount   int64              `json:"qso_count"`
	FirstQso   pgtype.Timestamptz `json:"first_qso"`
}

func (q *Queries) ListWorkedStates(ctx context.Context) ([]ListWorkedStatesRow, error) {
	rows, err := q.db.Query(ctx, listWorkedStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkedStatesRow{}
	for rows.Next() {
		var i ListWorkedStatesRow
		if err := rows.Scan(&i.StateValue, &i.QsoCount, &i.FirstQso); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkedWPXPrefixes = `-- name: ListWorkedWPXPrefixes :many
SELECT
    q.callsign,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso,
    COALESCE(BOOL_OR(
        q.lotw_qsl_rcvd = 'Y'
        OR q.qsl_rcvd = 'Y'
        OR q.eqsl_qsl_rcvd = 'Y'
    ), false)                               AS confirmed
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND NULLIF(BTRIM(q.callsign), '') IS NOT NULL
GROUP BY q.callsign
ORDER BY q.callsign ASC
`

type ListWorkedWPXPrefixesRow struct {
	Callsign  string             `json:"callsign"`
	QsoCount  int64              `json:"qso_count"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
	Confirmed interface{}        `json:"confirmed"`
}

// WPX: raw callsigns for prefix extraction (done in Go).
func (q *Queries) ListWorkedWPXPrefixes(ctx context.Context) ([]ListWorkedWPXPrefixesRow, error) {
	rows, err := q.db.Query(ctx, listWorkedWPXPrefixes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkedWPXPrefixesRow{}
	for rows.Next() {
		var i ListWorkedWPXPrefixesRow
		if err := rows.Scan(
			&i.Callsign,
			&i.QsoCount,
			&i.FirstQso,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkedZones = `-- name: ListWorkedZones :many
SELECT
    q.cq_zone::int                          AS zone,
    COUNT(*)::bigint                        AS qso_count,
    MIN(q.datetime_on)::timestamptz         AS first_qso,
    COALESCE(BOOL_OR(
        q.lotw_qsl_rcvd = 'Y'
        OR q.qsl_rcvd = 'Y'
        OR q.eqsl_qsl_rcvd = 'Y'
    ), false)                               AS confirmed
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND q.cq_zone IS NOT NULL
  AND q.cq_zone BETWEEN 1 AND 40
GROUP BY q.cq_zone
ORDER BY q.cq_zone ASC
`

type ListWorkedZonesRow struct {
	Zone      int32              `json:"zone"`
	QsoCount  int64              `json:"qso_count"`
	FirstQso  pgtype.Timestamptz `json:"first_qso"`
	Confirmed interface{}        `json:"confirmed"`
}

// WAZ: CQ zones worked from QSO records.
func (q *Queries) ListWorkedZones(ctx context.Context) ([]ListWorkedZonesRow, error) {
	rows, err := q.db.Query(ctx, listWorkedZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkedZonesRow{}
	for rows.Next() {
		var i ListWorkedZonesRow
		if err := rows.Scan(
			&i.Zone,
			&i.QsoCount,
			&i.FirstQso,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserAwardsDirty = `-- name: MarkUserAwardsDirty :exec
UPDATE award_progress
SET dirty = TRUE, updated_at = NOW()
WHERE user_id = $1::bigint
`

// Called after QSO mutations to flag all cached award progress for recalculation.
func (q *Queries) MarkUserAwardsDirty(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markUserAwardsDirty, userID)
	return err
}

const upsertAwardProgress = `-- name: UpsertAwardProgress :exec
INSERT INTO award_progress (
    user_id,
    award_type,
    entity_key,
    band,
    mode,
    worked,
    confirmed,
    qso_count,
    last_qso_at,
    dirty,
    updated_at
)
VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::boolean,
    $7::boolean,
    $8::bigint,
    $9::timestamptz,
    FALSE,
    NOW()
)
ON CONFLICT ON CONSTRAINT uq_award_progress_nulls_not_distinct
DO UPDATE SET
    worked      = EXCLUDED.worked,
    confirmed   = EXCLUDED.confirmed,
    qso_count   = EXCLUDED.qso_count,
    last_qso_at = EXCLUDED.last_qso_at,
    dirty       = FALSE,
    updated_at  = NOW()
`

type UpsertAwardProgressParams struct {
	UserID    int64              `json:"user_id"`
	AwardType string             `json:"award_type"`
	EntityKey string             `json:"entity_key"`
	Band      *string            `json:"band"`
	Mode      *string            `json:"mode"`
	Worked    bool               `json:"worked"`
	Confirmed bool               `json:"confirmed"`
	QsoCount  int64              `json:"qso_count"`
	LastQsoAt pgtype.Timestamptz `json:"last_qso_at"`
}

// Upsert a single award_progress row. Used by AwardRefreshWorker.
func (q *Queries) UpsertAwardProgress(ctx context.Context, arg UpsertAwardProgressParams) error {
	_, err := q.db.Exec(ctx, upsertAwardProgress,
		arg.UserID,
		arg.AwardType,
		arg.EntityKey,
		arg.Band,
		arg.Mode,
		arg.Worked,
		arg.Confirmed,
		arg.QsoCount,
		arg.LastQsoAt,
	)
	return err
}
