// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: callsign_cache.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autocompleteCallsigns = `-- name: AutocompleteCallsigns :many
SELECT
    callsign,
    data->>'full_name' AS full_name,
    data->>'grid'      AS grid
FROM callsign_cache
WHERE callsign LIKE UPPER($1) || '%'
  AND expires_at > NOW()
ORDER BY callsign
LIMIT 10
`

type AutocompleteCallsignsRow struct {
	Callsign string      `json:"callsign"`
	FullName interface{} `json:"full_name"`
	Grid     interface{} `json:"grid"`
}

// Prefix search over cached callsigns for typeahead/autocomplete.
// Returns the top 10 matches by callsign for the given prefix.
// Only considers non-expired entries. Used by the QSO entry form.
func (q *Queries) AutocompleteCallsigns(ctx context.Context, prefix interface{}) ([]AutocompleteCallsignsRow, error) {
	rows, err := q.db.Query(ctx, autocompleteCallsigns, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutocompleteCallsignsRow{}
	for rows.Next() {
		var i AutocompleteCallsignsRow
		if err := rows.Scan(&i.Callsign, &i.FullName, &i.Grid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExpiredCallsignCache = `-- name: DeleteExpiredCallsignCache :exec
DELETE FROM callsign_cache
WHERE expires_at <= NOW()
`

// Removes all expired entries. Run periodically (e.g. daily background job).
func (q *Queries) DeleteExpiredCallsignCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCallsignCache)
	return err
}

const getCallsignCache = `-- name: GetCallsignCache :one
SELECT callsign, data, source, fetched_at, expires_at
FROM callsign_cache
WHERE callsign = UPPER($1)
  AND expires_at > NOW()
`

// Returns a cached callsign record if it exists and has not expired.
// Returns no rows if not found or expired.
func (q *Queries) GetCallsignCache(ctx context.Context, callsign interface{}) (CallsignCache, error) {
	row := q.db.QueryRow(ctx, getCallsignCache, callsign)
	var i CallsignCache
	err := row.Scan(
		&i.Callsign,
		&i.Data,
		&i.Source,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertCallsignCache = `-- name: UpsertCallsignCache :one

INSERT INTO callsign_cache (callsign, data, source, fetched_at, expires_at)
VALUES (
    UPPER($1),
    $2,
    $3,
    NOW(),
    $4
)
ON CONFLICT (callsign) DO UPDATE
    SET data       = EXCLUDED.data,
        source     = EXCLUDED.source,
        fetched_at = NOW(),
        expires_at = EXCLUDED.expires_at
RETURNING callsign, data, source, fetched_at, expires_at
`

type UpsertCallsignCacheParams struct {
	Callsign  interface{}        `json:"callsign"`
	Data      []byte             `json:"data"`
	Source    string             `json:"source"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries for the callsign_cache table.
//
// callsign_cache stores the results of QRZ/HamDB lookups so that we do not
// hammer external callbook APIs during ADIF imports or rapid QSO entry.
// A 100k-QSO import without this = 100k API calls; QRZ rate-limits aggressively.
//
// Schema reference: docs/SCHEMA.md § callsign_cache
// Cache TTL: 30 days (callsign data rarely changes; license class and grid are stable)
//
// This table is NOT tenant-scoped (no user_id, no RLS). All users share the same
// cache of public callbook data. The data is public information from QRZ/HamDB.
// Insert or update a callsign cache entry.
// On conflict (same callsign), overwrites with fresh data and resets expiry.
func (q *Queries) UpsertCallsignCache(ctx context.Context, arg UpsertCallsignCacheParams) (CallsignCache, error) {
	row := q.db.QueryRow(ctx, upsertCallsignCache,
		arg.Callsign,
		arg.Data,
		arg.Source,
		arg.ExpiresAt,
	)
	var i CallsignCache
	err := row.Scan(
		&i.Callsign,
		&i.Data,
		&i.Source,
		&i.FetchedAt,
		&i.ExpiresAt,
	)
	return i, err
}
