// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: callsigns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStationCallsign = `-- name: CreateStationCallsign :one

INSERT INTO station_callsigns (
    user_id,
    callsign,
    callsign_type,
    description,
    valid_from,
    valid_to,
    active
)
VALUES (
    $1,
    UPPER($2),
    $3,
    $4,
    $5,
    $6,
    TRUE
)
RETURNING
    id,
    uuid,
    user_id,
    callsign,
    callsign_type,
    description,
    valid_from,
    valid_to,
    active,
    created_at,
    updated_at
`

type CreateStationCallsignParams struct {
	UserID       int64       `json:"user_id"`
	Callsign     interface{} `json:"callsign"`
	CallsignType string      `json:"callsign_type"`
	Description  *string     `json:"description"`
	ValidFrom    pgtype.Date `json:"valid_from"`
	ValidTo      pgtype.Date `json:"valid_to"`
}

// ─────────────────────────────────────────────────────────────────────────────
// station_callsigns: station identity for logging (supports M:N operator model).
// ─────────────────────────────────────────────────────────────────────────────
// Creates a station callsign identity entry.
func (q *Queries) CreateStationCallsign(ctx context.Context, arg CreateStationCallsignParams) (StationCallsign, error) {
	row := q.db.QueryRow(ctx, createStationCallsign,
		arg.UserID,
		arg.Callsign,
		arg.CallsignType,
		arg.Description,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i StationCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.CallsignType,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserCallsign = `-- name: CreateUserCallsign :one


INSERT INTO user_callsigns (
    user_id,
    callsign,
    license_class,
    country,
    dxcc_entity,
    is_primary,
    valid_from,
    valid_to
)
VALUES (
    $1,
    UPPER($2),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    uuid,
    user_id,
    callsign,
    license_class,
    country,
    dxcc_entity,
    is_primary,
    valid_from,
    valid_to,
    created_at
`

type CreateUserCallsignParams struct {
	UserID       int64       `json:"user_id"`
	Callsign     interface{} `json:"callsign"`
	LicenseClass *string     `json:"license_class"`
	Country      *string     `json:"country"`
	DxccEntity   *int32      `json:"dxcc_entity"`
	IsPrimary    bool        `json:"is_primary"`
	ValidFrom    pgtype.Date `json:"valid_from"`
	ValidTo      pgtype.Date `json:"valid_to"`
}

// Queries for user_callsigns (personal callsign history) and station_callsigns
// (station identity, supporting M:N operator model) tables.
//
// Schema reference: docs/SCHEMA.md § user_callsigns, station_callsigns,
//
//	station_callsign_operators
//
// ─────────────────────────────────────────────────────────────────────────────
// user_callsigns: personal callsign history (one per user, supports upgrades,
// historical calls, and vanity changes).
// ─────────────────────────────────────────────────────────────────────────────
// Registers a new callsign for the authenticated user.
// Callsigns are stored uppercase per ADIF and ham radio convention.
func (q *Queries) CreateUserCallsign(ctx context.Context, arg CreateUserCallsignParams) (UserCallsign, error) {
	row := q.db.QueryRow(ctx, createUserCallsign,
		arg.UserID,
		arg.Callsign,
		arg.LicenseClass,
		arg.Country,
		arg.DxccEntity,
		arg.IsPrimary,
		arg.ValidFrom,
		arg.ValidTo,
	)
	var i UserCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.LicenseClass,
		&i.Country,
		&i.DxccEntity,
		&i.IsPrimary,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStationCallsign = `-- name: DeleteStationCallsign :exec
UPDATE station_callsigns
SET active = FALSE, updated_at = NOW()
WHERE uuid = $1
`

// Soft-deactivates a station callsign by clearing its active flag.
// Hard-delete is not safe because QSOs may reference station_callsign_id.
func (q *Queries) DeleteStationCallsign(ctx context.Context, callsignUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStationCallsign, callsignUuid)
	return err
}

const deleteUserCallsign = `-- name: DeleteUserCallsign :exec
DELETE FROM user_callsigns
WHERE uuid = $1
`

// Removes a user callsign. Hard delete is safe because callsigns have no
// downstream FK references from QSOs (those use the text callsign column).
func (q *Queries) DeleteUserCallsign(ctx context.Context, callsignUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserCallsign, callsignUuid)
	return err
}

const getStationCallsignByUUID = `-- name: GetStationCallsignByUUID :one
SELECT
    id,
    uuid,
    user_id,
    callsign,
    callsign_type,
    description,
    valid_from,
    valid_to,
    active,
    created_at,
    updated_at
FROM station_callsigns
WHERE uuid = $1
`

// Returns a single station callsign by UUID, scoped via RLS.
func (q *Queries) GetStationCallsignByUUID(ctx context.Context, callsignUuid uuid.UUID) (StationCallsign, error) {
	row := q.db.QueryRow(ctx, getStationCallsignByUUID, callsignUuid)
	var i StationCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.CallsignType,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCallsignByUUID = `-- name: GetUserCallsignByUUID :one
SELECT
    id,
    uuid,
    user_id,
    callsign,
    license_class,
    country,
    dxcc_entity,
    is_primary,
    valid_from,
    valid_to,
    created_at
FROM user_callsigns
WHERE uuid = $1
`

// Returns a single user callsign by UUID, scoped via RLS.
func (q *Queries) GetUserCallsignByUUID(ctx context.Context, callsignUuid uuid.UUID) (UserCallsign, error) {
	row := q.db.QueryRow(ctx, getUserCallsignByUUID, callsignUuid)
	var i UserCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.LicenseClass,
		&i.Country,
		&i.DxccEntity,
		&i.IsPrimary,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}

const listStationCallsigns = `-- name: ListStationCallsigns :many
SELECT
    id,
    uuid,
    user_id,
    callsign,
    callsign_type,
    description,
    valid_from,
    valid_to,
    active,
    created_at,
    updated_at
FROM station_callsigns
WHERE user_id = $1
ORDER BY active DESC, created_at DESC, id DESC
`

// Lists all station callsigns for the authenticated user, active first.
func (q *Queries) ListStationCallsigns(ctx context.Context, userID int64) ([]StationCallsign, error) {
	rows, err := q.db.Query(ctx, listStationCallsigns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StationCallsign{}
	for rows.Next() {
		var i StationCallsign
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Callsign,
			&i.CallsignType,
			&i.Description,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCallsigns = `-- name: ListUserCallsigns :many
SELECT
    id,
    uuid,
    user_id,
    callsign,
    license_class,
    country,
    dxcc_entity,
    is_primary,
    valid_from,
    valid_to,
    created_at
FROM user_callsigns
WHERE user_id = $1
ORDER BY is_primary DESC, created_at DESC, id DESC
`

// Lists all callsigns for the authenticated user, primary first then newest first.
func (q *Queries) ListUserCallsigns(ctx context.Context, userID int64) ([]UserCallsign, error) {
	rows, err := q.db.Query(ctx, listUserCallsigns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserCallsign{}
	for rows.Next() {
		var i UserCallsign
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Callsign,
			&i.LicenseClass,
			&i.Country,
			&i.DxccEntity,
			&i.IsPrimary,
			&i.ValidFrom,
			&i.ValidTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStationCallsign = `-- name: UpdateStationCallsign :one
UPDATE station_callsigns
SET
    callsign_type = $1,
    description   = $2,
    valid_from    = $3,
    valid_to      = $4,
    active        = $5,
    updated_at    = NOW()
WHERE uuid = $6
RETURNING
    id,
    uuid,
    user_id,
    callsign,
    callsign_type,
    description,
    valid_from,
    valid_to,
    active,
    created_at,
    updated_at
`

type UpdateStationCallsignParams struct {
	CallsignType string      `json:"callsign_type"`
	Description  *string     `json:"description"`
	ValidFrom    pgtype.Date `json:"valid_from"`
	ValidTo      pgtype.Date `json:"valid_to"`
	Active       bool        `json:"active"`
	CallsignUuid uuid.UUID   `json:"callsign_uuid"`
}

// Updates a station callsign's metadata.
func (q *Queries) UpdateStationCallsign(ctx context.Context, arg UpdateStationCallsignParams) (StationCallsign, error) {
	row := q.db.QueryRow(ctx, updateStationCallsign,
		arg.CallsignType,
		arg.Description,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Active,
		arg.CallsignUuid,
	)
	var i StationCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.CallsignType,
		&i.Description,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserCallsign = `-- name: UpdateUserCallsign :one
UPDATE user_callsigns
SET
    is_primary    = $1,
    license_class = $2,
    country       = $3,
    dxcc_entity   = $4,
    valid_from    = $5,
    valid_to      = $6
WHERE uuid = $7
RETURNING
    id,
    uuid,
    user_id,
    callsign,
    license_class,
    country,
    dxcc_entity,
    is_primary,
    valid_from,
    valid_to,
    created_at
`

type UpdateUserCallsignParams struct {
	IsPrimary    bool        `json:"is_primary"`
	LicenseClass *string     `json:"license_class"`
	Country      *string     `json:"country"`
	DxccEntity   *int32      `json:"dxcc_entity"`
	ValidFrom    pgtype.Date `json:"valid_from"`
	ValidTo      pgtype.Date `json:"valid_to"`
	CallsignUuid uuid.UUID   `json:"callsign_uuid"`
}

// Updates a user callsign's metadata (primary flag, active status, validity dates).
// Callsign text itself is immutable once created (create a new row for a new call).
func (q *Queries) UpdateUserCallsign(ctx context.Context, arg UpdateUserCallsignParams) (UserCallsign, error) {
	row := q.db.QueryRow(ctx, updateUserCallsign,
		arg.IsPrimary,
		arg.LicenseClass,
		arg.Country,
		arg.DxccEntity,
		arg.ValidFrom,
		arg.ValidTo,
		arg.CallsignUuid,
	)
	var i UserCallsign
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Callsign,
		&i.LicenseClass,
		&i.Country,
		&i.DxccEntity,
		&i.IsPrimary,
		&i.ValidFrom,
		&i.ValidTo,
		&i.CreatedAt,
	)
	return i, err
}
