// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkDupe = `-- name: CheckDupe :one
SELECT
    q.uuid                AS qso_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on,
    cqe.sent_serial,
    cqe.recv_exchange,
    cqe.is_dupe
FROM contest_sessions sess
JOIN qsos q
    ON q.contest_session_id = sess.id
   AND UPPER(q.callsign) = UPPER($1::text)
   AND q.band = $2
   AND q.deleted_at IS NULL
JOIN contest_qso_exchange cqe
    ON cqe.qso_id = q.id
   AND NOT cqe.is_dupe
WHERE sess.uuid = $3
ORDER BY q.datetime_on ASC
LIMIT 1
`

type CheckDupeParams struct {
	Callsign    string    `json:"callsign"`
	Band        string    `json:"band"`
	SessionUuid uuid.UUID `json:"session_uuid"`
}

type CheckDupeRow struct {
	QsoUuid      uuid.UUID          `json:"qso_uuid"`
	Callsign     string             `json:"callsign"`
	Band         string             `json:"band"`
	Mode         string             `json:"mode"`
	DatetimeOn   pgtype.Timestamptz `json:"datetime_on"`
	SentSerial   *int32             `json:"sent_serial"`
	RecvExchange *string            `json:"recv_exchange"`
	IsDupe       bool               `json:"is_dupe"`
}

// Returns the first non-dupe QSO for callsign+band in this contest session.
// Uses idx_qsos_contest_dupe for <10ms response.
func (q *Queries) CheckDupe(ctx context.Context, arg CheckDupeParams) (CheckDupeRow, error) {
	row := q.db.QueryRow(ctx, checkDupe, arg.Callsign, arg.Band, arg.SessionUuid)
	var i CheckDupeRow
	err := row.Scan(
		&i.QsoUuid,
		&i.Callsign,
		&i.Band,
		&i.Mode,
		&i.DatetimeOn,
		&i.SentSerial,
		&i.RecvExchange,
		&i.IsDupe,
	)
	return i, err
}

const createContestSession = `-- name: CreateContestSession :one
INSERT INTO contest_sessions (
    user_id,
    logbook_id,
    contest_id,
    station_callsign_id,
    name,
    starts_at,
    ends_at,
    category_operator,
    category_assisted,
    category_band,
    category_mode,
    category_power,
    category_station,
    category_time,
    category_transmitter,
    category_overlay,
    operators_line,
    club_name,
    location,
    soapbox,
    exchange_sent,
    exchange_template,
    status,
    cabrillo_version
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24
)
RETURNING
    id, uuid, user_id, logbook_id, contest_id, name,
    starts_at, ends_at, category_operator, category_assisted, category_band,
    category_mode, category_power, category_station, category_time,
    category_transmitter, category_overlay, operators_line, club_name,
    location, soapbox, exchange_sent, exchange_template,
    serial_counter, status, cabrillo_version, created_at, updated_at
`

type CreateContestSessionParams struct {
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	ContestID           int64              `json:"contest_id"`
	StationCallsignID   *int64             `json:"station_callsign_id"`
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ExchangeSent        *string            `json:"exchange_sent"`
	ExchangeTemplate    string             `json:"exchange_template"`
	Status              string             `json:"status"`
	CabrilloVersion     string             `json:"cabrillo_version"`
}

type CreateContestSessionRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	ContestID           int64              `json:"contest_id"`
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ExchangeSent        *string            `json:"exchange_sent"`
	ExchangeTemplate    string             `json:"exchange_template"`
	SerialCounter       int32              `json:"serial_counter"`
	Status              string             `json:"status"`
	CabrilloVersion     string             `json:"cabrillo_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContestSession(ctx context.Context, arg CreateContestSessionParams) (CreateContestSessionRow, error) {
	row := q.db.QueryRow(ctx, createContestSession,
		arg.UserID,
		arg.LogbookID,
		arg.ContestID,
		arg.StationCallsignID,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryOperator,
		arg.CategoryAssisted,
		arg.CategoryBand,
		arg.CategoryMode,
		arg.CategoryPower,
		arg.CategoryStation,
		arg.CategoryTime,
		arg.CategoryTransmitter,
		arg.CategoryOverlay,
		arg.OperatorsLine,
		arg.ClubName,
		arg.Location,
		arg.Soapbox,
		arg.ExchangeSent,
		arg.ExchangeTemplate,
		arg.Status,
		arg.CabrilloVersion,
	)
	var i CreateContestSessionRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.ContestID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryOperator,
		&i.CategoryAssisted,
		&i.CategoryBand,
		&i.CategoryMode,
		&i.CategoryPower,
		&i.CategoryStation,
		&i.CategoryTime,
		&i.CategoryTransmitter,
		&i.CategoryOverlay,
		&i.OperatorsLine,
		&i.ClubName,
		&i.Location,
		&i.Soapbox,
		&i.ExchangeSent,
		&i.ExchangeTemplate,
		&i.SerialCounter,
		&i.Status,
		&i.CabrilloVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestForExport = `-- name: GetContestForExport :one
SELECT
    cs.uuid,
    cs.name,
    c.cabrillo_name       AS contest_cabrillo_name,
    c.contest_code,
    sc.callsign           AS my_callsign,
    cs.category_operator,
    cs.category_assisted,
    cs.category_band,
    cs.category_mode,
    cs.category_power,
    cs.category_station,
    cs.category_time,
    cs.category_transmitter,
    cs.category_overlay,
    cs.operators_line,
    cs.club_name,
    cs.location,
    cs.soapbox,
    cs.claimed_score,
    cs.exchange_sent,
    cs.cabrillo_version,
    cs.starts_at,
    cs.ends_at
FROM contest_sessions cs
JOIN contests c ON c.id = cs.contest_id
LEFT JOIN station_callsigns sc ON sc.id = cs.station_callsign_id
WHERE cs.uuid = $1
`

type GetContestForExportRow struct {
	Uuid                uuid.UUID          `json:"uuid"`
	Name                string             `json:"name"`
	ContestCabrilloName string             `json:"contest_cabrillo_name"`
	ContestCode         string             `json:"contest_code"`
	MyCallsign          *string            `json:"my_callsign"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ClaimedScore        *int64             `json:"claimed_score"`
	ExchangeSent        *string            `json:"exchange_sent"`
	CabrilloVersion     string             `json:"cabrillo_version"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
}

// Fetch all header fields needed to generate a Cabrillo export.
func (q *Queries) GetContestForExport(ctx context.Context, sessionUuid uuid.UUID) (GetContestForExportRow, error) {
	row := q.db.QueryRow(ctx, getContestForExport, sessionUuid)
	var i GetContestForExportRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.ContestCabrilloName,
		&i.ContestCode,
		&i.MyCallsign,
		&i.CategoryOperator,
		&i.CategoryAssisted,
		&i.CategoryBand,
		&i.CategoryMode,
		&i.CategoryPower,
		&i.CategoryStation,
		&i.CategoryTime,
		&i.CategoryTransmitter,
		&i.CategoryOverlay,
		&i.OperatorsLine,
		&i.ClubName,
		&i.Location,
		&i.Soapbox,
		&i.ClaimedScore,
		&i.ExchangeSent,
		&i.CabrilloVersion,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getContestQSOsForExport = `-- name: GetContestQSOsForExport :many
SELECT
    q.uuid          AS qso_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.submode,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.frequency_hz,
    cqe.sent_serial,
    cqe.recv_serial,
    cqe.sent_exchange,
    cqe.recv_exchange,
    cqe.is_dupe,
    cqe.cabrillo_qso_line
FROM contest_sessions cs
JOIN qsos q
    ON q.contest_session_id = cs.id
   AND q.deleted_at IS NULL
JOIN contest_qso_exchange cqe ON cqe.qso_id = q.id
WHERE cs.uuid = $1
ORDER BY q.datetime_on ASC, q.id ASC
`

type GetContestQSOsForExportRow struct {
	QsoUuid         uuid.UUID          `json:"qso_uuid"`
	Callsign        string             `json:"callsign"`
	Band            string             `json:"band"`
	Mode            string             `json:"mode"`
	Submode         *string            `json:"submode"`
	DatetimeOn      pgtype.Timestamptz `json:"datetime_on"`
	RstSent         *string            `json:"rst_sent"`
	RstRcvd         *string            `json:"rst_rcvd"`
	FrequencyHz     *int64             `json:"frequency_hz"`
	SentSerial      *int32             `json:"sent_serial"`
	RecvSerial      *int32             `json:"recv_serial"`
	SentExchange    *string            `json:"sent_exchange"`
	RecvExchange    *string            `json:"recv_exchange"`
	IsDupe          bool               `json:"is_dupe"`
	CabrilloQsoLine *string            `json:"cabrillo_qso_line"`
}

// All QSOs for a contest session (including dupes), ordered by time.
func (q *Queries) GetContestQSOsForExport(ctx context.Context, sessionUuid uuid.UUID) ([]GetContestQSOsForExportRow, error) {
	rows, err := q.db.Query(ctx, getContestQSOsForExport, sessionUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContestQSOsForExportRow{}
	for rows.Next() {
		var i GetContestQSOsForExportRow
		if err := rows.Scan(
			&i.QsoUuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.Submode,
			&i.DatetimeOn,
			&i.RstSent,
			&i.RstRcvd,
			&i.FrequencyHz,
			&i.SentSerial,
			&i.RecvSerial,
			&i.SentExchange,
			&i.RecvExchange,
			&i.IsDupe,
			&i.CabrilloQsoLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContestSessionByUUID = `-- name: GetContestSessionByUUID :one
SELECT
    cs.id,
    cs.uuid,
    cs.user_id,
    cs.logbook_id,
    l.uuid AS logbook_uuid,
    cs.contest_id,
    c.contest_code,
    c.name AS contest_name,
    c.cabrillo_name,
    sc.callsign AS my_callsign,
    cs.name,
    cs.starts_at,
    cs.ends_at,
    cs.category_operator,
    cs.category_assisted,
    cs.category_band,
    cs.category_mode,
    cs.category_power,
    cs.category_station,
    cs.category_time,
    cs.category_transmitter,
    cs.category_overlay,
    cs.operators_line,
    cs.club_name,
    cs.location,
    cs.soapbox,
    cs.claimed_score,
    cs.exchange_sent,
    cs.exchange_template,
    cs.serial_counter,
    cs.status,
    cs.cabrillo_version,
    cs.created_at,
    cs.updated_at
FROM contest_sessions cs
JOIN logbooks l ON l.id = cs.logbook_id
JOIN contests c ON c.id = cs.contest_id
LEFT JOIN station_callsigns sc ON sc.id = cs.station_callsign_id
WHERE cs.uuid = $1
`

type GetContestSessionByUUIDRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	LogbookUuid         uuid.UUID          `json:"logbook_uuid"`
	ContestID           int64              `json:"contest_id"`
	ContestCode         string             `json:"contest_code"`
	ContestName         string             `json:"contest_name"`
	CabrilloName        string             `json:"cabrillo_name"`
	MyCallsign          *string            `json:"my_callsign"`
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ClaimedScore        *int64             `json:"claimed_score"`
	ExchangeSent        *string            `json:"exchange_sent"`
	ExchangeTemplate    string             `json:"exchange_template"`
	SerialCounter       int32              `json:"serial_counter"`
	Status              string             `json:"status"`
	CabrilloVersion     string             `json:"cabrillo_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContestSessionByUUID(ctx context.Context, sessionUuid uuid.UUID) (GetContestSessionByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getContestSessionByUUID, sessionUuid)
	var i GetContestSessionByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.LogbookUuid,
		&i.ContestID,
		&i.ContestCode,
		&i.ContestName,
		&i.CabrilloName,
		&i.MyCallsign,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryOperator,
		&i.CategoryAssisted,
		&i.CategoryBand,
		&i.CategoryMode,
		&i.CategoryPower,
		&i.CategoryStation,
		&i.CategoryTime,
		&i.CategoryTransmitter,
		&i.CategoryOverlay,
		&i.OperatorsLine,
		&i.ClubName,
		&i.Location,
		&i.Soapbox,
		&i.ClaimedScore,
		&i.ExchangeSent,
		&i.ExchangeTemplate,
		&i.SerialCounter,
		&i.Status,
		&i.CabrilloVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestStats = `-- name: GetContestStats :one
SELECT
    COALESCE(COUNT(q.id) FILTER (WHERE NOT cqe.is_dupe), 0)::bigint        AS total_qsos,
    COALESCE(COUNT(q.id) FILTER (WHERE cqe.is_dupe), 0)::bigint             AS dupe_qsos,
    COALESCE(COUNT(DISTINCT UPPER(q.callsign)) FILTER (WHERE NOT cqe.is_dupe), 0)::bigint AS unique_callsigns,
    COALESCE(COUNT(q.id) FILTER (WHERE NOT cqe.is_dupe AND q.datetime_on >= NOW() - INTERVAL '60 minutes'), 0)::bigint AS rate_last_60min,
    COALESCE(COUNT(q.id) FILTER (WHERE NOT cqe.is_dupe AND q.datetime_on >= NOW() - INTERVAL '10 minutes'), 0)::bigint AS rate_last_10min,
    COALESCE(COUNT(q.id) FILTER (WHERE NOT cqe.is_dupe AND q.datetime_on >= NOW() - INTERVAL '1 minute'), 0)::bigint  AS rate_last_1min,
    MIN(q.datetime_on)                                                       AS first_qso_at,
    MAX(q.datetime_on)                                                       AS last_qso_at,
    cs.serial_counter
FROM contest_sessions cs
LEFT JOIN qsos q
    ON q.contest_session_id = cs.id
   AND q.deleted_at IS NULL
LEFT JOIN contest_qso_exchange cqe ON cqe.qso_id = q.id
WHERE cs.uuid = $1
GROUP BY cs.serial_counter
`

type GetContestStatsRow struct {
	TotalQsos       int64       `json:"total_qsos"`
	DupeQsos        int64       `json:"dupe_qsos"`
	UniqueCallsigns int64       `json:"unique_callsigns"`
	RateLast60min   int64       `json:"rate_last_60min"`
	RateLast10min   int64       `json:"rate_last_10min"`
	RateLast1min    int64       `json:"rate_last_1min"`
	FirstQsoAt      interface{} `json:"first_qso_at"`
	LastQsoAt       interface{} `json:"last_qso_at"`
	SerialCounter   int32       `json:"serial_counter"`
}

// Live contest statistics for the session detail view.
func (q *Queries) GetContestStats(ctx context.Context, sessionUuid uuid.UUID) (GetContestStatsRow, error) {
	row := q.db.QueryRow(ctx, getContestStats, sessionUuid)
	var i GetContestStatsRow
	err := row.Scan(
		&i.TotalQsos,
		&i.DupeQsos,
		&i.UniqueCallsigns,
		&i.RateLast60min,
		&i.RateLast10min,
		&i.RateLast1min,
		&i.FirstQsoAt,
		&i.LastQsoAt,
		&i.SerialCounter,
	)
	return i, err
}

const incrementSerialCounter = `-- name: IncrementSerialCounter :one
UPDATE contest_sessions
SET
    serial_counter = serial_counter + 1,
    updated_at     = NOW()
WHERE uuid = $1
RETURNING serial_counter
`

// Atomically increment serial_counter and return the new value.
func (q *Queries) IncrementSerialCounter(ctx context.Context, sessionUuid uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementSerialCounter, sessionUuid)
	var serial_counter int32
	err := row.Scan(&serial_counter)
	return serial_counter, err
}

const insertContestQSO = `-- name: InsertContestQSO :one
INSERT INTO qsos (
    logbook_id,
    created_by_user_id,
    callsign,
    band,
    mode,
    datetime_on,
    rst_sent,
    rst_rcvd,
    frequency_hz,
    contest_session_id,
    contest_id
)
SELECT
    cs.logbook_id,
    $1::bigint,
    UPPER(BTRIM($2::text)),
    $3::text,
    $4::text,
    $5::timestamptz,
    $6::text,
    $7::text,
    $8::bigint,
    cs.id,
    c.contest_code
FROM contest_sessions cs
JOIN contests c ON c.id = cs.contest_id
WHERE cs.uuid = $9
RETURNING id, uuid, callsign, band, mode, datetime_on, rst_sent, rst_rcvd, frequency_hz, contest_session_id
`

type InsertContestQSOParams struct {
	CreatedByUserID int64              `json:"created_by_user_id"`
	Callsign        string             `json:"callsign"`
	Band            string             `json:"band"`
	Mode            string             `json:"mode"`
	DatetimeOn      pgtype.Timestamptz `json:"datetime_on"`
	RstSent         *string            `json:"rst_sent"`
	RstRcvd         *string            `json:"rst_rcvd"`
	FrequencyHz     *int64             `json:"frequency_hz"`
	SessionUuid     uuid.UUID          `json:"session_uuid"`
}

type InsertContestQSORow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	Callsign         string             `json:"callsign"`
	Band             string             `json:"band"`
	Mode             string             `json:"mode"`
	DatetimeOn       pgtype.Timestamptz `json:"datetime_on"`
	RstSent          *string            `json:"rst_sent"`
	RstRcvd          *string            `json:"rst_rcvd"`
	FrequencyHz      *int64             `json:"frequency_hz"`
	ContestSessionID *int64             `json:"contest_session_id"`
}

// Insert a QSO linked to a contest session.
func (q *Queries) InsertContestQSO(ctx context.Context, arg InsertContestQSOParams) (InsertContestQSORow, error) {
	row := q.db.QueryRow(ctx, insertContestQSO,
		arg.CreatedByUserID,
		arg.Callsign,
		arg.Band,
		arg.Mode,
		arg.DatetimeOn,
		arg.RstSent,
		arg.RstRcvd,
		arg.FrequencyHz,
		arg.SessionUuid,
	)
	var i InsertContestQSORow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Callsign,
		&i.Band,
		&i.Mode,
		&i.DatetimeOn,
		&i.RstSent,
		&i.RstRcvd,
		&i.FrequencyHz,
		&i.ContestSessionID,
	)
	return i, err
}

const insertContestQSOExchange = `-- name: InsertContestQSOExchange :one
INSERT INTO contest_qso_exchange (
    qso_id,
    contest_session_id,
    sent_serial,
    recv_serial,
    sent_exchange,
    recv_exchange,
    is_dupe
)
SELECT
    $1::bigint,
    cs.id,
    $2::integer,
    $3::integer,
    $4::text,
    $5::text,
    $6::boolean
FROM contest_sessions cs
WHERE cs.uuid = $7
RETURNING qso_id, contest_session_id, sent_serial, recv_serial, sent_exchange, recv_exchange, is_dupe, created_at
`

type InsertContestQSOExchangeParams struct {
	QsoID        int64     `json:"qso_id"`
	SentSerial   *int32    `json:"sent_serial"`
	RecvSerial   *int32    `json:"recv_serial"`
	SentExchange *string   `json:"sent_exchange"`
	RecvExchange *string   `json:"recv_exchange"`
	IsDupe       bool      `json:"is_dupe"`
	SessionUuid  uuid.UUID `json:"session_uuid"`
}

type InsertContestQSOExchangeRow struct {
	QsoID            int64              `json:"qso_id"`
	ContestSessionID int64              `json:"contest_session_id"`
	SentSerial       *int32             `json:"sent_serial"`
	RecvSerial       *int32             `json:"recv_serial"`
	SentExchange     *string            `json:"sent_exchange"`
	RecvExchange     *string            `json:"recv_exchange"`
	IsDupe           bool               `json:"is_dupe"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertContestQSOExchange(ctx context.Context, arg InsertContestQSOExchangeParams) (InsertContestQSOExchangeRow, error) {
	row := q.db.QueryRow(ctx, insertContestQSOExchange,
		arg.QsoID,
		arg.SentSerial,
		arg.RecvSerial,
		arg.SentExchange,
		arg.RecvExchange,
		arg.IsDupe,
		arg.SessionUuid,
	)
	var i InsertContestQSOExchangeRow
	err := row.Scan(
		&i.QsoID,
		&i.ContestSessionID,
		&i.SentSerial,
		&i.RecvSerial,
		&i.SentExchange,
		&i.RecvExchange,
		&i.IsDupe,
		&i.CreatedAt,
	)
	return i, err
}

const listContestSessions = `-- name: ListContestSessions :many
SELECT
    cs.id,
    cs.uuid,
    cs.logbook_id,
    l.uuid AS logbook_uuid,
    cs.contest_id,
    c.contest_code,
    c.name AS contest_name,
    sc.callsign AS my_callsign,
    cs.name,
    cs.starts_at,
    cs.ends_at,
    cs.category_operator,
    cs.category_band,
    cs.category_mode,
    cs.category_power,
    cs.exchange_template,
    cs.serial_counter,
    cs.status,
    cs.created_at
FROM contest_sessions cs
JOIN logbooks l ON l.id = cs.logbook_id
JOIN contests c ON c.id = cs.contest_id
LEFT JOIN station_callsigns sc ON sc.id = cs.station_callsign_id
WHERE cs.user_id = $1
ORDER BY cs.created_at DESC
`

type ListContestSessionsRow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	LogbookID        int64              `json:"logbook_id"`
	LogbookUuid      uuid.UUID          `json:"logbook_uuid"`
	ContestID        int64              `json:"contest_id"`
	ContestCode      string             `json:"contest_code"`
	ContestName      string             `json:"contest_name"`
	MyCallsign       *string            `json:"my_callsign"`
	Name             string             `json:"name"`
	StartsAt         pgtype.Timestamptz `json:"starts_at"`
	EndsAt           pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator string             `json:"category_operator"`
	CategoryBand     string             `json:"category_band"`
	CategoryMode     string             `json:"category_mode"`
	CategoryPower    string             `json:"category_power"`
	ExchangeTemplate string             `json:"exchange_template"`
	SerialCounter    int32              `json:"serial_counter"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListContestSessions(ctx context.Context, userID int64) ([]ListContestSessionsRow, error) {
	rows, err := q.db.Query(ctx, listContestSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestSessionsRow{}
	for rows.Next() {
		var i ListContestSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.LogbookID,
			&i.LogbookUuid,
			&i.ContestID,
			&i.ContestCode,
			&i.ContestName,
			&i.MyCallsign,
			&i.Name,
			&i.StartsAt,
			&i.EndsAt,
			&i.CategoryOperator,
			&i.CategoryBand,
			&i.CategoryMode,
			&i.CategoryPower,
			&i.ExchangeTemplate,
			&i.SerialCounter,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT id, contest_code, name, sponsor, cabrillo_name, exchange_schema, active
FROM contests
WHERE active = TRUE
ORDER BY name ASC
`

type ListContestsRow struct {
	ID             int64   `json:"id"`
	ContestCode    string  `json:"contest_code"`
	Name           string  `json:"name"`
	Sponsor        *string `json:"sponsor"`
	CabrilloName   string  `json:"cabrillo_name"`
	ExchangeSchema []byte  `json:"exchange_schema"`
	Active         bool    `json:"active"`
}

func (q *Queries) ListContests(ctx context.Context) ([]ListContestsRow, error) {
	rows, err := q.db.Query(ctx, listContests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestsRow{}
	for rows.Next() {
		var i ListContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestCode,
			&i.Name,
			&i.Sponsor,
			&i.CabrilloName,
			&i.ExchangeSchema,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContestSession = `-- name: UpdateContestSession :one
UPDATE contest_sessions
SET
    name                 = $1,
    starts_at            = $2,
    ends_at              = $3,
    category_operator    = $4,
    category_assisted    = $5,
    category_band        = $6,
    category_mode        = $7,
    category_power       = $8,
    category_station     = $9,
    category_time        = $10,
    category_transmitter = $11,
    category_overlay     = $12,
    operators_line       = $13,
    club_name            = $14,
    location             = $15,
    soapbox              = $16,
    exchange_sent        = $17,
    exchange_template    = $18,
    status               = $19,
    updated_at           = NOW()
WHERE uuid = $20
RETURNING
    id, uuid, user_id, logbook_id, contest_id, name,
    starts_at, ends_at, category_operator, category_assisted, category_band,
    category_mode, category_power, category_station, category_time,
    category_transmitter, category_overlay, operators_line, club_name,
    location, soapbox, exchange_sent, exchange_template,
    serial_counter, status, cabrillo_version, created_at, updated_at
`

type UpdateContestSessionParams struct {
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ExchangeSent        *string            `json:"exchange_sent"`
	ExchangeTemplate    string             `json:"exchange_template"`
	Status              string             `json:"status"`
	SessionUuid         uuid.UUID          `json:"session_uuid"`
}

type UpdateContestSessionRow struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	ContestID           int64              `json:"contest_id"`
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ExchangeSent        *string            `json:"exchange_sent"`
	ExchangeTemplate    string             `json:"exchange_template"`
	SerialCounter       int32              `json:"serial_counter"`
	Status              string             `json:"status"`
	CabrilloVersion     string             `json:"cabrillo_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateContestSession(ctx context.Context, arg UpdateContestSessionParams) (UpdateContestSessionRow, error) {
	row := q.db.QueryRow(ctx, updateContestSession,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
		arg.CategoryOperator,
		arg.CategoryAssisted,
		arg.CategoryBand,
		arg.CategoryMode,
		arg.CategoryPower,
		arg.CategoryStation,
		arg.CategoryTime,
		arg.CategoryTransmitter,
		arg.CategoryOverlay,
		arg.OperatorsLine,
		arg.ClubName,
		arg.Location,
		arg.Soapbox,
		arg.ExchangeSent,
		arg.ExchangeTemplate,
		arg.Status,
		arg.SessionUuid,
	)
	var i UpdateContestSessionRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.ContestID,
		&i.Name,
		&i.StartsAt,
		&i.EndsAt,
		&i.CategoryOperator,
		&i.CategoryAssisted,
		&i.CategoryBand,
		&i.CategoryMode,
		&i.CategoryPower,
		&i.CategoryStation,
		&i.CategoryTime,
		&i.CategoryTransmitter,
		&i.CategoryOverlay,
		&i.OperatorsLine,
		&i.ClubName,
		&i.Location,
		&i.Soapbox,
		&i.ExchangeSent,
		&i.ExchangeTemplate,
		&i.SerialCounter,
		&i.Status,
		&i.CabrilloVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContest = `-- name: UpsertContest :one
INSERT INTO contests (contest_code, name, cabrillo_name, exchange_schema)
VALUES (
    UPPER(BTRIM($1::text)),
    $2::text,
    UPPER(BTRIM($1::text)),
    '{}'::jsonb
)
ON CONFLICT (contest_code) DO UPDATE
    SET name = EXCLUDED.name
RETURNING id, contest_code, name, cabrillo_name, exchange_schema, active
`

type UpsertContestParams struct {
	ContestCode string `json:"contest_code"`
	Name        string `json:"name"`
}

type UpsertContestRow struct {
	ID             int64  `json:"id"`
	ContestCode    string `json:"contest_code"`
	Name           string `json:"name"`
	CabrilloName   string `json:"cabrillo_name"`
	ExchangeSchema []byte `json:"exchange_schema"`
	Active         bool   `json:"active"`
}

// Auto-provision a contest record by ADIF contest code.
// Inserts if not present; returns existing record if already there.
func (q *Queries) UpsertContest(ctx context.Context, arg UpsertContestParams) (UpsertContestRow, error) {
	row := q.db.QueryRow(ctx, upsertContest, arg.ContestCode, arg.Name)
	var i UpsertContestRow
	err := row.Scan(
		&i.ID,
		&i.ContestCode,
		&i.Name,
		&i.CabrilloName,
		&i.ExchangeSchema,
		&i.Active,
	)
	return i, err
}
