// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCredential = `-- name: DeleteCredential :execrows
DELETE FROM user_service_credentials
WHERE user_id = $1
  AND service = $2
`

type DeleteCredentialParams struct {
	UserID  int64  `json:"user_id"`
	Service string `json:"service"`
}

// Hard-delete the credential row.
// Encrypted ciphertext is worthless without the master key, so there is no
// audit value in retaining it after a user removes a service integration.
func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCredential, arg.UserID, arg.Service)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredential = `-- name: GetCredential :one
SELECT id, user_id, service, credential_type, credentials, key_version, expires_at, last_used_at, last_verified_at, is_active, created_at, updated_at
FROM user_service_credentials
WHERE user_id = $1
  AND service = $2
  AND is_active = TRUE
`

type GetCredentialParams struct {
	UserID  int64  `json:"user_id"`
	Service string `json:"service"`
}

// Retrieve the encrypted credential blob for a specific (user, service).
// RLS enforces that only the owning user can retrieve their own credentials.
// Callers must decrypt the credentials blob before using it.
func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (UserServiceCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.UserID, arg.Service)
	var i UserServiceCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Service,
		&i.CredentialType,
		&i.Credentials,
		&i.KeyVersion,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastVerifiedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, user_id, service, credential_type, key_version, expires_at, last_used_at, last_verified_at, is_active, created_at, updated_at
FROM user_service_credentials
WHERE user_id = $1
  AND is_active = TRUE
ORDER BY service ASC
`

type ListCredentialsRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Service        string             `json:"service"`
	CredentialType string             `json:"credential_type"`
	KeyVersion     int32              `json:"key_version"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// List credentials for a user — service names and metadata ONLY.
// The encrypted credentials blob is intentionally excluded from this query.
// Callers see which services are configured, but cannot retrieve the secrets.
func (q *Queries) ListCredentials(ctx context.Context, userID int64) ([]ListCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCredentialsRow{}
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Service,
			&i.CredentialType,
			&i.KeyVersion,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastVerifiedAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredentialLastUsed = `-- name: UpdateCredentialLastUsed :exec
UPDATE user_service_credentials
SET last_used_at = NOW()
WHERE user_id = $1
  AND service = $2
`

type UpdateCredentialLastUsedParams struct {
	UserID  int64  `json:"user_id"`
	Service string `json:"service"`
}

// Record when a credential was last used for a sync operation.
// Called by sync workers when they successfully use a stored credential.
func (q *Queries) UpdateCredentialLastUsed(ctx context.Context, arg UpdateCredentialLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateCredentialLastUsed, arg.UserID, arg.Service)
	return err
}

const upsertCredential = `-- name: UpsertCredential :one

INSERT INTO user_service_credentials (
    user_id,
    service,
    credential_type,
    credentials,
    key_version,
    expires_at,
    is_active,
    updated_at
)
VALUES (
    $1,  -- user_id
    $2,  -- service
    $3,  -- credential_type
    $4,  -- credentials (AES-256-GCM ciphertext: nonce || ciphertext || tag)
    $5,  -- key_version
    $6,  -- expires_at (NULL = no expiry)
    TRUE,
    NOW()
)
ON CONFLICT (user_id, service) DO UPDATE SET
    credential_type = EXCLUDED.credential_type,
    credentials     = EXCLUDED.credentials,
    key_version     = EXCLUDED.key_version,
    expires_at      = EXCLUDED.expires_at,
    is_active       = TRUE,
    updated_at      = NOW()
RETURNING id, user_id, service, credential_type, key_version, expires_at, last_used_at, last_verified_at, is_active, created_at, updated_at
`

type UpsertCredentialParams struct {
	UserID         int64              `json:"user_id"`
	Service        string             `json:"service"`
	CredentialType string             `json:"credential_type"`
	Credentials    []byte             `json:"credentials"`
	KeyVersion     int32              `json:"key_version"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type UpsertCredentialRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Service        string             `json:"service"`
	CredentialType string             `json:"credential_type"`
	KeyVersion     int32              `json:"key_version"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Queries for user_service_credentials (encrypted external service credentials).
// Plaintext is NEVER stored or logged here. All encryption/decryption happens in
// the Go crypto layer before calling these queries.
//
// Schema reference: docs/SCHEMA.md § user_service_credentials
// Encryption spec: docs/ARCHITECTURE.md § "Credential Encryption: AES-256-GCM"
// Insert or update an encrypted credential for a (user_id, service) pair.
// ON CONFLICT updates the ciphertext, key_version, and metadata.
// The UNIQUE(user_id, service) constraint ensures one active credential per service per user.
func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (UpsertCredentialRow, error) {
	row := q.db.QueryRow(ctx, upsertCredential,
		arg.UserID,
		arg.Service,
		arg.CredentialType,
		arg.Credentials,
		arg.KeyVersion,
		arg.ExpiresAt,
	)
	var i UpsertCredentialRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Service,
		&i.CredentialType,
		&i.KeyVersion,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastVerifiedAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
