// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_jobs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeImportJob = `-- name: CompleteImportJob :exec
UPDATE import_jobs
SET
    status = $1::text,
    completed_at = NOW(),
    total_records = $2::integer,
    imported = $3::integer,
    skipped = $4::integer,
    duplicate = $5::integer,
    errors = $6::integer,
    warnings = $7::integer
WHERE id = $8::bigint
`

type CompleteImportJobParams struct {
	Status       string `json:"status"`
	TotalRecords *int32 `json:"total_records"`
	Imported     int32  `json:"imported"`
	Skipped      int32  `json:"skipped"`
	Duplicate    int32  `json:"duplicate"`
	Errors       int32  `json:"errors"`
	Warnings     int32  `json:"warnings"`
	ID           int64  `json:"id"`
}

// Marks an import job as complete or errored with final counters.
func (q *Queries) CompleteImportJob(ctx context.Context, arg CompleteImportJobParams) error {
	_, err := q.db.Exec(ctx, completeImportJob,
		arg.Status,
		arg.TotalRecords,
		arg.Imported,
		arg.Skipped,
		arg.Duplicate,
		arg.Errors,
		arg.Warnings,
		arg.ID,
	)
	return err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO import_jobs (
    user_id,
    logbook_id,
    filename,
    file_size_bytes,
    status,
    source,
    dedup_strategy,
    timestamp_strategy
)
SELECT
    app_current_user_id(),
    lb.id,
    $1::text,
    $2::bigint,
    'pending',
    $3::text,
    'skip',
    'trust_utc'
FROM logbooks lb
WHERE lb.uuid = $4::uuid
  AND lb.deleted_at IS NULL
  AND app_has_logbook_min_role(lb.id, app_current_user_id(), 'operator')
RETURNING id, uuid, user_id, logbook_id, filename, file_size_bytes, status,
          total_records, imported, skipped, duplicate, errors, warnings,
          source, dedup_strategy, timestamp_strategy, source_timezone, adif_version,
          created_at, started_at, completed_at
`

type CreateImportJobParams struct {
	Filename      *string   `json:"filename"`
	FileSizeBytes *int64    `json:"file_size_bytes"`
	Source        string    `json:"source"`
	LogbookUuid   uuid.UUID `json:"logbook_uuid"`
}

// Creates a new import job record and returns the created row including its UUID.
func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob,
		arg.Filename,
		arg.FileSizeBytes,
		arg.Source,
		arg.LogbookUuid,
	)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.Filename,
		&i.FileSizeBytes,
		&i.Status,
		&i.TotalRecords,
		&i.Imported,
		&i.Skipped,
		&i.Duplicate,
		&i.Errors,
		&i.Warnings,
		&i.Source,
		&i.DedupStrategy,
		&i.TimestampStrategy,
		&i.SourceTimezone,
		&i.AdifVersion,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createImportJobError = `-- name: CreateImportJobError :exec
INSERT INTO import_job_errors (
    import_job_id,
    severity,
    record_number,
    line_number,
    adif_field,
    reason_code,
    reason_detail,
    raw_fragment
)
VALUES (
    $1::bigint,
    $2::text,
    $3::integer,
    $4::integer,
    $5::text,
    $6::text,
    $7::text,
    $8::text
)
`

type CreateImportJobErrorParams struct {
	ImportJobID  int64   `json:"import_job_id"`
	Severity     string  `json:"severity"`
	RecordNumber *int32  `json:"record_number"`
	LineNumber   *int32  `json:"line_number"`
	AdifField    *string `json:"adif_field"`
	ReasonCode   *string `json:"reason_code"`
	ReasonDetail string  `json:"reason_detail"`
	RawFragment  *string `json:"raw_fragment"`
}

// Records a single per-record parse or validation error for an import job.
func (q *Queries) CreateImportJobError(ctx context.Context, arg CreateImportJobErrorParams) error {
	_, err := q.db.Exec(ctx, createImportJobError,
		arg.ImportJobID,
		arg.Severity,
		arg.RecordNumber,
		arg.LineNumber,
		arg.AdifField,
		arg.ReasonCode,
		arg.ReasonDetail,
		arg.RawFragment,
	)
	return err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT
    id, uuid, user_id, logbook_id,
    filename, file_size_bytes, status,
    total_records, imported, skipped, duplicate, errors, warnings,
    source, dedup_strategy, timestamp_strategy, source_timezone, adif_version,
    created_at, started_at, completed_at
FROM import_jobs
WHERE id = $1::bigint
`

// Returns an import job by its internal ID (used by the River worker).
func (q *Queries) GetImportJobByID(ctx context.Context, id int64) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.Filename,
		&i.FileSizeBytes,
		&i.Status,
		&i.TotalRecords,
		&i.Imported,
		&i.Skipped,
		&i.Duplicate,
		&i.Errors,
		&i.Warnings,
		&i.Source,
		&i.DedupStrategy,
		&i.TimestampStrategy,
		&i.SourceTimezone,
		&i.AdifVersion,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getImportJobByUUID = `-- name: GetImportJobByUUID :one
SELECT
    ij.id,
    ij.uuid,
    ij.user_id,
    ij.logbook_id,
    lb.uuid AS logbook_uuid,
    ij.filename,
    ij.file_size_bytes,
    ij.status,
    ij.total_records,
    ij.imported,
    ij.skipped,
    ij.duplicate,
    ij.errors,
    ij.warnings,
    ij.source,
    ij.dedup_strategy,
    ij.timestamp_strategy,
    ij.source_timezone,
    ij.adif_version,
    ij.created_at,
    ij.started_at,
    ij.completed_at
FROM import_jobs ij
JOIN logbooks lb ON lb.id = ij.logbook_id
WHERE ij.uuid = $1::uuid
`

type GetImportJobByUUIDRow struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	UserID            int64              `json:"user_id"`
	LogbookID         int64              `json:"logbook_id"`
	LogbookUuid       uuid.UUID          `json:"logbook_uuid"`
	Filename          *string            `json:"filename"`
	FileSizeBytes     *int64             `json:"file_size_bytes"`
	Status            string             `json:"status"`
	TotalRecords      *int32             `json:"total_records"`
	Imported          int32              `json:"imported"`
	Skipped           int32              `json:"skipped"`
	Duplicate         int32              `json:"duplicate"`
	Errors            int32              `json:"errors"`
	Warnings          int32              `json:"warnings"`
	Source            string             `json:"source"`
	DedupStrategy     string             `json:"dedup_strategy"`
	TimestampStrategy string             `json:"timestamp_strategy"`
	SourceTimezone    *string            `json:"source_timezone"`
	AdifVersion       *string            `json:"adif_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

// Returns an import job by its UUID, scoped to the requesting user via RLS.
func (q *Queries) GetImportJobByUUID(ctx context.Context, importJobUuid uuid.UUID) (GetImportJobByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getImportJobByUUID, importJobUuid)
	var i GetImportJobByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.LogbookID,
		&i.LogbookUuid,
		&i.Filename,
		&i.FileSizeBytes,
		&i.Status,
		&i.TotalRecords,
		&i.Imported,
		&i.Skipped,
		&i.Duplicate,
		&i.Errors,
		&i.Warnings,
		&i.Source,
		&i.DedupStrategy,
		&i.TimestampStrategy,
		&i.SourceTimezone,
		&i.AdifVersion,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getImportJobErrors = `-- name: GetImportJobErrors :many
SELECT
    id, severity, record_number, line_number,
    adif_field, reason_code, reason_detail, raw_fragment, created_at
FROM import_job_errors
WHERE import_job_id = (
    SELECT id FROM import_jobs WHERE uuid = $1::uuid
)
ORDER BY id
LIMIT $2::integer
`

type GetImportJobErrorsParams struct {
	ImportJobUuid uuid.UUID `json:"import_job_uuid"`
	PageSize      int32     `json:"page_size"`
}

type GetImportJobErrorsRow struct {
	ID           int64              `json:"id"`
	Severity     string             `json:"severity"`
	RecordNumber *int32             `json:"record_number"`
	LineNumber   *int32             `json:"line_number"`
	AdifField    *string            `json:"adif_field"`
	ReasonCode   *string            `json:"reason_code"`
	ReasonDetail string             `json:"reason_detail"`
	RawFragment  *string            `json:"raw_fragment"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Returns errors for an import job, used for the error listing endpoint.
func (q *Queries) GetImportJobErrors(ctx context.Context, arg GetImportJobErrorsParams) ([]GetImportJobErrorsRow, error) {
	rows, err := q.db.Query(ctx, getImportJobErrors, arg.ImportJobUuid, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImportJobErrorsRow{}
	for rows.Next() {
		var i GetImportJobErrorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.RecordNumber,
			&i.LineNumber,
			&i.AdifField,
			&i.ReasonCode,
			&i.ReasonDetail,
			&i.RawFragment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestImportJobErrorByUUID = `-- name: GetLatestImportJobErrorByUUID :one
SELECT reason_detail
FROM import_job_errors
WHERE import_job_id = (
    SELECT id FROM import_jobs WHERE uuid = $1::uuid
)
ORDER BY id DESC
LIMIT 1
`

// Returns the most recent error reason for a given import job UUID.
func (q *Queries) GetLatestImportJobErrorByUUID(ctx context.Context, importJobUuid uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLatestImportJobErrorByUUID, importJobUuid)
	var reason_detail string
	err := row.Scan(&reason_detail)
	return reason_detail, err
}

const startImportJob = `-- name: StartImportJob :one
UPDATE import_jobs
SET
    status = 'processing',
    started_at = NOW(),
    total_records = $1::integer,
    adif_version = $2::text
WHERE id = $3::bigint
  AND status = 'pending'
RETURNING id, uuid, status, started_at, total_records
`

type StartImportJobParams struct {
	TotalRecords *int32  `json:"total_records"`
	AdifVersion  *string `json:"adif_version"`
	ID           int64   `json:"id"`
}

type StartImportJobRow struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	TotalRecords *int32             `json:"total_records"`
}

// Transitions a job to processing status and sets started_at.
func (q *Queries) StartImportJob(ctx context.Context, arg StartImportJobParams) (StartImportJobRow, error) {
	row := q.db.QueryRow(ctx, startImportJob, arg.TotalRecords, arg.AdifVersion, arg.ID)
	var i StartImportJobRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Status,
		&i.StartedAt,
		&i.TotalRecords,
	)
	return i, err
}

const updateImportJobProgress = `-- name: UpdateImportJobProgress :exec
UPDATE import_jobs
SET
    imported = $1::integer,
    skipped = $2::integer,
    duplicate = $3::integer,
    errors = $4::integer,
    warnings = $5::integer
WHERE id = $6::bigint
`

type UpdateImportJobProgressParams struct {
	Imported  int32 `json:"imported"`
	Skipped   int32 `json:"skipped"`
	Duplicate int32 `json:"duplicate"`
	Errors    int32 `json:"errors"`
	Warnings  int32 `json:"warnings"`
	ID        int64 `json:"id"`
}

// Updates rolling counters for a running import job. Called periodically by the worker.
func (q *Queries) UpdateImportJobProgress(ctx context.Context, arg UpdateImportJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateImportJobProgress,
		arg.Imported,
		arg.Skipped,
		arg.Duplicate,
		arg.Errors,
		arg.Warnings,
		arg.ID,
	)
	return err
}
