// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInviteByCode = `-- name: ConsumeInviteByCode :one
UPDATE invite_keys
SET uses_count = uses_count + 1,
    used_by = $1
WHERE code = UPPER(BTRIM($2::text))
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND uses_count < max_uses
RETURNING id, code, created_by, used_by, max_uses, uses_count, expires_at, created_at, revoked_at
`

type ConsumeInviteByCodeParams struct {
	UsedBy *int64 `json:"used_by"`
	Code   string `json:"code"`
}

func (q *Queries) ConsumeInviteByCode(ctx context.Context, arg ConsumeInviteByCodeParams) (InviteKey, error) {
	row := q.db.QueryRow(ctx, consumeInviteByCode, arg.UsedBy, arg.Code)
	var i InviteKey
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const countActiveInvitesByCreator = `-- name: CountActiveInvitesByCreator :one

SELECT COUNT(*)
FROM invite_keys
WHERE created_by = $1
  AND revoked_at IS NULL
  AND uses_count < max_uses
  AND (expires_at IS NULL OR expires_at > NOW())
`

// Queries for invite_keys table.
func (q *Queries) CountActiveInvitesByCreator(ctx context.Context, createdBy int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveInvitesByCreator, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInviteKey = `-- name: CreateInviteKey :one
INSERT INTO invite_keys (
    code,
    created_by,
    max_uses,
    expires_at
)
VALUES (
    UPPER(BTRIM($1::text)),
    $2,
    COALESCE($3::integer, 1),
    $4
)
RETURNING id, code, created_by, used_by, max_uses, uses_count, expires_at, created_at, revoked_at
`

type CreateInviteKeyParams struct {
	Code      string             `json:"code"`
	CreatedBy int64              `json:"created_by"`
	MaxUses   *int32             `json:"max_uses"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInviteKey(ctx context.Context, arg CreateInviteKeyParams) (InviteKey, error) {
	row := q.db.QueryRow(ctx, createInviteKey,
		arg.Code,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i InviteKey
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveInviteByCode = `-- name: GetActiveInviteByCode :one
SELECT id, code, created_by, used_by, max_uses, uses_count, expires_at, created_at, revoked_at
FROM invite_keys
WHERE code = UPPER(BTRIM($1::text))
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
  AND uses_count < max_uses
`

func (q *Queries) GetActiveInviteByCode(ctx context.Context, code string) (InviteKey, error) {
	row := q.db.QueryRow(ctx, getActiveInviteByCode, code)
	var i InviteKey
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedBy,
		&i.UsedBy,
		&i.MaxUses,
		&i.UsesCount,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listInviteKeysByCreator = `-- name: ListInviteKeysByCreator :many
SELECT id, code, created_by, used_by, max_uses, uses_count, expires_at, created_at, revoked_at
FROM invite_keys
WHERE created_by = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListInviteKeysByCreator(ctx context.Context, createdBy int64) ([]InviteKey, error) {
	rows, err := q.db.Query(ctx, listInviteKeysByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteKey{}
	for rows.Next() {
		var i InviteKey
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedBy,
			&i.UsedBy,
			&i.MaxUses,
			&i.UsesCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInviteKey = `-- name: RevokeInviteKey :execrows
UPDATE invite_keys
SET revoked_at = NOW()
WHERE id = $1
  AND created_by = $2
  AND revoked_at IS NULL
`

type RevokeInviteKeyParams struct {
	ID        int64 `json:"id"`
	CreatedBy int64 `json:"created_by"`
}

func (q *Queries) RevokeInviteKey(ctx context.Context, arg RevokeInviteKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInviteKey, arg.ID, arg.CreatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
