// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStationLocation = `-- name: CreateStationLocation :one

INSERT INTO station_locations (
    user_id,
    name,
    callsign,
    grid_square,
    latitude,
    longitude,
    location,
    dxcc_entity,
    state,
    county,
    city,
    country,
    lotw_location_name,
    lotw_cert_expiry,
    is_default
)
VALUES (
    $1,
    $2,
    UPPER($3),
    UPPER($4),
    $5,
    $6,
    CASE
        WHEN $5::numeric IS NOT NULL
         AND $6::numeric IS NOT NULL
        THEN ST_SetSRID(
                ST_MakePoint(
                    $6::float8,
                    $5::float8
                ), 4326)
        ELSE maidenhead_to_point($4)
    END,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
RETURNING
    id,
    uuid,
    user_id,
    name,
    callsign,
    grid_square,
    latitude,
    longitude,
    dxcc_entity,
    state,
    county,
    city,
    country,
    lotw_location_name,
    lotw_cert_expiry,
    is_default,
    created_at,
    updated_at
`

type CreateStationLocationParams struct {
	UserID           int64          `json:"user_id"`
	Name             string         `json:"name"`
	Callsign         interface{}    `json:"callsign"`
	GridSquare       interface{}    `json:"grid_square"`
	Latitude         pgtype.Numeric `json:"latitude"`
	Longitude        pgtype.Numeric `json:"longitude"`
	DxccEntity       *int32         `json:"dxcc_entity"`
	State            *string        `json:"state"`
	County           *string        `json:"county"`
	City             *string        `json:"city"`
	Country          *string        `json:"country"`
	LotwLocationName *string        `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date    `json:"lotw_cert_expiry"`
	IsDefault        bool           `json:"is_default"`
}

type CreateStationLocationRow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Callsign         string             `json:"callsign"`
	GridSquare       string             `json:"grid_square"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	DxccEntity       *int32             `json:"dxcc_entity"`
	State            *string            `json:"state"`
	County           *string            `json:"county"`
	City             *string            `json:"city"`
	Country          *string            `json:"country"`
	LotwLocationName *string            `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date        `json:"lotw_cert_expiry"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Queries for station_locations table.
//
// station_locations are the tQSL "station locations" required for LoTW integration.
// One callsign can have many locations (Home, POTA Portable, DXpedition), each with
// its own tQSL certificate. RLS isolates each user's locations.
//
// Schema reference: docs/SCHEMA.md § station_locations
// Creates a new station location for the authenticated user.
// The PostGIS location point is computed from lat/lon when both are provided,
// falling back to the maidenhead_to_point() function on the grid_square.
func (q *Queries) CreateStationLocation(ctx context.Context, arg CreateStationLocationParams) (CreateStationLocationRow, error) {
	row := q.db.QueryRow(ctx, createStationLocation,
		arg.UserID,
		arg.Name,
		arg.Callsign,
		arg.GridSquare,
		arg.Latitude,
		arg.Longitude,
		arg.DxccEntity,
		arg.State,
		arg.County,
		arg.City,
		arg.Country,
		arg.LotwLocationName,
		arg.LotwCertExpiry,
		arg.IsDefault,
	)
	var i CreateStationLocationRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.GridSquare,
		&i.Latitude,
		&i.Longitude,
		&i.DxccEntity,
		&i.State,
		&i.County,
		&i.City,
		&i.Country,
		&i.LotwLocationName,
		&i.LotwCertExpiry,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStationLocation = `-- name: DeleteStationLocation :exec
UPDATE station_locations
SET deleted_at = NOW(), updated_at = NOW()
WHERE uuid = $1
  AND deleted_at IS NULL
`

// Soft-deletes a station location. References from logbooks use ON DELETE SET NULL
// so logbooks are not affected.
func (q *Queries) DeleteStationLocation(ctx context.Context, locationUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStationLocation, locationUuid)
	return err
}

const getStationLocationByUUID = `-- name: GetStationLocationByUUID :one
SELECT
    id,
    uuid,
    user_id,
    name,
    callsign,
    grid_square,
    latitude,
    longitude,
    dxcc_entity,
    state,
    county,
    city,
    country,
    lotw_location_name,
    lotw_cert_expiry,
    is_default,
    created_at,
    updated_at
FROM station_locations
WHERE uuid = $1
  AND deleted_at IS NULL
`

type GetStationLocationByUUIDRow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Callsign         string             `json:"callsign"`
	GridSquare       string             `json:"grid_square"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	DxccEntity       *int32             `json:"dxcc_entity"`
	State            *string            `json:"state"`
	County           *string            `json:"county"`
	City             *string            `json:"city"`
	Country          *string            `json:"country"`
	LotwLocationName *string            `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date        `json:"lotw_cert_expiry"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Returns a station location by UUID, scoped to the authenticated user via RLS.
func (q *Queries) GetStationLocationByUUID(ctx context.Context, locationUuid uuid.UUID) (GetStationLocationByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getStationLocationByUUID, locationUuid)
	var i GetStationLocationByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.GridSquare,
		&i.Latitude,
		&i.Longitude,
		&i.DxccEntity,
		&i.State,
		&i.County,
		&i.City,
		&i.Country,
		&i.LotwLocationName,
		&i.LotwCertExpiry,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllExpiringCerts = `-- name: ListAllExpiringCerts :many
SELECT
    id,
    user_id,
    callsign,
    name,
    lotw_location_name,
    lotw_cert_expiry
FROM station_locations
WHERE lotw_cert_expiry IS NOT NULL
  AND deleted_at IS NULL
ORDER BY lotw_cert_expiry ASC
`

type ListAllExpiringCertsRow struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	Callsign         string      `json:"callsign"`
	Name             string      `json:"name"`
	LotwLocationName *string     `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date `json:"lotw_cert_expiry"`
}

// Worker query: returns all station locations with a non-null lotw_cert_expiry.
// Used by CertExpiryCheckJob to find certificates approaching expiry.
// Runs as radioledger_worker role (see migration 013 for the SELECT policy).
// No user filter — intentionally queries across all users.
func (q *Queries) ListAllExpiringCerts(ctx context.Context) ([]ListAllExpiringCertsRow, error) {
	rows, err := q.db.Query(ctx, listAllExpiringCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllExpiringCertsRow{}
	for rows.Next() {
		var i ListAllExpiringCertsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Callsign,
			&i.Name,
			&i.LotwLocationName,
			&i.LotwCertExpiry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationLocations = `-- name: ListStationLocations :many
SELECT
    id,
    uuid,
    user_id,
    name,
    callsign,
    grid_square,
    latitude,
    longitude,
    dxcc_entity,
    state,
    county,
    city,
    country,
    lotw_location_name,
    lotw_cert_expiry,
    is_default,
    created_at,
    updated_at
FROM station_locations
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY is_default DESC, created_at DESC, id DESC
`

type ListStationLocationsRow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Callsign         string             `json:"callsign"`
	GridSquare       string             `json:"grid_square"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	DxccEntity       *int32             `json:"dxcc_entity"`
	State            *string            `json:"state"`
	County           *string            `json:"county"`
	City             *string            `json:"city"`
	Country          *string            `json:"country"`
	LotwLocationName *string            `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date        `json:"lotw_cert_expiry"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Lists all active station locations for the authenticated user, newest first.
func (q *Queries) ListStationLocations(ctx context.Context, userID int64) ([]ListStationLocationsRow, error) {
	rows, err := q.db.Query(ctx, listStationLocations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationLocationsRow{}
	for rows.Next() {
		var i ListStationLocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.Callsign,
			&i.GridSquare,
			&i.Latitude,
			&i.Longitude,
			&i.DxccEntity,
			&i.State,
			&i.County,
			&i.City,
			&i.Country,
			&i.LotwLocationName,
			&i.LotwCertExpiry,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertExpiryByCallsign = `-- name: UpdateCertExpiryByCallsign :execrows
UPDATE station_locations
SET
    lotw_cert_expiry = $1,
    updated_at       = NOW()
WHERE user_id       = $2
  AND callsign      = UPPER($3)
  AND deleted_at    IS NULL
`

type UpdateCertExpiryByCallsignParams struct {
	LotwCertExpiry pgtype.Date `json:"lotw_cert_expiry"`
	UserID         int64       `json:"user_id"`
	Callsign       interface{} `json:"callsign"`
}

// Updates lotw_cert_expiry on all active station locations matching the callsign
// for the authenticated user. Called by POST /v1/desktop/cert-expiry.
// Returns the number of rows updated (0 = no matching location found).
func (q *Queries) UpdateCertExpiryByCallsign(ctx context.Context, arg UpdateCertExpiryByCallsignParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCertExpiryByCallsign, arg.LotwCertExpiry, arg.UserID, arg.Callsign)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStationLocation = `-- name: UpdateStationLocation :one
UPDATE station_locations
SET
    name               = $1,
    callsign           = UPPER($2),
    grid_square        = UPPER($3),
    latitude           = $4,
    longitude          = $5,
    location           = CASE
                             WHEN $4::numeric IS NOT NULL
                              AND $5::numeric IS NOT NULL
                             THEN ST_SetSRID(
                                     ST_MakePoint(
                                         $5::float8,
                                         $4::float8
                                     ), 4326)
                             ELSE maidenhead_to_point($3)
                         END,
    dxcc_entity        = $6,
    state              = $7,
    county             = $8,
    city               = $9,
    country            = $10,
    lotw_location_name = $11,
    lotw_cert_expiry   = $12,
    is_default         = $13,
    updated_at         = NOW()
WHERE uuid = $14
  AND deleted_at IS NULL
RETURNING
    id,
    uuid,
    user_id,
    name,
    callsign,
    grid_square,
    latitude,
    longitude,
    dxcc_entity,
    state,
    county,
    city,
    country,
    lotw_location_name,
    lotw_cert_expiry,
    is_default,
    created_at,
    updated_at
`

type UpdateStationLocationParams struct {
	Name             string         `json:"name"`
	Callsign         interface{}    `json:"callsign"`
	GridSquare       interface{}    `json:"grid_square"`
	Latitude         pgtype.Numeric `json:"latitude"`
	Longitude        pgtype.Numeric `json:"longitude"`
	DxccEntity       *int32         `json:"dxcc_entity"`
	State            *string        `json:"state"`
	County           *string        `json:"county"`
	City             *string        `json:"city"`
	Country          *string        `json:"country"`
	LotwLocationName *string        `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date    `json:"lotw_cert_expiry"`
	IsDefault        bool           `json:"is_default"`
	LocationUuid     uuid.UUID      `json:"location_uuid"`
}

type UpdateStationLocationRow struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Callsign         string             `json:"callsign"`
	GridSquare       string             `json:"grid_square"`
	Latitude         pgtype.Numeric     `json:"latitude"`
	Longitude        pgtype.Numeric     `json:"longitude"`
	DxccEntity       *int32             `json:"dxcc_entity"`
	State            *string            `json:"state"`
	County           *string            `json:"county"`
	City             *string            `json:"city"`
	Country          *string            `json:"country"`
	LotwLocationName *string            `json:"lotw_location_name"`
	LotwCertExpiry   pgtype.Date        `json:"lotw_cert_expiry"`
	IsDefault        bool               `json:"is_default"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Updates a station location by UUID. Recomputes the PostGIS point when coordinates change.
func (q *Queries) UpdateStationLocation(ctx context.Context, arg UpdateStationLocationParams) (UpdateStationLocationRow, error) {
	row := q.db.QueryRow(ctx, updateStationLocation,
		arg.Name,
		arg.Callsign,
		arg.GridSquare,
		arg.Latitude,
		arg.Longitude,
		arg.DxccEntity,
		arg.State,
		arg.County,
		arg.City,
		arg.Country,
		arg.LotwLocationName,
		arg.LotwCertExpiry,
		arg.IsDefault,
		arg.LocationUuid,
	)
	var i UpdateStationLocationRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.GridSquare,
		&i.Latitude,
		&i.Longitude,
		&i.DxccEntity,
		&i.State,
		&i.County,
		&i.City,
		&i.Country,
		&i.LotwLocationName,
		&i.LotwCertExpiry,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
