// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logbooks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLogbook = `-- name: CreateLogbook :one
INSERT INTO logbooks (
    user_id,
    name,
    callsign,
    description,
    is_default
)
VALUES (
    $1,
    $2,
    CASE
        WHEN $3::text IS NULL THEN NULL
        ELSE UPPER($3::text)
    END,
    $4,
    $5
)
RETURNING
    id,
    uuid,
    user_id,
    name,
    callsign,
    description,
    is_default,
    created_at,
    updated_at
`

type CreateLogbookParams struct {
	UserID      int64   `json:"user_id"`
	Name        string  `json:"name"`
	Callsign    *string `json:"callsign"`
	Description *string `json:"description"`
	IsDefault   bool    `json:"is_default"`
}

type CreateLogbookRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Callsign    *string            `json:"callsign"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLogbook(ctx context.Context, arg CreateLogbookParams) (CreateLogbookRow, error) {
	row := q.db.QueryRow(ctx, createLogbook,
		arg.UserID,
		arg.Name,
		arg.Callsign,
		arg.Description,
		arg.IsDefault,
	)
	var i CreateLogbookRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLogbook = `-- name: DeleteLogbook :one
UPDATE logbooks
SET
    deleted_at = NOW(),
    is_default = FALSE,
    updated_at = NOW()
WHERE uuid = $1
  AND deleted_at IS NULL
RETURNING uuid
`

func (q *Queries) DeleteLogbook(ctx context.Context, logbookUuid uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLogbook, logbookUuid)
	var uuid uuid.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const getDefaultLogbook = `-- name: GetDefaultLogbook :one
SELECT
    id,
    uuid,
    user_id,
    name,
    callsign,
    description,
    is_default,
    created_at,
    updated_at
FROM logbooks
WHERE user_id = $1
  AND is_default = TRUE
  AND deleted_at IS NULL
LIMIT 1
`

type GetDefaultLogbookRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Callsign    *string            `json:"callsign"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDefaultLogbook(ctx context.Context, userID int64) (GetDefaultLogbookRow, error) {
	row := q.db.QueryRow(ctx, getDefaultLogbook, userID)
	var i GetDefaultLogbookRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLogbookByUUID = `-- name: GetLogbookByUUID :one
SELECT
    id,
    uuid,
    user_id,
    name,
    callsign,
    description,
    is_default,
    created_at,
    updated_at
FROM logbooks
WHERE uuid = $1
  AND deleted_at IS NULL
`

type GetLogbookByUUIDRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Callsign    *string            `json:"callsign"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLogbookByUUID(ctx context.Context, logbookUuid uuid.UUID) (GetLogbookByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getLogbookByUUID, logbookUuid)
	var i GetLogbookByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLogbooksByUser = `-- name: ListLogbooksByUser :many
SELECT
    l.id,
    l.uuid,
    l.user_id,
    l.name,
    l.callsign,
    l.description,
    l.is_default,
    l.created_at,
    l.updated_at
FROM logbooks l
JOIN user_roles ur ON ur.logbook_id = l.id
WHERE ur.user_id = $1
  AND l.deleted_at IS NULL
ORDER BY l.created_at DESC, l.id DESC
`

type ListLogbooksByUserRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Callsign    *string            `json:"callsign"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLogbooksByUser(ctx context.Context, userID int64) ([]ListLogbooksByUserRow, error) {
	rows, err := q.db.Query(ctx, listLogbooksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogbooksByUserRow{}
	for rows.Next() {
		var i ListLogbooksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Name,
			&i.Callsign,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLogbook = `-- name: UpdateLogbook :one
UPDATE logbooks
SET
    name = $1,
    callsign = CASE
        WHEN $2::text IS NULL THEN NULL
        ELSE UPPER($2::text)
    END,
    description = $3,
    is_default = $4,
    updated_at = NOW()
WHERE uuid = $5
  AND deleted_at IS NULL
RETURNING
    id,
    uuid,
    user_id,
    name,
    callsign,
    description,
    is_default,
    created_at,
    updated_at
`

type UpdateLogbookParams struct {
	Name        string    `json:"name"`
	Callsign    *string   `json:"callsign"`
	Description *string   `json:"description"`
	IsDefault   bool      `json:"is_default"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

type UpdateLogbookRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	Callsign    *string            `json:"callsign"`
	Description *string            `json:"description"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateLogbook(ctx context.Context, arg UpdateLogbookParams) (UpdateLogbookRow, error) {
	row := q.db.QueryRow(ctx, updateLogbook,
		arg.Name,
		arg.Callsign,
		arg.Description,
		arg.IsDefault,
		arg.LogbookUuid,
	)
	var i UpdateLogbookRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Name,
		&i.Callsign,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
