// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLogbookMemberByUserUUID = `-- name: DeleteLogbookMemberByUserUUID :execrows
DELETE FROM user_roles ur
USING logbooks lb, users u
WHERE ur.logbook_id = lb.id
  AND ur.user_id = u.id
  AND lb.uuid = $1
  AND u.uuid = $2
  AND lb.deleted_at IS NULL
  AND u.deleted_at IS NULL
`

type DeleteLogbookMemberByUserUUIDParams struct {
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
	UserUuid    uuid.UUID `json:"user_uuid"`
}

func (q *Queries) DeleteLogbookMemberByUserUUID(ctx context.Context, arg DeleteLogbookMemberByUserUUIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLogbookMemberByUserUUID, arg.LogbookUuid, arg.UserUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLogbookMemberByUserUUID = `-- name: GetLogbookMemberByUserUUID :one
SELECT
    ur.logbook_id,
    u.id AS user_id,
    u.uuid AS user_uuid,
    u.email,
    u.callsign,
    u.display_name,
    ur.role,
    ur.created_at,
    ur.updated_at
FROM user_roles ur
JOIN logbooks lb ON lb.id = ur.logbook_id
JOIN users u ON u.id = ur.user_id
WHERE lb.uuid = $1
  AND u.uuid = $2
  AND lb.deleted_at IS NULL
  AND u.deleted_at IS NULL
`

type GetLogbookMemberByUserUUIDParams struct {
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
	UserUuid    uuid.UUID `json:"user_uuid"`
}

type GetLogbookMemberByUserUUIDRow struct {
	LogbookID   int64              `json:"logbook_id"`
	UserID      int64              `json:"user_id"`
	UserUuid    uuid.UUID          `json:"user_uuid"`
	Email       string             `json:"email"`
	Callsign    *string            `json:"callsign"`
	DisplayName *string            `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLogbookMemberByUserUUID(ctx context.Context, arg GetLogbookMemberByUserUUIDParams) (GetLogbookMemberByUserUUIDRow, error) {
	row := q.db.QueryRow(ctx, getLogbookMemberByUserUUID, arg.LogbookUuid, arg.UserUuid)
	var i GetLogbookMemberByUserUUIDRow
	err := row.Scan(
		&i.LogbookID,
		&i.UserID,
		&i.UserUuid,
		&i.Email,
		&i.Callsign,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLogbookOwner = `-- name: GetLogbookOwner :one
SELECT
    u.id AS user_id,
    u.uuid AS user_uuid,
    ur.role
FROM user_roles ur
JOIN logbooks lb ON lb.id = ur.logbook_id
JOIN users u ON u.id = ur.user_id
WHERE lb.uuid = $1
  AND ur.role = 'owner'
  AND lb.deleted_at IS NULL
LIMIT 1
`

type GetLogbookOwnerRow struct {
	UserID   int64     `json:"user_id"`
	UserUuid uuid.UUID `json:"user_uuid"`
	Role     string    `json:"role"`
}

func (q *Queries) GetLogbookOwner(ctx context.Context, logbookUuid uuid.UUID) (GetLogbookOwnerRow, error) {
	row := q.db.QueryRow(ctx, getLogbookOwner, logbookUuid)
	var i GetLogbookOwnerRow
	err := row.Scan(&i.UserID, &i.UserUuid, &i.Role)
	return i, err
}

const getUserRoleForLogbook = `-- name: GetUserRoleForLogbook :one
SELECT ur.role
FROM user_roles ur
JOIN logbooks lb ON lb.id = ur.logbook_id
WHERE lb.uuid = $1
  AND ur.user_id = $2
  AND lb.deleted_at IS NULL
`

type GetUserRoleForLogbookParams struct {
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
	UserID      int64     `json:"user_id"`
}

func (q *Queries) GetUserRoleForLogbook(ctx context.Context, arg GetUserRoleForLogbookParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserRoleForLogbook, arg.LogbookUuid, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listLogbookMembers = `-- name: ListLogbookMembers :many
SELECT
    u.id AS user_id,
    u.uuid AS user_uuid,
    u.email,
    u.callsign,
    u.display_name,
    ur.role,
    ur.created_at,
    ur.updated_at
FROM user_roles ur
JOIN logbooks lb ON lb.id = ur.logbook_id
JOIN users u ON u.id = ur.user_id
WHERE lb.uuid = $1
  AND lb.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY app_role_rank(ur.role) DESC, lower(u.email) ASC
`

type ListLogbookMembersRow struct {
	UserID      int64              `json:"user_id"`
	UserUuid    uuid.UUID          `json:"user_uuid"`
	Email       string             `json:"email"`
	Callsign    *string            `json:"callsign"`
	DisplayName *string            `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLogbookMembers(ctx context.Context, logbookUuid uuid.UUID) ([]ListLogbookMembersRow, error) {
	rows, err := q.db.Query(ctx, listLogbookMembers, logbookUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogbookMembersRow{}
	for rows.Next() {
		var i ListLogbookMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserUuid,
			&i.Email,
			&i.Callsign,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLogbookMemberRoleByUserID = `-- name: SetLogbookMemberRoleByUserID :execrows
UPDATE user_roles
SET
    role = $1,
    invited_by = $2,
    updated_at = NOW()
WHERE logbook_id = $3
  AND user_id = $4
`

type SetLogbookMemberRoleByUserIDParams struct {
	Role      string `json:"role"`
	InvitedBy *int64 `json:"invited_by"`
	LogbookID int64  `json:"logbook_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) SetLogbookMemberRoleByUserID(ctx context.Context, arg SetLogbookMemberRoleByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLogbookMemberRoleByUserID,
		arg.Role,
		arg.InvitedBy,
		arg.LogbookID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLogbookOwnerUser = `-- name: SetLogbookOwnerUser :execrows
UPDATE logbooks
SET
    user_id = $1,
    is_default = FALSE,
    updated_at = NOW()
WHERE uuid = $2
  AND deleted_at IS NULL
`

type SetLogbookOwnerUserParams struct {
	UserID      int64     `json:"user_id"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

func (q *Queries) SetLogbookOwnerUser(ctx context.Context, arg SetLogbookOwnerUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLogbookOwnerUser, arg.UserID, arg.LogbookUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLogbookMemberRoleByUserUUID = `-- name: UpdateLogbookMemberRoleByUserUUID :one
UPDATE user_roles ur
SET
    role = $1,
    invited_by = $2,
    updated_at = NOW()
FROM logbooks lb, users u
WHERE ur.logbook_id = lb.id
  AND ur.user_id = u.id
  AND lb.uuid = $3
  AND u.uuid = $4
  AND lb.deleted_at IS NULL
  AND u.deleted_at IS NULL
RETURNING
    ur.id,
    ur.uuid,
    ur.logbook_id,
    ur.user_id,
    ur.role,
    ur.invited_by,
    ur.created_at,
    ur.updated_at
`

type UpdateLogbookMemberRoleByUserUUIDParams struct {
	Role        string    `json:"role"`
	InvitedBy   *int64    `json:"invited_by"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
	UserUuid    uuid.UUID `json:"user_uuid"`
}

func (q *Queries) UpdateLogbookMemberRoleByUserUUID(ctx context.Context, arg UpdateLogbookMemberRoleByUserUUIDParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, updateLogbookMemberRoleByUserUUID,
		arg.Role,
		arg.InvitedBy,
		arg.LogbookUuid,
		arg.UserUuid,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.LogbookID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLogbookMemberRole = `-- name: UpsertLogbookMemberRole :one
INSERT INTO user_roles (
    logbook_id,
    user_id,
    role,
    invited_by
)
SELECT
    lb.id,
    $1,
    $2,
    $3
FROM logbooks lb
WHERE lb.uuid = $4
  AND lb.deleted_at IS NULL
ON CONFLICT (logbook_id, user_id)
DO UPDATE SET
    role = EXCLUDED.role,
    invited_by = EXCLUDED.invited_by,
    updated_at = NOW()
RETURNING
    id,
    uuid,
    logbook_id,
    user_id,
    role,
    invited_by,
    created_at,
    updated_at
`

type UpsertLogbookMemberRoleParams struct {
	UserID      int64     `json:"user_id"`
	Role        string    `json:"role"`
	InvitedBy   *int64    `json:"invited_by"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

func (q *Queries) UpsertLogbookMemberRole(ctx context.Context, arg UpsertLogbookMemberRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, upsertLogbookMemberRole,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.LogbookUuid,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.LogbookID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
