// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Portable activation sessions (POTA/SOTA/etc.) grouped by reference + date.
type Activation struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	UserID    int64     `json:"user_id"`
	LogbookID int64     `json:"logbook_id"`
	Program   string    `json:"program"`
	// Program reference identifier: POTA park (e.g., K-1234) or SOTA summit (e.g., W4C/WM-001). Stored uppercase.
	Reference         string      `json:"reference"`
	ActivationDate    pgtype.Date `json:"activation_date"`
	StationLocationID *int64      `json:"station_location_id"`
	Notes             *string     `json:"notes"`
	// Activation workflow state: in_progress, valid (minimum criteria met), or submitted (uploaded to target service).
	Status          string             `json:"status"`
	QsoCount        int32              `json:"qso_count"`
	UniqueCallsigns int32              `json:"unique_callsigns"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// API keys for scripting and automation. key_hash = SHA-256 of full key (shown once at creation, never stored).
type ApiKey struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	KeyHash   string    `json:"key_hash"`
	KeyPrefix string    `json:"key_prefix"`
	// Least-privilege API scopes. Examples: qsos:read, qsos:write, adif:import, sync:trigger.
	Scopes     []string           `json:"scopes"`
	AllowedIps []netip.Addr       `json:"allowed_ips"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	LastUsedIp *netip.Addr        `json:"last_used_ip"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// QSO mutation audit trail. Partitioned by month. GDPR deletion: SET user_id=NULL, ip_address=NULL (anonymize) rather than deleting rows.
type AuditLog struct {
	ID        *int64             `json:"id"`
	UserID    *int64             `json:"user_id"`
	TableName string             `json:"table_name"`
	RecordID  int64              `json:"record_id"`
	Action    string             `json:"action"`
	OldValues []byte             `json:"old_values"`
	NewValues []byte             `json:"new_values"`
	ChangedBy *string            `json:"changed_by"`
	IpAddress *netip.Addr        `json:"ip_address"`
	RequestID *string            `json:"request_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Materialized award progress. dirty=TRUE triggers recalculation by AwardProgressRefreshJob.
type AwardProgress struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	AwardType  string  `json:"award_type"`
	EntityKey  string  `json:"entity_key"`
	Band       *string `json:"band"`
	Mode       *string `json:"mode"`
	FirstQsoID *int64  `json:"first_qso_id"`
	Confirmed  bool    `json:"confirmed"`
	// HOW confirmation happened: lotw, eqsl, qsl_card, radioledger. Matters for award submission reporting.
	ConfirmationMethod *string            `json:"confirmation_method"`
	ConfirmedVia       *string            `json:"confirmed_via"`
	ConfirmedAt        pgtype.Timestamptz `json:"confirmed_at"`
	// Total QSOs contributing to this award entity (band/mode combo). Updated by AwardRefreshWorker.
	QsoCount int64 `json:"qso_count"`
	// Timestamp of the most recent QSO contributing to this progress record.
	LastQsoAt pgtype.Timestamptz `json:"last_qso_at"`
	// TRUE when at least one QSO has been logged for this entity_key/band/mode.
	Worked bool `json:"worked"`
	// Set TRUE by AFTER trigger when a relevant QSO changes. Cleared to FALSE on successful recalculation.
	Dirty     bool               `json:"dirty"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Award programs a user is actively pursuing.
type AwardTracking struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	UserID    int64     `json:"user_id"`
	LogbookID *int64    `json:"logbook_id"`
	AwardType string    `json:"award_type"`
	// JSON config for this award instance. DXCC example: {"band": "20m", "mode": "CW", "confirmed_only": true}.
	AwardConfig []byte             `json:"award_config"`
	Enabled     bool               `json:"enabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Band struct {
	Name      string         `json:"name"`
	LowerFreq pgtype.Numeric `json:"lower_freq"`
	UpperFreq pgtype.Numeric `json:"upper_freq"`
	BandGroup *string        `json:"band_group"`
	// TRUE for WARC bands (30m, 17m, 12m). Excluded from most major contest categories.
	Warc bool `json:"warc"`
	// TRUE for bands shown in default UI views. FALSE for obscure/experimental/country-specific bands.
	IsCommon bool `json:"is_common"`
	// Display sort order. Lower values appear first. HF bands 1–20, VHF/UHF 11–18, others 50+
	SortOrder int32 `json:"sort_order"`
}

// Per-ITU-region band allocations with region-specific frequency edges. Used for region-aware band visibility defaults.
type BandRegionAllocation struct {
	ID int64 `json:"id"`
	// 1=Europe/Africa/Middle East, 2=Americas, 3=Asia/Pacific.
	ItuRegion int32          `json:"itu_region"`
	BandName  string         `json:"band_name"`
	LowerFreq pgtype.Numeric `json:"lower_freq"`
	UpperFreq pgtype.Numeric `json:"upper_freq"`
	// TRUE if the band is commonly used/allocated in that region and should appear in default UI band pickers.
	IsDefaultVisible bool    `json:"is_default_visible"`
	Notes            *string `json:"notes"`
}

type CallsignCache struct {
	Callsign  string             `json:"callsign"`
	Data      []byte             `json:"data"`
	Source    string             `json:"source"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CallsignRecord struct {
	ID            int64              `json:"id"`
	Callsign      string             `json:"callsign"`
	Source        string             `json:"source"`
	SourceID      *string            `json:"source_id"`
	FirstName     *string            `json:"first_name"`
	LastName      *string            `json:"last_name"`
	FullName      *string            `json:"full_name"`
	AddressLine1  *string            `json:"address_line1"`
	AddressLine2  *string            `json:"address_line2"`
	City          *string            `json:"city"`
	StateProvince *string            `json:"state_province"`
	PostalCode    *string            `json:"postal_code"`
	Country       string             `json:"country"`
	LicenseClass  *string            `json:"license_class"`
	GrantDate     pgtype.Date        `json:"grant_date"`
	ExpiryDate    pgtype.Date        `json:"expiry_date"`
	Status        string             `json:"status"`
	GridSquare    *string            `json:"grid_square"`
	Latitude      *float64           `json:"latitude"`
	Longitude     *float64           `json:"longitude"`
	DxccEntityID  *int32             `json:"dxcc_entity_id"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CallsignSyncRun struct {
	ID               int64              `json:"id"`
	Source           string             `json:"source"`
	RunType          string             `json:"run_type"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	RecordsProcessed int32              `json:"records_processed"`
	RecordsAdded     int32              `json:"records_added"`
	RecordsUpdated   int32              `json:"records_updated"`
	RecordsRemoved   int32              `json:"records_removed"`
	Status           string             `json:"status"`
	Error            *string            `json:"error"`
}

// Contest metadata used for category validation, exchange parsing, and Cabrillo export.
type Contest struct {
	ID             int64              `json:"id"`
	ContestCode    string             `json:"contest_code"`
	Name           string             `json:"name"`
	Sponsor        *string            `json:"sponsor"`
	CabrilloName   string             `json:"cabrillo_name"`
	ExchangeSchema []byte             `json:"exchange_schema"`
	Active         bool               `json:"active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Normalized multiplier tracking for contests.
type ContestMultiplier struct {
	ID               int64              `json:"id"`
	ContestSessionID int64              `json:"contest_session_id"`
	MultiplierType   string             `json:"multiplier_type"`
	MultiplierKey    string             `json:"multiplier_key"`
	Band             *string            `json:"band"`
	Mode             *string            `json:"mode"`
	FirstQsoID       *int64             `json:"first_qso_id"`
	Value            int16              `json:"value"`
	WorkedAt         pgtype.Timestamptz `json:"worked_at"`
}

// Per-QSO contest exchange and serial information for native contest logging and Cabrillo generation.
type ContestQsoExchange struct {
	QsoID            int64              `json:"qso_id"`
	ContestSessionID int64              `json:"contest_session_id"`
	SentSerial       *int32             `json:"sent_serial"`
	RecvSerial       *int32             `json:"recv_serial"`
	SentExchange     *string            `json:"sent_exchange"`
	RecvExchange     *string            `json:"recv_exchange"`
	QsoPoints        *int16             `json:"qso_points"`
	IsDupe           bool               `json:"is_dupe"`
	MultiplierCredit []byte             `json:"multiplier_credit"`
	CabrilloQsoLine  *string            `json:"cabrillo_qso_line"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Native contest logging session. Holds multi-operator categories, Cabrillo header metadata, and links contest QSOs.
type ContestSession struct {
	ID                  int64              `json:"id"`
	Uuid                uuid.UUID          `json:"uuid"`
	UserID              int64              `json:"user_id"`
	LogbookID           int64              `json:"logbook_id"`
	ContestID           int64              `json:"contest_id"`
	StationCallsignID   *int64             `json:"station_callsign_id"`
	Name                string             `json:"name"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	CategoryOperator    string             `json:"category_operator"`
	CategoryAssisted    string             `json:"category_assisted"`
	CategoryBand        string             `json:"category_band"`
	CategoryMode        string             `json:"category_mode"`
	CategoryPower       string             `json:"category_power"`
	CategoryStation     string             `json:"category_station"`
	CategoryTime        string             `json:"category_time"`
	CategoryTransmitter string             `json:"category_transmitter"`
	CategoryOverlay     *string            `json:"category_overlay"`
	OperatorsLine       *string            `json:"operators_line"`
	ClubName            *string            `json:"club_name"`
	Location            *string            `json:"location"`
	Soapbox             *string            `json:"soapbox"`
	ClaimedScore        *int64             `json:"claimed_score"`
	ExchangeSent        *string            `json:"exchange_sent"`
	CabrilloVersion     string             `json:"cabrillo_version"`
	// Controls UI entry fields and Cabrillo SENT-EXCH format. serial=auto counter; grid=Maidenhead; state=US state/province; zone=CQ/ITU zone; custom=free text.
	ExchangeTemplate string `json:"exchange_template"`
	// Monotonically increasing QSO serial. Incremented atomically by UPDATE...RETURNING; never client-supplied.
	SerialCounter int32 `json:"serial_counter"`
	// active=contest in progress; finished=window closed; submitted=Cabrillo submitted to sponsor.
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Operator roster for contest sessions.
type ContestSessionOperator struct {
	ID               int64              `json:"id"`
	ContestSessionID int64              `json:"contest_session_id"`
	OperatorID       int64              `json:"operator_id"`
	Role             string             `json:"role"`
	OperatingFrom    pgtype.Timestamptz `json:"operating_from"`
	OperatingTo      pgtype.Timestamptz `json:"operating_to"`
	IsPrimary        bool               `json:"is_primary"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// ARRL DXCC entity list. Do not delete rows — deleted entities still valid for historical QSOs.
type DxccEntity struct {
	EntityID int32  `json:"entity_id"`
	Name     string `json:"name"`
	// LoTW sometimes uses different entity names than the DXCC standard list. Stored here for matching during LoTW sync confirmation.
	LotwEntityName *string        `json:"lotw_entity_name"`
	Prefix         string         `json:"prefix"`
	Continent      string         `json:"continent"`
	CqZone         *int16         `json:"cq_zone"`
	ItuZone        *int16         `json:"itu_zone"`
	Latitude       pgtype.Numeric `json:"latitude"`
	Longitude      pgtype.Numeric `json:"longitude"`
	Location       interface{}    `json:"location"`
	Deleted        bool           `json:"deleted"`
	ValidFrom      pgtype.Date    `json:"valid_from"`
	ValidTo        pgtype.Date    `json:"valid_to"`
}

type DxccPrefix struct {
	Prefix    string             `json:"prefix"`
	EntityID  int32              `json:"entity_id"`
	Source    string             `json:"source"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EqslSyncStatus struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	LastPullAt pgtype.Timestamptz `json:"last_pull_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Async ADIF import jobs with summary counters. Per-row failures stored in import_job_errors.
type ImportJob struct {
	ID            int64     `json:"id"`
	Uuid          uuid.UUID `json:"uuid"`
	UserID        int64     `json:"user_id"`
	LogbookID     int64     `json:"logbook_id"`
	Filename      *string   `json:"filename"`
	FileSizeBytes *int64    `json:"file_size_bytes"`
	Status        string    `json:"status"`
	TotalRecords  *int32    `json:"total_records"`
	Imported      int32     `json:"imported"`
	Skipped       int32     `json:"skipped"`
	Duplicate     int32     `json:"duplicate"`
	Errors        int32     `json:"errors"`
	Warnings      int32     `json:"warnings"`
	Source        string    `json:"source"`
	DedupStrategy string    `json:"dedup_strategy"`
	// UTC interpretation mode: trust_utc, interpret_local, detect_and_warn.
	TimestampStrategy string             `json:"timestamp_strategy"`
	SourceTimezone    *string            `json:"source_timezone"`
	AdifVersion       *string            `json:"adif_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

// Per-record import errors/warnings. Avoids large JSONB arrays on bad imports.
type ImportJobError struct {
	ID            int64              `json:"id"`
	ImportJobID   int64              `json:"import_job_id"`
	Severity      string             `json:"severity"`
	RecordNumber  *int32             `json:"record_number"`
	LineNumber    *int32             `json:"line_number"`
	AdifField     *string            `json:"adif_field"`
	ReasonCode    *string            `json:"reason_code"`
	ReasonDetail  string             `json:"reason_detail"`
	RawFragment   *string            `json:"raw_fragment"`
	RawRecordHash *string            `json:"raw_record_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InviteKey struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	CreatedBy int64              `json:"created_by"`
	UsedBy    *int64             `json:"used_by"`
	MaxUses   int32              `json:"max_uses"`
	UsesCount int32              `json:"uses_count"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Groups QSOs under a callsign/station/activity.
type Logbook struct {
	ID                int64          `json:"id"`
	Uuid              uuid.UUID      `json:"uuid"`
	UserID            int64          `json:"user_id"`
	Name              string         `json:"name"`
	Callsign          *string        `json:"callsign"`
	Description       *string        `json:"description"`
	StationLocationID *int64         `json:"station_location_id"`
	GridSquare        *string        `json:"grid_square"`
	DefaultPowerWatts pgtype.Numeric `json:"default_power_watts"`
	LogbookType       string         `json:"logbook_type"`
	// Time window (seconds) for duplicate QSO detection. FT8/FT4: use 30s. Configurable per logbook.
	DedupWindowSeconds int32              `json:"dedup_window_seconds"`
	IsDefault          bool               `json:"is_default"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// One row per LoTW upload attempt. Tracks QSOs included, ARRL response, and retry state.
type LotwSyncJob struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Status       string             `json:"status"`
	QsoCount     int32              `json:"qso_count"`
	QsoIds       []byte             `json:"qso_ids"`
	Tq8SizeBytes *int32             `json:"tq8_size_bytes"`
	ArrlResponse *string            `json:"arrl_response"`
	ErrorMessage *string            `json:"error_message"`
	RetryCount   int16              `json:"retry_count"`
	MaxRetries   int16              `json:"max_retries"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

// Per-user LoTW sync preferences and aggregate state. One row per user.
type LotwSyncStatus struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	HasCert          bool               `json:"has_cert"`
	AutoSyncPrompt   bool               `json:"auto_sync_prompt"`
	LastSyncAt       pgtype.Timestamptz `json:"last_sync_at"`
	LastPullAt       pgtype.Timestamptz `json:"last_pull_at"`
	LastSyncQsoCount *int32             `json:"last_sync_qso_count"`
	LastSyncResult   *string            `json:"last_sync_result"`
	LastSyncError    *string            `json:"last_sync_error"`
	TotalQsosSynced  int32              `json:"total_qsos_synced"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Mode definitions and ADIF canonical export mapping. adif_mode/adif_submode distinguish canonical export values from tolerated import or UI aliases.
type Mode struct {
	Name        string   `json:"name"`
	Category    *string  `json:"category"`
	AdifMode    *string  `json:"adif_mode"`
	AdifSubmode *string  `json:"adif_submode"`
	Submodes    []string `json:"submodes"`
	// TRUE for analog modes (SSB, FM, AM, CW). FALSE for digital/image/data modes.
	IsAnalog bool `json:"is_analog"`
	// TRUE for modes shown in default/quick-pick UI lists. FALSE for less-common modes.
	IsPopular bool `json:"is_popular"`
	// Display sort order. Lower values appear first in mode pickers.
	SortOrder int32 `json:"sort_order"`
}

type Notification struct {
	ID     int64     `json:"id"`
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
	// Notification category. Product-facing types: import_complete, import_failed, sync_complete, qsl_confirmed, system_announcement, spot_alert. Legacy values retained for compatibility.
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	QsoID     *int64             `json:"qso_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Operator identity table (person-level identity). Distinct from callsigns.
type Operator struct {
	ID               int64              `json:"id"`
	Uuid             uuid.UUID          `json:"uuid"`
	UserID           int64              `json:"user_id"`
	LinkedUserID     *int64             `json:"linked_user_id"`
	OperatorCallsign *string            `json:"operator_callsign"`
	DisplayName      string             `json:"display_name"`
	IsOwner          bool               `json:"is_owner"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OperatorProfile struct {
	ID                 int64              `json:"id"`
	Callsign           string             `json:"callsign"`
	UserID             *int64             `json:"user_id"`
	DisplayName        *string            `json:"display_name"`
	Bio                *string            `json:"bio"`
	AvatarUrl          *string            `json:"avatar_url"`
	Website            *string            `json:"website"`
	QrzPage            *string            `json:"qrz_page"`
	StationDescription *string            `json:"station_description"`
	Antennas           []string           `json:"antennas"`
	Rigs               []string           `json:"rigs"`
	GridSquare         *string            `json:"grid_square"`
	QslVia             *string            `json:"qsl_via"`
	QslMessage         *string            `json:"qsl_message"`
	Twitter            *string            `json:"twitter"`
	Mastodon           *string            `json:"mastodon"`
	Youtube            *string            `json:"youtube"`
	TotalQsos          int32              `json:"total_qsos"`
	UniqueDxcc         int32              `json:"unique_dxcc"`
	UniqueGrids        int32              `json:"unique_grids"`
	MemberSince        pgtype.Timestamptz `json:"member_since"`
	LastActive         pgtype.Timestamptz `json:"last_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Identity verification records for operators per callsign.
type OperatorVerification struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	Callsign         string             `json:"callsign"`
	Method           string             `json:"method"`
	Status           string             `json:"status"`
	VerificationCode *string            `json:"verification_code"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	VouchedBy        *int64             `json:"vouched_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Paper QSL lifecycle container. Tracks bureau/direct/manager batches from draft → printed → sent → received/closed.
type PaperQslBatch struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	UserID            int64              `json:"user_id"`
	Direction         string             `json:"direction"`
	RouteType         string             `json:"route_type"`
	StationCallsignID *int64             `json:"station_callsign_id"`
	OperatorID        *int64             `json:"operator_id"`
	Label             *string            `json:"label"`
	Status            string             `json:"status"`
	MailedOn          pgtype.Date        `json:"mailed_on"`
	ReceivedOn        pgtype.Date        `json:"received_on"`
	ExpectedReplyBy   pgtype.Date        `json:"expected_reply_by"`
	PostageCents      *int32             `json:"postage_cents"`
	TrackingReference *string            `json:"tracking_reference"`
	Notes             *string            `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Per-QSO paper QSL workflow state. Has scope enforcement trigger to prevent cross-tenant FK bypass.
type PaperQslBatchItem struct {
	ID             int64              `json:"id"`
	BatchID        int64              `json:"batch_id"`
	QsoID          int64              `json:"qso_id"`
	WorkedCallsign string             `json:"worked_callsign"`
	CardStatus     string             `json:"card_status"`
	SentOn         pgtype.Date        `json:"sent_on"`
	ReceivedOn     pgtype.Date        `json:"received_on"`
	QslRouteID     *int64             `json:"qsl_route_id"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PotaPark struct {
	ParkRef       string             `json:"park_ref"`
	Name          string             `json:"name"`
	Country       string             `json:"country"`
	StateProvince *string            `json:"state_province"`
	Latitude      pgtype.Numeric     `json:"latitude"`
	Longitude     pgtype.Numeric     `json:"longitude"`
	Location      interface{}        `json:"location"`
	ParkType      *string            `json:"park_type"`
	Active        bool               `json:"active"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Reception reports fetched from pskreporter.info. One row per reception event per user. Pruned by background worker after 30 days.
type PskReceptionReport struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	SenderCallsign   string             `json:"sender_callsign"`
	ReceiverCallsign string             `json:"receiver_callsign"`
	FrequencyKhz     pgtype.Numeric     `json:"frequency_khz"`
	Mode             *string            `json:"mode"`
	Snr              *int16             `json:"snr"`
	Grid             *string            `json:"grid"`
	SpottedAt        pgtype.Timestamptz `json:"spotted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Paper QSL routing history. Captures manager and bureau changes over time.
type QslRoute struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	WorkedCallsign  string             `json:"worked_callsign"`
	RouteType       string             `json:"route_type"`
	ManagerCallsign *string            `json:"manager_callsign"`
	BureauName      *string            `json:"bureau_name"`
	ValidFrom       pgtype.Date        `json:"valid_from"`
	ValidTo         pgtype.Date        `json:"valid_to"`
	Source          string             `json:"source"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Core QSO log table. One row = one radio contact. Core ADIF fields typed; uncommon fields in extra JSONB.
type Qso struct {
	ID                int64       `json:"id"`
	Uuid              uuid.UUID   `json:"uuid"`
	ClientUuid        pgtype.UUID `json:"client_uuid"`
	LogbookID         int64       `json:"logbook_id"`
	StationCallsignID *int64      `json:"station_callsign_id"`
	OperatorID        *int64      `json:"operator_id"`
	// User who created this QSO. Contributors can only edit/delete their own QSOs.
	CreatedByUserID *int64 `json:"created_by_user_id"`
	// Optional FK to activation session. Used when QSOs are logged inside POTA/SOTA activation workflows.
	ActivationID *int64             `json:"activation_id"`
	Callsign     string             `json:"callsign"`
	Name         *string            `json:"name"`
	Qth          *string            `json:"qth"`
	Band         string             `json:"band"`
	Mode         string             `json:"mode"`
	Submode      *string            `json:"submode"`
	FrequencyHz  *int64             `json:"frequency_hz"`
	FreqRxHz     *int64             `json:"freq_rx_hz"`
	DatetimeOn   pgtype.Timestamptz `json:"datetime_on"`
	DatetimeOff  pgtype.Timestamptz `json:"datetime_off"`
	// How timestamp was derived at import: utc, local_converted, or assumed_utc.
	TimeSource            string         `json:"time_source"`
	SourceTimezone        *string        `json:"source_timezone"`
	RstSent               *string        `json:"rst_sent"`
	RstRcvd               *string        `json:"rst_rcvd"`
	TxPower               pgtype.Numeric `json:"tx_power"`
	RxPwr                 pgtype.Numeric `json:"rx_pwr"`
	MyAntenna             *string        `json:"my_antenna"`
	MyRig                 *string        `json:"my_rig"`
	Gridsquare            *string        `json:"gridsquare"`
	Dxcc                  *int32         `json:"dxcc"`
	Country               *string        `json:"country"`
	State                 *string        `json:"state"`
	County                *string        `json:"county"`
	CqZone                *int16         `json:"cq_zone"`
	ItuZone               *int16         `json:"itu_zone"`
	Continent             *string        `json:"continent"`
	MyGridsquare          *string        `json:"my_gridsquare"`
	MyCity                *string        `json:"my_city"`
	MyState               *string        `json:"my_state"`
	MyCountry             *string        `json:"my_country"`
	MyDxcc                *int32         `json:"my_dxcc"`
	Sfi                   *int16         `json:"sfi"`
	AIndex                *int16         `json:"a_index"`
	KIndex                *int16         `json:"k_index"`
	Operator              *string        `json:"operator"`
	StationCallsign       *string        `json:"station_callsign"`
	ContestSessionID      *int64         `json:"contest_session_id"`
	ContestID             *string        `json:"contest_id"`
	Srx                   *string        `json:"srx"`
	Stx                   *string        `json:"stx"`
	SrxString             *string        `json:"srx_string"`
	StxString             *string        `json:"stx_string"`
	SatName               *string        `json:"sat_name"`
	SatMode               *string        `json:"sat_mode"`
	PropMode              *string        `json:"prop_mode"`
	SotaRef               *string        `json:"sota_ref"`
	MySotaRef             *string        `json:"my_sota_ref"`
	PotaRefs              []string       `json:"pota_refs"`
	MyPotaRefs            []string       `json:"my_pota_refs"`
	WwffRef               *string        `json:"wwff_ref"`
	MyWwffRef             *string        `json:"my_wwff_ref"`
	Iota                  *string        `json:"iota"`
	Sig                   *string        `json:"sig"`
	SigInfo               *string        `json:"sig_info"`
	QslSent               *string        `json:"qsl_sent"`
	QslSentDate           pgtype.Date    `json:"qsl_sent_date"`
	QslRcvd               *string        `json:"qsl_rcvd"`
	QslRcvdDate           pgtype.Date    `json:"qsl_rcvd_date"`
	QslVia                *string        `json:"qsl_via"`
	LotwQslSent           *string        `json:"lotw_qsl_sent"`
	LotwQslSentDate       pgtype.Date    `json:"lotw_qsl_sent_date"`
	LotwQslRcvd           *string        `json:"lotw_qsl_rcvd"`
	LotwQslRcvdDate       pgtype.Date    `json:"lotw_qsl_rcvd_date"`
	EqslQslSent           *string        `json:"eqsl_qsl_sent"`
	EqslQslSentDate       pgtype.Date    `json:"eqsl_qsl_sent_date"`
	EqslQslRcvd           *string        `json:"eqsl_qsl_rcvd"`
	EqslQslRcvdDate       pgtype.Date    `json:"eqsl_qsl_rcvd_date"`
	QrzQslRcvd            *string        `json:"qrz_qsl_rcvd"`
	QrzQslRcvdDate        pgtype.Date    `json:"qrz_qsl_rcvd_date"`
	ClublogQslRcvd        *string        `json:"clublog_qsl_rcvd"`
	ClublogQslRcvdDate    pgtype.Date    `json:"clublog_qsl_rcvd_date"`
	LotwConfirmedCallsign *string        `json:"lotw_confirmed_callsign"`
	Comment               *string        `json:"comment"`
	Notes                 *string        `json:"notes"`
	// JSONB store for ADIF fields not mapped to typed columns. Keys use original ADIF field names (uppercase).
	Extra         []byte         `json:"extra"`
	MyLocation    interface{}    `json:"my_location"`
	TheirLocation interface{}    `json:"their_location"`
	DistanceKm    pgtype.Numeric `json:"distance_km"`
	// Timestamp when this QSO was last successfully submitted to ARRL LoTW.
	LotwSentAt pgtype.Timestamptz `json:"lotw_sent_at"`
	Source     *string            `json:"source"`
	SourceID   *string            `json:"source_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	// The lotw_sync_jobs row that last uploaded this QSO to LoTW.
	LotwSyncJobID *int64 `json:"lotw_sync_job_id"`
}

// Links two QSO entries from different users confirming the same contact.
type QsoConfirmation struct {
	ID                int64              `json:"id"`
	QsoID             int64              `json:"qso_id"`
	MatchedQsoID      *int64             `json:"matched_qso_id"`
	OurCallsign       string             `json:"our_callsign"`
	TheirCallsign     string             `json:"their_callsign"`
	Band              string             `json:"band"`
	Mode              string             `json:"mode"`
	QsoDate           pgtype.Date        `json:"qso_date"`
	QsoTime           pgtype.Time        `json:"qso_time"`
	Status            string             `json:"status"`
	OurVerification   string             `json:"our_verification"`
	TheirVerification string             `json:"their_verification"`
	LotwConfirmed     *bool              `json:"lotw_confirmed"`
	LotwConfirmedAt   pgtype.Timestamptz `json:"lotw_confirmed_at"`
	EqslConfirmed     *bool              `json:"eqsl_confirmed"`
	EqslConfirmedAt   pgtype.Timestamptz `json:"eqsl_confirmed_at"`
	QrzConfirmed      *bool              `json:"qrz_confirmed"`
	QrzConfirmedAt    pgtype.Timestamptz `json:"qrz_confirmed_at"`
	RlConfirmed       *bool              `json:"rl_confirmed"`
	RlConfirmedAt     pgtype.Timestamptz `json:"rl_confirmed_at"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	EqslAg            *bool              `json:"eqsl_ag"`
}

type SotaSummit struct {
	SummitRef   string         `json:"summit_ref"`
	Name        string         `json:"name"`
	Association string         `json:"association"`
	Region      string         `json:"region"`
	ElevationM  *int32         `json:"elevation_m"`
	Points      *int16         `json:"points"`
	BonusPoints int16          `json:"bonus_points"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Longitude   pgtype.Numeric `json:"longitude"`
	Location    interface{}    `json:"location"`
	GridSquare  *string        `json:"grid_square"`
	ValidFrom   pgtype.Date    `json:"valid_from"`
	ValidTo     pgtype.Date    `json:"valid_to"`
	Active      bool           `json:"active"`
}

// Active POTA/SOTA spots pulled from upstream spot feeds. Old rows are pruned after 24h by background worker.
type Spot struct {
	ID           int64              `json:"id"`
	Source       string             `json:"source"`
	Callsign     string             `json:"callsign"`
	Reference    string             `json:"reference"`
	FrequencyKhz pgtype.Numeric     `json:"frequency_khz"`
	Band         *string            `json:"band"`
	Mode         *string            `json:"mode"`
	SpottedAt    pgtype.Timestamptz `json:"spotted_at"`
	RawPayload   []byte             `json:"raw_payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Per-user spot alert settings. cooldown_minutes throttles repeated alerts for a watch rule.
type SpotNotificationPreference struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Enabled         bool               `json:"enabled"`
	CooldownMinutes int32              `json:"cooldown_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Per-user spot alert watch list. Matching spots generate in-app notifications via SpotPoller worker.
type SpotWatchRule struct {
	ID             int64              `json:"id"`
	Uuid           uuid.UUID          `json:"uuid"`
	UserID         int64              `json:"user_id"`
	Source         string             `json:"source"`
	Reference      string             `json:"reference"`
	Mode           *string            `json:"mode"`
	Band           *string            `json:"band"`
	Enabled        bool               `json:"enabled"`
	LastNotifiedAt pgtype.Timestamptz `json:"last_notified_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Station callsign identity. Club calls, special event calls, and personal calls all live here.
type StationCallsign struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	UserID       int64              `json:"user_id"`
	Callsign     string             `json:"callsign"`
	CallsignType string             `json:"callsign_type"`
	Description  *string            `json:"description"`
	ValidFrom    pgtype.Date        `json:"valid_from"`
	ValidTo      pgtype.Date        `json:"valid_to"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Authorization and attribution mapping between callsigns and operators.
type StationCallsignOperator struct {
	ID                int64              `json:"id"`
	StationCallsignID int64              `json:"station_callsign_id"`
	OperatorID        int64              `json:"operator_id"`
	Role              string             `json:"role"`
	ValidFrom         pgtype.Timestamptz `json:"valid_from"`
	ValidTo           pgtype.Timestamptz `json:"valid_to"`
	IsDefault         bool               `json:"is_default"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// tQSL station locations. Not the same as a callsign — one callsign can have many locations.
type StationLocation struct {
	ID         int64          `json:"id"`
	Uuid       uuid.UUID      `json:"uuid"`
	UserID     int64          `json:"user_id"`
	Name       string         `json:"name"`
	Callsign   string         `json:"callsign"`
	GridSquare string         `json:"grid_square"`
	DxccEntity *int32         `json:"dxcc_entity"`
	State      *string        `json:"state"`
	County     *string        `json:"county"`
	City       *string        `json:"city"`
	Country    *string        `json:"country"`
	Latitude   pgtype.Numeric `json:"latitude"`
	Longitude  pgtype.Numeric `json:"longitude"`
	Location   interface{}    `json:"location"`
	// Exact string used as the "Station Location" in tQSL. Mismatch causes LoTW rejection.
	LotwLocationName *string `json:"lotw_location_name"`
	// Date the tQSL certificate for this location expires. Notification system surfaces warnings at 60, 30, and 7 days before expiry.
	LotwCertExpiry pgtype.Date        `json:"lotw_cert_expiry"`
	IsDefault      bool               `json:"is_default"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SyncCircuitState struct {
	Service             string             `json:"service"`
	State               string             `json:"state"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	OpenedAt            pgtype.Timestamptz `json:"opened_at"`
	HalfOpenInFlight    bool               `json:"half_open_in_flight"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	LastError           *string            `json:"last_error"`
}

type SyncConflict struct {
	ID                int64              `json:"id"`
	QsoID             int64              `json:"qso_id"`
	ServiceA          string             `json:"service_a"`
	ServiceB          string             `json:"service_b"`
	FieldConflicts    []byte             `json:"field_conflicts"`
	Status            string             `json:"status"`
	Resolution        []byte             `json:"resolution"`
	ResolvedByService *string            `json:"resolved_by_service"`
	ResolvedAt        pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type SyncRateLimitWindow struct {
	Service     string             `json:"service"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Count       int32              `json:"count"`
}

// Per-QSO sync state for each external service. ON DELETE CASCADE cleans up rows when QSO is deleted.
type SyncStatus struct {
	ID           int64              `json:"id"`
	QsoID        int64              `json:"qso_id"`
	Service      string             `json:"service"`
	Status       string             `json:"status"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	RemoteID     *string            `json:"remote_id"`
	ErrorMessage *string            `json:"error_message"`
	RetryCount   int16              `json:"retry_count"`
	// When to retry. Worker sets: NOW() + (2^retry_count * base_interval) + random_jitter to prevent thundering herd.
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	LastErrorCode *string            `json:"last_error_code"`
	Extra         []byte             `json:"extra"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Server-level operational metadata. Not tenant-scoped. Used for master key generation timestamps and similar self-hosted metadata.
type SystemSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// One row per registered RadioLedger account. BIGSERIAL id is for internal joins only — always use uuid in API responses and URLs.
type User struct {
	ID int64 `json:"id"`
	// External-facing stable identifier. Use in all API responses and URLs. Never expose id (BIGSERIAL) externally.
	Uuid                       uuid.UUID          `json:"uuid"`
	Email                      string             `json:"email"`
	PasswordHash               *string            `json:"password_hash"`
	EmailVerifiedAt            pgtype.Timestamptz `json:"email_verified_at"`
	EmailVerificationTokenHash *string            `json:"email_verification_token_hash"`
	// Zitadel user subject claim (sub). Set on first Zitadel OIDC authentication. NULL for dev-mode users and pre-Zitadel accounts.
	ZitadelID *string `json:"zitadel_id"`
	// Primary callsign. Always stored uppercase.
	Callsign                   *string            `json:"callsign"`
	CallsignVerifiedAt         pgtype.Timestamptz `json:"callsign_verified_at"`
	CallsignVerificationSource *string            `json:"callsign_verification_source"`
	DisplayName                *string            `json:"display_name"`
	GridSquare                 *string            `json:"grid_square"`
	// Default transmit power in watts. Column name is explicit to prevent confusion with dBm.
	DefaultPowerWatts     pgtype.Numeric     `json:"default_power_watts"`
	OnboardingComplete    bool               `json:"onboarding_complete"`
	Timezone              string             `json:"timezone"`
	SubscriptionTier      string             `json:"subscription_tier"`
	SubscriptionExpiresAt pgtype.Timestamptz `json:"subscription_expires_at"`
	LastLoginAt           pgtype.Timestamptz `json:"last_login_at"`
	LastAutoSyncAt        pgtype.Timestamptz `json:"last_auto_sync_at"`
	// User-scoped UI and logging preferences JSONB payload. Expected keys include timezone, default_band, default_mode, default_power, ui_theme, dedup_window, desktop_udp_port, and desktop_rig_port.
	Preferences []byte             `json:"preferences"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	// PostGIS Point (WGS-84) derived from grid_square via trigger.
	Location  interface{}        `json:"location"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// All callsigns associated with a user, current and historical.
type UserCallsign struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	UserID       int64              `json:"user_id"`
	Callsign     string             `json:"callsign"`
	LicenseClass *string            `json:"license_class"`
	Country      *string            `json:"country"`
	DxccEntity   *int32             `json:"dxcc_entity"`
	IsPrimary    bool               `json:"is_primary"`
	ValidFrom    pgtype.Date        `json:"valid_from"`
	ValidTo      pgtype.Date        `json:"valid_to"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Per-logbook membership and RBAC role assignments.
type UserRole struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	LogbookID int64     `json:"logbook_id"`
	UserID    int64     `json:"user_id"`
	// Role for this user within this specific logbook. Valid values: owner, admin, operator, contributor, viewer.
	Role string `json:"role"`
	// User who granted this membership/role. NULL for bootstrapped owner rows.
	InvitedBy *int64             `json:"invited_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Encrypted external service credentials. credentials is AES-256-GCM ciphertext; plaintext never enters the database.
type UserServiceCredential struct {
	ID             int64  `json:"id"`
	UserID         int64  `json:"user_id"`
	Service        string `json:"service"`
	CredentialType string `json:"credential_type"`
	Credentials    []byte `json:"credentials"`
	// Master key derivation version. On rotation: increment app version, re-encrypt rows in background, update this field.
	KeyVersion     int32              `json:"key_version"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ZipCentroid struct {
	ZipCode   string             `json:"zip_code"`
	Latitude  float64            `json:"latitude"`
	Longitude float64            `json:"longitude"`
	City      *string            `json:"city"`
	State     *string            `json:"state"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
