// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint AS unread_count
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
    user_id,
    type,
    payload,
    qso_id
)
VALUES (
    $1::bigint,
    $2::text,
    COALESCE($3::jsonb, '{}'::jsonb),
    $4::bigint
)
RETURNING id, uuid, user_id, type, payload, qso_id, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  int64  `json:"user_id"`
	Type    string `json:"type"`
	Payload []byte `json:"payload"`
	QsoID   *int64 `json:"qso_id"`
}

// Queries for notifications feed.
//
// Notification payloads are JSONB so feature-specific data can evolve without
// schema churn, while type remains strongly constrained in the database.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Payload,
		arg.QsoID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.QsoID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkerNotification = `-- name: CreateWorkerNotification :one
INSERT INTO notifications (
    user_id,
    type,
    payload
)
VALUES (
    $1::bigint,
    $2::text,
    $3::jsonb
)
RETURNING id, uuid, user_id, type, payload, qso_id, read_at, created_at
`

type CreateWorkerNotificationParams struct {
	UserID  int64  `json:"user_id"`
	Type    string `json:"type"`
	Payload []byte `json:"payload"`
}

// Creates a notification as the worker role (no user RLS context needed).
// Used by background jobs to create notifications for any user.
// The caller is responsible for SET LOCAL ROLE radioledger_worker before executing.
func (q *Queries) CreateWorkerNotification(ctx context.Context, arg CreateWorkerNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createWorkerNotification, arg.UserID, arg.Type, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.QsoID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications
WHERE uuid = $1
  AND user_id = $2
`

type DeleteNotificationParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, arg.Uuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasRecentCertExpiryNotification = `-- name: HasRecentCertExpiryNotification :one
SELECT COUNT(*)::bigint
FROM notifications
WHERE user_id = $1
  AND type = 'cert_expiry'
  AND payload->>'callsign' = $2::text
  AND (payload->>'expires_at')::date = $3::date
  AND payload->>'threshold_days' = $4::text
  AND created_at > NOW() - INTERVAL '25 days'
`

type HasRecentCertExpiryNotificationParams struct {
	UserID        int64       `json:"user_id"`
	Callsign      string      `json:"callsign"`
	ExpiresAt     pgtype.Date `json:"expires_at"`
	ThresholdDays string      `json:"threshold_days"`
}

// Returns the count of cert_expiry notifications already sent for a specific
// (user, callsign, expiry date, threshold) combination within the past 25 days.
// Used by CertExpiryCheckJob to avoid sending duplicate alerts.
// Runs as radioledger_worker role (see migration 013 for the SELECT policy).
func (q *Queries) HasRecentCertExpiryNotification(ctx context.Context, arg HasRecentCertExpiryNotificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, hasRecentCertExpiryNotification,
		arg.UserID,
		arg.Callsign,
		arg.ExpiresAt,
		arg.ThresholdDays,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, uuid, user_id, type, payload, qso_id, read_at, created_at
FROM notifications
WHERE user_id = $1
ORDER BY (read_at IS NULL) DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.QsoID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, uuid, user_id, type, payload, qso_id, read_at, created_at
FROM notifications
WHERE user_id = $1
  AND read_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnreadNotificationsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Returns only unread notifications for a user, newest first.
// Used by GET /v1/notifications?unread=true.
func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.QsoID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = NOW()
WHERE user_id = $1
  AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, NOW())
WHERE uuid = $1
  AND user_id = $2
`

type MarkNotificationReadParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.Uuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
