// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT
    id,
    uuid,
    display_name,
    timezone,
    grid_square,
    default_power_watts,
    preferences,
    updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserPreferencesRow struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	DisplayName       *string            `json:"display_name"`
	Timezone          string             `json:"timezone"`
	GridSquare        *string            `json:"grid_square"`
	DefaultPowerWatts pgtype.Numeric     `json:"default_power_watts"`
	Preferences       []byte             `json:"preferences"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserPreferences(ctx context.Context, id int64) (GetUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, id)
	var i GetUserPreferencesRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Timezone,
		&i.GridSquare,
		&i.DefaultPowerWatts,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUserByID = `-- name: SoftDeleteUserByID :execrows
UPDATE users
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUserByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUserByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users
SET
    display_name = $1,
    timezone = COALESCE($2::text, timezone),
    grid_square = CASE
        WHEN $3::text IS NULL THEN grid_square
        ELSE UPPER($3::text)
    END,
    default_power_watts = COALESCE($4::numeric, default_power_watts),
    preferences = COALESCE($5::jsonb, preferences),
    updated_at = NOW()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING
    id,
    uuid,
    display_name,
    timezone,
    grid_square,
    default_power_watts,
    preferences,
    updated_at
`

type UpdateUserPreferencesParams struct {
	DisplayName       *string        `json:"display_name"`
	Timezone          *string        `json:"timezone"`
	GridSquare        *string        `json:"grid_square"`
	DefaultPowerWatts pgtype.Numeric `json:"default_power_watts"`
	Preferences       []byte         `json:"preferences"`
	ID                int64          `json:"id"`
}

type UpdateUserPreferencesRow struct {
	ID                int64              `json:"id"`
	Uuid              uuid.UUID          `json:"uuid"`
	DisplayName       *string            `json:"display_name"`
	Timezone          string             `json:"timezone"`
	GridSquare        *string            `json:"grid_square"`
	DefaultPowerWatts pgtype.Numeric     `json:"default_power_watts"`
	Preferences       []byte             `json:"preferences"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.DisplayName,
		arg.Timezone,
		arg.GridSquare,
		arg.DefaultPowerWatts,
		arg.Preferences,
		arg.ID,
	)
	var i UpdateUserPreferencesRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.DisplayName,
		&i.Timezone,
		&i.GridSquare,
		&i.DefaultPowerWatts,
		&i.Preferences,
		&i.UpdatedAt,
	)
	return i, err
}
