// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pskreporter.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePSKReportsOlderThan = `-- name: DeletePSKReportsOlderThan :execrows
DELETE FROM psk_reception_reports
WHERE spotted_at < $1::timestamptz
`

// Prune old PSK reception reports. Called periodically by the poller worker.
func (q *Queries) DeletePSKReportsOlderThan(ctx context.Context, cutoffAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deletePSKReportsOlderThan, cutoffAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPSKReceptionReports = `-- name: ListPSKReceptionReports :many
SELECT
    id,
    user_id,
    sender_callsign,
    receiver_callsign,
    frequency_khz,
    mode,
    snr,
    grid,
    spotted_at,
    created_at
FROM psk_reception_reports
WHERE user_id = $1::bigint
  AND (
      $2::timestamptz IS NULL
      OR spotted_at < $2::timestamptz
      OR (spotted_at = $2::timestamptz AND id < $3::bigint)
  )
ORDER BY spotted_at DESC, id DESC
LIMIT $4::int
`

type ListPSKReceptionReportsParams struct {
	UserID          int64              `json:"user_id"`
	CursorSpottedAt pgtype.Timestamptz `json:"cursor_spotted_at"`
	CursorID        *int64             `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

// Paginated list of PSK reception reports for the authenticated user.
// Cursor-based pagination using (spotted_at DESC, id DESC).
func (q *Queries) ListPSKReceptionReports(ctx context.Context, arg ListPSKReceptionReportsParams) ([]PskReceptionReport, error) {
	rows, err := q.db.Query(ctx, listPSKReceptionReports,
		arg.UserID,
		arg.CursorSpottedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PskReceptionReport{}
	for rows.Next() {
		var i PskReceptionReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SenderCallsign,
			&i.ReceiverCallsign,
			&i.FrequencyKhz,
			&i.Mode,
			&i.Snr,
			&i.Grid,
			&i.SpottedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPSKReportsByCallsignAndWindow = `-- name: ListPSKReportsByCallsignAndWindow :many
SELECT
    id,
    user_id,
    sender_callsign,
    receiver_callsign,
    frequency_khz,
    mode,
    snr,
    grid,
    spotted_at,
    created_at
FROM psk_reception_reports
WHERE user_id = $1::bigint
  AND UPPER(sender_callsign) = UPPER($2::text)
  AND spotted_at >= $3::timestamptz
  AND spotted_at <= $4::timestamptz
ORDER BY spotted_at DESC, id DESC
LIMIT $5::int
`

type ListPSKReportsByCallsignAndWindowParams struct {
	UserID         int64              `json:"user_id"`
	SenderCallsign string             `json:"sender_callsign"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	WindowEnd      pgtype.Timestamptz `json:"window_end"`
	LimitCount     int32              `json:"limit_count"`
}

// Find PSK reception reports that match a specific QSO by sender callsign
// and time window. Used by the /match/:qso_id endpoint.
func (q *Queries) ListPSKReportsByCallsignAndWindow(ctx context.Context, arg ListPSKReportsByCallsignAndWindowParams) ([]PskReceptionReport, error) {
	rows, err := q.db.Query(ctx, listPSKReportsByCallsignAndWindow,
		arg.UserID,
		arg.SenderCallsign,
		arg.WindowStart,
		arg.WindowEnd,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PskReceptionReport{}
	for rows.Next() {
		var i PskReceptionReport
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SenderCallsign,
			&i.ReceiverCallsign,
			&i.FrequencyKhz,
			&i.Mode,
			&i.Snr,
			&i.Grid,
			&i.SpottedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithCallsign = `-- name: ListUsersWithCallsign :many
SELECT
    id,
    callsign
FROM users
WHERE callsign IS NOT NULL
  AND callsign <> ''
  AND deleted_at IS NULL
`

type ListUsersWithCallsignRow struct {
	ID       int64   `json:"id"`
	Callsign *string `json:"callsign"`
}

// Return users who have a callsign configured. Used by the PSK Reporter poller
// to determine which callsigns to query.
func (q *Queries) ListUsersWithCallsign(ctx context.Context) ([]ListUsersWithCallsignRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithCallsign)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithCallsignRow{}
	for rows.Next() {
		var i ListUsersWithCallsignRow
		if err := rows.Scan(&i.ID, &i.Callsign); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPSKReceptionReport = `-- name: UpsertPSKReceptionReport :exec
INSERT INTO psk_reception_reports (
    user_id,
    sender_callsign,
    receiver_callsign,
    frequency_khz,
    mode,
    snr,
    grid,
    spotted_at
)
VALUES (
    $1::bigint,
    UPPER($2::text),
    UPPER($3::text),
    $4::numeric,
    $5::text,
    $6::smallint,
    $7::text,
    $8::timestamptz
)
ON CONFLICT (user_id, sender_callsign, receiver_callsign, spotted_at)
DO NOTHING
`

type UpsertPSKReceptionReportParams struct {
	UserID           int64              `json:"user_id"`
	SenderCallsign   string             `json:"sender_callsign"`
	ReceiverCallsign string             `json:"receiver_callsign"`
	FrequencyKhz     pgtype.Numeric     `json:"frequency_khz"`
	Mode             *string            `json:"mode"`
	Snr              *int16             `json:"snr"`
	Grid             *string            `json:"grid"`
	SpottedAt        pgtype.Timestamptz `json:"spotted_at"`
}

// Insert a new PSK reception report, ignoring duplicates (same user, sender,
// receiver, spotted_at). Called by the PSK Reporter poller worker.
func (q *Queries) UpsertPSKReceptionReport(ctx context.Context, arg UpsertPSKReceptionReportParams) error {
	_, err := q.db.Exec(ctx, upsertPSKReceptionReport,
		arg.UserID,
		arg.SenderCallsign,
		arg.ReceiverCallsign,
		arg.FrequencyKhz,
		arg.Mode,
		arg.Snr,
		arg.Grid,
		arg.SpottedAt,
	)
	return err
}
