// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qsos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQSO = `-- name: CreateQSO :one
WITH target_logbook AS (
    SELECT l.id, l.uuid
    FROM logbooks l
    WHERE l.uuid = $18
      AND l.deleted_at IS NULL
)
INSERT INTO qsos (
    logbook_id,
    created_by_user_id,
    callsign,
    name,
    qth,
    band,
    mode,
    submode,
    frequency_hz,
    datetime_on,
    rst_sent,
    rst_rcvd,
    tx_power,
    gridsquare,
    my_gridsquare,
    dxcc,
    comment,
    notes
)
SELECT
    target_logbook.id,
    $1,
    UPPER($2::text),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    CASE
        WHEN $13::text IS NULL THEN NULL
        ELSE UPPER($13::text)
    END,
    CASE
        WHEN $14::text IS NULL THEN NULL
        ELSE UPPER($14::text)
    END,
    $15,
    $16,
    $17
FROM target_logbook
RETURNING
    id,
    uuid,
    callsign,
    name,
    qth,
    band,
    mode,
    submode,
    frequency_hz,
    datetime_on,
    rst_sent,
    rst_rcvd,
    tx_power,
    gridsquare,
    my_gridsquare,
    dxcc,
    comment,
    notes,
    created_at,
    updated_at
`

type CreateQSOParams struct {
	CreatedByUserID *int64             `json:"created_by_user_id"`
	Callsign        string             `json:"callsign"`
	Name            *string            `json:"name"`
	Qth             *string            `json:"qth"`
	Band            string             `json:"band"`
	Mode            string             `json:"mode"`
	Submode         *string            `json:"submode"`
	FrequencyHz     *int64             `json:"frequency_hz"`
	DatetimeOn      pgtype.Timestamptz `json:"datetime_on"`
	RstSent         *string            `json:"rst_sent"`
	RstRcvd         *string            `json:"rst_rcvd"`
	TxPower         pgtype.Numeric     `json:"tx_power"`
	Gridsquare      *string            `json:"gridsquare"`
	MyGridsquare    *string            `json:"my_gridsquare"`
	Dxcc            *int32             `json:"dxcc"`
	Comment         *string            `json:"comment"`
	Notes           *string            `json:"notes"`
	LogbookUuid     uuid.UUID          `json:"logbook_uuid"`
}

type CreateQSORow struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	Callsign     string             `json:"callsign"`
	Name         *string            `json:"name"`
	Qth          *string            `json:"qth"`
	Band         string             `json:"band"`
	Mode         string             `json:"mode"`
	Submode      *string            `json:"submode"`
	FrequencyHz  *int64             `json:"frequency_hz"`
	DatetimeOn   pgtype.Timestamptz `json:"datetime_on"`
	RstSent      *string            `json:"rst_sent"`
	RstRcvd      *string            `json:"rst_rcvd"`
	TxPower      pgtype.Numeric     `json:"tx_power"`
	Gridsquare   *string            `json:"gridsquare"`
	MyGridsquare *string            `json:"my_gridsquare"`
	Dxcc         *int32             `json:"dxcc"`
	Comment      *string            `json:"comment"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateQSO(ctx context.Context, arg CreateQSOParams) (CreateQSORow, error) {
	row := q.db.QueryRow(ctx, createQSO,
		arg.CreatedByUserID,
		arg.Callsign,
		arg.Name,
		arg.Qth,
		arg.Band,
		arg.Mode,
		arg.Submode,
		arg.FrequencyHz,
		arg.DatetimeOn,
		arg.RstSent,
		arg.RstRcvd,
		arg.TxPower,
		arg.Gridsquare,
		arg.MyGridsquare,
		arg.Dxcc,
		arg.Comment,
		arg.Notes,
		arg.LogbookUuid,
	)
	var i CreateQSORow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Callsign,
		&i.Name,
		&i.Qth,
		&i.Band,
		&i.Mode,
		&i.Submode,
		&i.FrequencyHz,
		&i.DatetimeOn,
		&i.RstSent,
		&i.RstRcvd,
		&i.TxPower,
		&i.Gridsquare,
		&i.MyGridsquare,
		&i.Dxcc,
		&i.Comment,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQSO = `-- name: DeleteQSO :exec
UPDATE qsos q
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE q.uuid = $1
  AND q.logbook_id = (
      SELECT l.id
      FROM logbooks l
      WHERE l.uuid = $2
        AND l.deleted_at IS NULL
  )
  AND q.deleted_at IS NULL
`

type DeleteQSOParams struct {
	QsoUuid     uuid.UUID `json:"qso_uuid"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

func (q *Queries) DeleteQSO(ctx context.Context, arg DeleteQSOParams) error {
	_, err := q.db.Exec(ctx, deleteQSO, arg.QsoUuid, arg.LogbookUuid)
	return err
}

const getQSOByUUID = `-- name: GetQSOByUUID :one
SELECT
    q.id,
    q.uuid,
    l.uuid AS logbook_uuid,
    q.created_by_user_id,
    q.callsign,
    q.name,
    q.qth,
    q.band,
    q.mode,
    q.submode,
    q.frequency_hz,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.tx_power,
    q.gridsquare,
    q.my_gridsquare,
    q.dxcc,
    q.country,
    q.cq_zone,
    q.itu_zone,
    q.continent,
    q.comment,
    q.notes,
    q.created_at,
    q.updated_at
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE q.uuid = $1
  AND l.uuid = $2
  AND l.deleted_at IS NULL
  AND q.deleted_at IS NULL
`

type GetQSOByUUIDParams struct {
	QsoUuid     uuid.UUID `json:"qso_uuid"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

type GetQSOByUUIDRow struct {
	ID              int64              `json:"id"`
	Uuid            uuid.UUID          `json:"uuid"`
	LogbookUuid     uuid.UUID          `json:"logbook_uuid"`
	CreatedByUserID *int64             `json:"created_by_user_id"`
	Callsign        string             `json:"callsign"`
	Name            *string            `json:"name"`
	Qth             *string            `json:"qth"`
	Band            string             `json:"band"`
	Mode            string             `json:"mode"`
	Submode         *string            `json:"submode"`
	FrequencyHz     *int64             `json:"frequency_hz"`
	DatetimeOn      pgtype.Timestamptz `json:"datetime_on"`
	RstSent         *string            `json:"rst_sent"`
	RstRcvd         *string            `json:"rst_rcvd"`
	TxPower         pgtype.Numeric     `json:"tx_power"`
	Gridsquare      *string            `json:"gridsquare"`
	MyGridsquare    *string            `json:"my_gridsquare"`
	Dxcc            *int32             `json:"dxcc"`
	Country         *string            `json:"country"`
	CqZone          *int16             `json:"cq_zone"`
	ItuZone         *int16             `json:"itu_zone"`
	Continent       *string            `json:"continent"`
	Comment         *string            `json:"comment"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetQSOByUUID(ctx context.Context, arg GetQSOByUUIDParams) (GetQSOByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getQSOByUUID, arg.QsoUuid, arg.LogbookUuid)
	var i GetQSOByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.LogbookUuid,
		&i.CreatedByUserID,
		&i.Callsign,
		&i.Name,
		&i.Qth,
		&i.Band,
		&i.Mode,
		&i.Submode,
		&i.FrequencyHz,
		&i.DatetimeOn,
		&i.RstSent,
		&i.RstRcvd,
		&i.TxPower,
		&i.Gridsquare,
		&i.MyGridsquare,
		&i.Dxcc,
		&i.Country,
		&i.CqZone,
		&i.ItuZone,
		&i.Continent,
		&i.Comment,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQSOCreatorByUUID = `-- name: GetQSOCreatorByUUID :one
SELECT
    q.created_by_user_id
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE q.uuid = $1
  AND l.uuid = $2
  AND l.deleted_at IS NULL
  AND q.deleted_at IS NULL
`

type GetQSOCreatorByUUIDParams struct {
	QsoUuid     uuid.UUID `json:"qso_uuid"`
	LogbookUuid uuid.UUID `json:"logbook_uuid"`
}

func (q *Queries) GetQSOCreatorByUUID(ctx context.Context, arg GetQSOCreatorByUUIDParams) (*int64, error) {
	row := q.db.QueryRow(ctx, getQSOCreatorByUUID, arg.QsoUuid, arg.LogbookUuid)
	var created_by_user_id *int64
	err := row.Scan(&created_by_user_id)
	return created_by_user_id, err
}

const getQSOForPSKMatch = `-- name: GetQSOForPSKMatch :one
SELECT
    q.id,
    q.uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE q.uuid = $1::uuid
  AND l.deleted_at IS NULL
  AND q.deleted_at IS NULL
LIMIT 1
`

type GetQSOForPSKMatchRow struct {
	ID         int64              `json:"id"`
	Uuid       uuid.UUID          `json:"uuid"`
	Callsign   string             `json:"callsign"`
	Band       string             `json:"band"`
	Mode       string             `json:"mode"`
	DatetimeOn pgtype.Timestamptz `json:"datetime_on"`
}

// Look up a QSO by UUID for PSK Reporter matching. Returns just the fields
// needed to match against reception reports. RLS ensures only the owner sees it.
func (q *Queries) GetQSOForPSKMatch(ctx context.Context, qsoUuid uuid.UUID) (GetQSOForPSKMatchRow, error) {
	row := q.db.QueryRow(ctx, getQSOForPSKMatch, qsoUuid)
	var i GetQSOForPSKMatchRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Callsign,
		&i.Band,
		&i.Mode,
		&i.DatetimeOn,
	)
	return i, err
}

const listQSOsByLogbook = `-- name: ListQSOsByLogbook :many
SELECT
    q.id,
    q.uuid,
    l.uuid AS logbook_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.name,
    q.qth,
    q.gridsquare,
    q.dxcc,
    q.country,
    q.cq_zone,
    q.itu_zone,
    q.continent,
    q.comment,
    q.notes,
    q.created_at,
    q.updated_at
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.uuid = $1
  AND l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND (
      $2::timestamptz IS NULL
      OR (q.datetime_on, q.id) < (
          $2::timestamptz,
          COALESCE($3::bigint, 9223372036854775807)
      )
  )
ORDER BY q.datetime_on DESC, q.id DESC
LIMIT LEAST($4::int, 100)
`

type ListQSOsByLogbookParams struct {
	LogbookUuid    uuid.UUID          `json:"logbook_uuid"`
	CursorDatetime pgtype.Timestamptz `json:"cursor_datetime"`
	CursorID       *int64             `json:"cursor_id"`
	PageSize       int32              `json:"page_size"`
}

type ListQSOsByLogbookRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	LogbookUuid uuid.UUID          `json:"logbook_uuid"`
	Callsign    string             `json:"callsign"`
	Band        string             `json:"band"`
	Mode        string             `json:"mode"`
	DatetimeOn  pgtype.Timestamptz `json:"datetime_on"`
	RstSent     *string            `json:"rst_sent"`
	RstRcvd     *string            `json:"rst_rcvd"`
	Name        *string            `json:"name"`
	Qth         *string            `json:"qth"`
	Gridsquare  *string            `json:"gridsquare"`
	Dxcc        *int32             `json:"dxcc"`
	Country     *string            `json:"country"`
	CqZone      *int16             `json:"cq_zone"`
	ItuZone     *int16             `json:"itu_zone"`
	Continent   *string            `json:"continent"`
	Comment     *string            `json:"comment"`
	Notes       *string            `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListQSOsByLogbook(ctx context.Context, arg ListQSOsByLogbookParams) ([]ListQSOsByLogbookRow, error) {
	rows, err := q.db.Query(ctx, listQSOsByLogbook,
		arg.LogbookUuid,
		arg.CursorDatetime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQSOsByLogbookRow{}
	for rows.Next() {
		var i ListQSOsByLogbookRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.LogbookUuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.DatetimeOn,
			&i.RstSent,
			&i.RstRcvd,
			&i.Name,
			&i.Qth,
			&i.Gridsquare,
			&i.Dxcc,
			&i.Country,
			&i.CqZone,
			&i.ItuZone,
			&i.Continent,
			&i.Comment,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchQSOs = `-- name: SearchQSOs :many
SELECT
    q.id,
    q.uuid,
    l.uuid AS logbook_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.name,
    q.qth,
    q.gridsquare,
    q.dxcc,
    q.country,
    q.cq_zone,
    q.itu_zone,
    q.continent,
    q.comment,
    q.notes,
    q.created_at,
    q.updated_at
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.uuid = $1
  AND l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND (
      $2::text IS NULL
      OR q.callsign ILIKE ('%' || $2::text || '%')
  )
  AND (
      $3::text IS NULL
      OR q.band = $3::text
  )
  AND (
      $4::text IS NULL
      OR q.mode = $4::text
  )
  AND (
      $5::timestamptz IS NULL
      OR q.datetime_on >= $5::timestamptz
  )
  AND (
      $6::timestamptz IS NULL
      OR q.datetime_on <= $6::timestamptz
  )
  AND (
      $7::integer IS NULL
      OR q.dxcc = $7::integer
  )
  AND (
      $8::text IS NULL
      OR q.gridsquare ILIKE (UPPER($8::text) || '%')
  )
  AND (
      $9::timestamptz IS NULL
      OR (q.datetime_on, q.id) < (
          $9::timestamptz,
          COALESCE($10::bigint, 9223372036854775807)
      )
  )
ORDER BY q.datetime_on DESC, q.id DESC
LIMIT LEAST($11::int, 100)
`

type SearchQSOsParams struct {
	LogbookUuid      uuid.UUID          `json:"logbook_uuid"`
	CallsignFilter   *string            `json:"callsign_filter"`
	BandFilter       *string            `json:"band_filter"`
	ModeFilter       *string            `json:"mode_filter"`
	DateFrom         pgtype.Timestamptz `json:"date_from"`
	DateTo           pgtype.Timestamptz `json:"date_to"`
	DxccFilter       *int32             `json:"dxcc_filter"`
	GridsquarePrefix *string            `json:"gridsquare_prefix"`
	CursorDatetime   pgtype.Timestamptz `json:"cursor_datetime"`
	CursorID         *int64             `json:"cursor_id"`
	PageSize         int32              `json:"page_size"`
}

type SearchQSOsRow struct {
	ID          int64              `json:"id"`
	Uuid        uuid.UUID          `json:"uuid"`
	LogbookUuid uuid.UUID          `json:"logbook_uuid"`
	Callsign    string             `json:"callsign"`
	Band        string             `json:"band"`
	Mode        string             `json:"mode"`
	DatetimeOn  pgtype.Timestamptz `json:"datetime_on"`
	RstSent     *string            `json:"rst_sent"`
	RstRcvd     *string            `json:"rst_rcvd"`
	Name        *string            `json:"name"`
	Qth         *string            `json:"qth"`
	Gridsquare  *string            `json:"gridsquare"`
	Dxcc        *int32             `json:"dxcc"`
	Country     *string            `json:"country"`
	CqZone      *int16             `json:"cq_zone"`
	ItuZone     *int16             `json:"itu_zone"`
	Continent   *string            `json:"continent"`
	Comment     *string            `json:"comment"`
	Notes       *string            `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchQSOs(ctx context.Context, arg SearchQSOsParams) ([]SearchQSOsRow, error) {
	rows, err := q.db.Query(ctx, searchQSOs,
		arg.LogbookUuid,
		arg.CallsignFilter,
		arg.BandFilter,
		arg.ModeFilter,
		arg.DateFrom,
		arg.DateTo,
		arg.DxccFilter,
		arg.GridsquarePrefix,
		arg.CursorDatetime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchQSOsRow{}
	for rows.Next() {
		var i SearchQSOsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.LogbookUuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.DatetimeOn,
			&i.RstSent,
			&i.RstRcvd,
			&i.Name,
			&i.Qth,
			&i.Gridsquare,
			&i.Dxcc,
			&i.Country,
			&i.CqZone,
			&i.ItuZone,
			&i.Continent,
			&i.Comment,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQSO = `-- name: UpdateQSO :one
WITH target_qso AS (
    SELECT q.id
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    WHERE q.uuid = $17
      AND l.uuid = $18
      AND l.deleted_at IS NULL
      AND q.deleted_at IS NULL
)
UPDATE qsos q
SET
    callsign = UPPER($1::text),
    name = COALESCE($2, q.name),
    qth = COALESCE($3, q.qth),
    band = $4,
    mode = $5,
    submode = COALESCE($6, q.submode),
    frequency_hz = COALESCE($7, q.frequency_hz),
    datetime_on = $8,
    rst_sent = COALESCE($9, q.rst_sent),
    rst_rcvd = COALESCE($10, q.rst_rcvd),
    tx_power = COALESCE($11, q.tx_power),
    gridsquare = CASE
        WHEN $12::text IS NULL THEN q.gridsquare
        ELSE UPPER($12::text)
    END,
    my_gridsquare = COALESCE(
        CASE
            WHEN $13::text IS NULL THEN NULL
            ELSE UPPER($13::text)
        END,
        q.my_gridsquare
    ),
    dxcc = $14,
    comment = COALESCE($15, q.comment),
    notes = COALESCE($16, q.notes),
    updated_at = NOW()
FROM target_qso
WHERE q.id = target_qso.id
RETURNING
    q.id,
    q.uuid,
    q.callsign,
    q.name,
    q.qth,
    q.band,
    q.mode,
    q.submode,
    q.frequency_hz,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.tx_power,
    q.gridsquare,
    q.my_gridsquare,
    q.dxcc,
    q.comment,
    q.notes,
    q.created_at,
    q.updated_at
`

type UpdateQSOParams struct {
	Callsign     string             `json:"callsign"`
	Name         *string            `json:"name"`
	Qth          *string            `json:"qth"`
	Band         string             `json:"band"`
	Mode         string             `json:"mode"`
	Submode      *string            `json:"submode"`
	FrequencyHz  *int64             `json:"frequency_hz"`
	DatetimeOn   pgtype.Timestamptz `json:"datetime_on"`
	RstSent      *string            `json:"rst_sent"`
	RstRcvd      *string            `json:"rst_rcvd"`
	TxPower      pgtype.Numeric     `json:"tx_power"`
	Gridsquare   *string            `json:"gridsquare"`
	MyGridsquare *string            `json:"my_gridsquare"`
	Dxcc         *int32             `json:"dxcc"`
	Comment      *string            `json:"comment"`
	Notes        *string            `json:"notes"`
	QsoUuid      uuid.UUID          `json:"qso_uuid"`
	LogbookUuid  uuid.UUID          `json:"logbook_uuid"`
}

type UpdateQSORow struct {
	ID           int64              `json:"id"`
	Uuid         uuid.UUID          `json:"uuid"`
	Callsign     string             `json:"callsign"`
	Name         *string            `json:"name"`
	Qth          *string            `json:"qth"`
	Band         string             `json:"band"`
	Mode         string             `json:"mode"`
	Submode      *string            `json:"submode"`
	FrequencyHz  *int64             `json:"frequency_hz"`
	DatetimeOn   pgtype.Timestamptz `json:"datetime_on"`
	RstSent      *string            `json:"rst_sent"`
	RstRcvd      *string            `json:"rst_rcvd"`
	TxPower      pgtype.Numeric     `json:"tx_power"`
	Gridsquare   *string            `json:"gridsquare"`
	MyGridsquare *string            `json:"my_gridsquare"`
	Dxcc         *int32             `json:"dxcc"`
	Comment      *string            `json:"comment"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateQSO(ctx context.Context, arg UpdateQSOParams) (UpdateQSORow, error) {
	row := q.db.QueryRow(ctx, updateQSO,
		arg.Callsign,
		arg.Name,
		arg.Qth,
		arg.Band,
		arg.Mode,
		arg.Submode,
		arg.FrequencyHz,
		arg.DatetimeOn,
		arg.RstSent,
		arg.RstRcvd,
		arg.TxPower,
		arg.Gridsquare,
		arg.MyGridsquare,
		arg.Dxcc,
		arg.Comment,
		arg.Notes,
		arg.QsoUuid,
		arg.LogbookUuid,
	)
	var i UpdateQSORow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Callsign,
		&i.Name,
		&i.Qth,
		&i.Band,
		&i.Mode,
		&i.Submode,
		&i.FrequencyHz,
		&i.DatetimeOn,
		&i.RstSent,
		&i.RstRcvd,
		&i.TxPower,
		&i.Gridsquare,
		&i.MyGridsquare,
		&i.Dxcc,
		&i.Comment,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
