// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Prefix search over cached callsigns for typeahead/autocomplete.
	// Returns the top 10 matches by callsign for the given prefix.
	// Only considers non-expired entries. Used by the QSO entry form.
	AutocompleteCallsigns(ctx context.Context, prefix interface{}) ([]AutocompleteCallsignsRow, error)
	// Returns the first non-dupe QSO for callsign+band in this contest session.
	// Uses idx_qsos_contest_dupe for <10ms response.
	CheckDupe(ctx context.Context, arg CheckDupeParams) (CheckDupeRow, error)
	// Marks an import job as complete or errored with final counters.
	CompleteImportJob(ctx context.Context, arg CompleteImportJobParams) error
	ConsumeInviteByCode(ctx context.Context, arg ConsumeInviteByCodeParams) (InviteKey, error)
	// Queries for invite_keys table.
	CountActiveInvitesByCreator(ctx context.Context, createdBy int64) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	// Queries for api_keys table.
	// API keys use a show-once pattern: the plaintext key is returned once at creation,
	// only the SHA-256 hash is ever stored. Authentication hashes the incoming bearer
	// token and compares against key_hash.
	//
	// Schema reference: docs/SCHEMA.md § api_keys
	// Security spec: docs/ARCHITECTURE.md § "Token architecture" (API Keys row)
	// Insert a new API key record. The plaintext key has already been generated and
	// hashed by the application layer before this query is called.
	// key_hash = hex(SHA-256(full_plaintext_key))
	// key_prefix = first 8 chars of full_plaintext_key (for display identification)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateActivation(ctx context.Context, arg CreateActivationParams) (Activation, error)
	CreateContestSession(ctx context.Context, arg CreateContestSessionParams) (CreateContestSessionRow, error)
	// Creates a new import job record and returns the created row including its UUID.
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error)
	// Records a single per-record parse or validation error for an import job.
	CreateImportJobError(ctx context.Context, arg CreateImportJobErrorParams) error
	CreateInviteKey(ctx context.Context, arg CreateInviteKeyParams) (InviteKey, error)
	CreateLogbook(ctx context.Context, arg CreateLogbookParams) (CreateLogbookRow, error)
	// Queries for notifications feed.
	//
	// Notification payloads are JSONB so feature-specific data can evolve without
	// schema churn, while type remains strongly constrained in the database.
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateQSO(ctx context.Context, arg CreateQSOParams) (CreateQSORow, error)
	CreateSpotWatchRule(ctx context.Context, arg CreateSpotWatchRuleParams) (SpotWatchRule, error)
	// ─────────────────────────────────────────────────────────────────────────────
	// station_callsigns: station identity for logging (supports M:N operator model).
	// ─────────────────────────────────────────────────────────────────────────────
	// Creates a station callsign identity entry.
	CreateStationCallsign(ctx context.Context, arg CreateStationCallsignParams) (StationCallsign, error)
	// Queries for station_locations table.
	//
	// station_locations are the tQSL "station locations" required for LoTW integration.
	// One callsign can have many locations (Home, POTA Portable, DXpedition), each with
	// its own tQSL certificate. RLS isolates each user's locations.
	//
	// Schema reference: docs/SCHEMA.md § station_locations
	// Creates a new station location for the authenticated user.
	// The PostGIS location point is computed from lat/lon when both are provided,
	// falling back to the maidenhead_to_point() function on the grid_square.
	CreateStationLocation(ctx context.Context, arg CreateStationLocationParams) (CreateStationLocationRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Queries for user_callsigns (personal callsign history) and station_callsigns
	// (station identity, supporting M:N operator model) tables.
	//
	// Schema reference: docs/SCHEMA.md § user_callsigns, station_callsigns,
	//                                     station_callsign_operators
	// ─────────────────────────────────────────────────────────────────────────────
	// user_callsigns: personal callsign history (one per user, supports upgrades,
	// historical calls, and vanity changes).
	// ─────────────────────────────────────────────────────────────────────────────
	// Registers a new callsign for the authenticated user.
	// Callsigns are stored uppercase per ADIF and ham radio convention.
	CreateUserCallsign(ctx context.Context, arg CreateUserCallsignParams) (UserCallsign, error)
	// Creates a notification as the worker role (no user RLS context needed).
	// Used by background jobs to create notifications for any user.
	// The caller is responsible for SET LOCAL ROLE radioledger_worker before executing.
	CreateWorkerNotification(ctx context.Context, arg CreateWorkerNotificationParams) (Notification, error)
	CreateZitadelUser(ctx context.Context, arg CreateZitadelUserParams) (CreateZitadelUserRow, error)
	// Clears cached progress for a specific award type before full recalculation.
	DeleteAwardProgressByType(ctx context.Context, arg DeleteAwardProgressByTypeParams) error
	// Hard-delete the credential row.
	// Encrypted ciphertext is worthless without the master key, so there is no
	// audit value in retaining it after a user removes a service integration.
	DeleteCredential(ctx context.Context, arg DeleteCredentialParams) (int64, error)
	// Removes all expired entries. Run periodically (e.g. daily background job).
	DeleteExpiredCallsignCache(ctx context.Context) error
	DeleteLogbook(ctx context.Context, logbookUuid uuid.UUID) (uuid.UUID, error)
	DeleteLogbookMemberByUserUUID(ctx context.Context, arg DeleteLogbookMemberByUserUUIDParams) (int64, error)
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (int64, error)
	// Prune old PSK reception reports. Called periodically by the poller worker.
	DeletePSKReportsOlderThan(ctx context.Context, cutoffAt pgtype.Timestamptz) (int64, error)
	DeleteQSO(ctx context.Context, arg DeleteQSOParams) error
	DeleteSpotWatchRuleByUUID(ctx context.Context, arg DeleteSpotWatchRuleByUUIDParams) (int64, error)
	DeleteSpotsOlderThan(ctx context.Context, cutoffAt pgtype.Timestamptz) (int64, error)
	// Soft-deactivates a station callsign by clearing its active flag.
	// Hard-delete is not safe because QSOs may reference station_callsign_id.
	DeleteStationCallsign(ctx context.Context, callsignUuid uuid.UUID) error
	// Soft-deletes a station location. References from logbooks use ON DELETE SET NULL
	// so logbooks are not affected.
	DeleteStationLocation(ctx context.Context, locationUuid uuid.UUID) error
	// Removes a user callsign. Hard delete is safe because callsigns have no
	// downstream FK references from QSOs (those use the text callsign column).
	DeleteUserCallsign(ctx context.Context, callsignUuid uuid.UUID) error
	// Look up a QSO by the composite key used for eQSL matching:
	// their callsign, band, mode, and time window (±15 minutes).
	// eQSL timestamps may be off by a few minutes — use a generous window.
	FindQSOForEQSLMatch(ctx context.Context, arg FindQSOForEQSLMatchParams) (FindQSOForEQSLMatchRow, error)
	// Look up an API key by its SHA-256 hash for authentication.
	// Called by the auth middleware when it receives a "Bearer rl_..." token.
	// Returns the full row including user_id (needed to set RLS context).
	// Filters out revoked and expired keys.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetActivationByUUIDAndProgram(ctx context.Context, arg GetActivationByUUIDAndProgramParams) (GetActivationByUUIDAndProgramRow, error)
	GetActivationStatusByUUIDAndProgram(ctx context.Context, arg GetActivationStatusByUUIDAndProgramParams) (GetActivationStatusByUUIDAndProgramRow, error)
	GetActiveInviteByCode(ctx context.Context, code string) (InviteKey, error)
	// Unified summary of all award types for a user (for GET /v1/awards).
	// Returns one row per award_type with aggregate counts.
	GetAwardProgressSummary(ctx context.Context) ([]GetAwardProgressSummaryRow, error)
	// Returns a cached callsign record if it exists and has not expired.
	// Returns no rows if not found or expired.
	GetCallsignCache(ctx context.Context, callsign interface{}) (CallsignCache, error)
	// Fetch all header fields needed to generate a Cabrillo export.
	GetContestForExport(ctx context.Context, sessionUuid uuid.UUID) (GetContestForExportRow, error)
	// All QSOs for a contest session (including dupes), ordered by time.
	GetContestQSOsForExport(ctx context.Context, sessionUuid uuid.UUID) ([]GetContestQSOsForExportRow, error)
	GetContestSessionByUUID(ctx context.Context, sessionUuid uuid.UUID) (GetContestSessionByUUIDRow, error)
	// Live contest statistics for the session detail view.
	GetContestStats(ctx context.Context, sessionUuid uuid.UUID) (GetContestStatsRow, error)
	// Retrieve the encrypted credential blob for a specific (user, service).
	// RLS enforces that only the owning user can retrieve their own credentials.
	// Callers must decrypt the credentials blob before using it.
	GetCredential(ctx context.Context, arg GetCredentialParams) (UserServiceCredential, error)
	GetDXCCSummary(ctx context.Context) (GetDXCCSummaryRow, error)
	GetDXCCTotalEntities(ctx context.Context) (int64, error)
	GetDefaultLogbook(ctx context.Context, userID int64) (GetDefaultLogbookRow, error)
	// Returns an import job by its internal ID (used by the River worker).
	GetImportJobByID(ctx context.Context, id int64) (ImportJob, error)
	// Returns an import job by its UUID, scoped to the requesting user via RLS.
	GetImportJobByUUID(ctx context.Context, importJobUuid uuid.UUID) (GetImportJobByUUIDRow, error)
	// Returns errors for an import job, used for the error listing endpoint.
	GetImportJobErrors(ctx context.Context, arg GetImportJobErrorsParams) ([]GetImportJobErrorsRow, error)
	// Returns the most recent error reason for a given import job UUID.
	GetLatestImportJobErrorByUUID(ctx context.Context, importJobUuid uuid.UUID) (string, error)
	GetLogbookByUUID(ctx context.Context, logbookUuid uuid.UUID) (GetLogbookByUUIDRow, error)
	GetLogbookMemberByUserUUID(ctx context.Context, arg GetLogbookMemberByUserUUIDParams) (GetLogbookMemberByUserUUIDRow, error)
	GetLogbookOwner(ctx context.Context, logbookUuid uuid.UUID) (GetLogbookOwnerRow, error)
	GetPOTAAwardSummary(ctx context.Context) (GetPOTAAwardSummaryRow, error)
	// Queries for the sync_status table and sync-related operations.
	// Schema reference: docs/SCHEMA.md § sync_status
	// These queries are used by sync workers (radioledger_worker role) and the sync status API.
	// Fetch QSOs for a user+service that are pending/dirty or errored and eligible for retry.
	// Used by the sync upload workers to find work. Runs as radioledger_worker role.
	GetPendingSyncQSOs(ctx context.Context, arg GetPendingSyncQSOsParams) ([]GetPendingSyncQSOsRow, error)
	GetQSOByUUID(ctx context.Context, arg GetQSOByUUIDParams) (GetQSOByUUIDRow, error)
	GetQSOCreatorByUUID(ctx context.Context, arg GetQSOCreatorByUUIDParams) (*int64, error)
	// Look up a QSO by UUID for PSK Reporter matching. Returns just the fields
	// needed to match against reception reports. RLS ensures only the owner sees it.
	GetQSOForPSKMatch(ctx context.Context, qsoUuid uuid.UUID) (GetQSOForPSKMatchRow, error)
	// Recent sync activity for a user, newest first. Used by GET /v1/sync/history.
	GetRecentSyncHistory(ctx context.Context, arg GetRecentSyncHistoryParams) ([]GetRecentSyncHistoryRow, error)
	GetSpotNotificationPreference(ctx context.Context, userID int64) (SpotNotificationPreference, error)
	// Returns a single station callsign by UUID, scoped via RLS.
	GetStationCallsignByUUID(ctx context.Context, callsignUuid uuid.UUID) (StationCallsign, error)
	// Returns a station location by UUID, scoped to the authenticated user via RLS.
	GetStationLocationByUUID(ctx context.Context, locationUuid uuid.UUID) (GetStationLocationByUUIDRow, error)
	GetStatsBands(ctx context.Context) ([]GetStatsBandsRow, error)
	GetStatsByMonth(ctx context.Context) ([]GetStatsByMonthRow, error)
	GetStatsByYear(ctx context.Context) ([]GetStatsByYearRow, error)
	GetStatsCountriesOverTime(ctx context.Context) ([]GetStatsCountriesOverTimeRow, error)
	GetStatsModes(ctx context.Context) ([]GetStatsModesRow, error)
	GetStatsOperatingPatterns(ctx context.Context) ([]GetStatsOperatingPatternsRow, error)
	GetStatsOverview(ctx context.Context) (GetStatsOverviewRow, error)
	GetStatsSummary(ctx context.Context) (GetStatsSummaryRow, error)
	GetStatsTopCallsigns(ctx context.Context, lim int32) ([]GetStatsTopCallsignsRow, error)
	GetStatsTopCountries(ctx context.Context) ([]GetStatsTopCountriesRow, error)
	GetStatsTopCountriesLimited(ctx context.Context, lim int32) ([]GetStatsTopCountriesLimitedRow, error)
	// Aggregate sync status per service for a user. Used by GET /v1/sync/status.
	GetSyncStatusSummary(ctx context.Context, userID int64) ([]GetSyncStatusSummaryRow, error)
	GetUserByCallsign(ctx context.Context, callsign interface{}) (GetUserByCallsignRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByZitadelID(ctx context.Context, zitadelID *string) (GetUserByZitadelIDRow, error)
	// Returns a single user callsign by UUID, scoped via RLS.
	GetUserCallsignByUUID(ctx context.Context, callsignUuid uuid.UUID) (UserCallsign, error)
	GetUserPreferences(ctx context.Context, id int64) (GetUserPreferencesRow, error)
	GetUserRoleForLogbook(ctx context.Context, arg GetUserRoleForLogbookParams) (string, error)
	// Returns the count of cert_expiry notifications already sent for a specific
	// (user, callsign, expiry date, threshold) combination within the past 25 days.
	// Used by CertExpiryCheckJob to avoid sending duplicate alerts.
	// Runs as radioledger_worker role (see migration 013 for the SELECT policy).
	HasRecentCertExpiryNotification(ctx context.Context, arg HasRecentCertExpiryNotificationParams) (int64, error)
	// Atomically increment serial_counter and return the new value.
	IncrementSerialCounter(ctx context.Context, sessionUuid uuid.UUID) (int32, error)
	// Insert a QSO linked to a contest session.
	InsertContestQSO(ctx context.Context, arg InsertContestQSOParams) (InsertContestQSORow, error)
	InsertContestQSOExchange(ctx context.Context, arg InsertContestQSOExchangeParams) (InsertContestQSOExchangeRow, error)
	// Insert a pending sync_status row for a single (qso_id, service) combination.
	// ON CONFLICT DO NOTHING: if a pending row already exists, leave it alone.
	// This is called by the QSO handler after create/update to enqueue sync work.
	InsertPendingSyncForQSO(ctx context.Context, arg InsertPendingSyncForQSOParams) error
	LinkUserZitadelIDByEmail(ctx context.Context, arg LinkUserZitadelIDByEmailParams) (LinkUserZitadelIDByEmailRow, error)
	// List API keys for a user — never returns key_hash (the secret hash).
	// Returns prefix, name, scopes, timestamps for display.
	// Revoked keys are excluded by default (revoked_at IS NULL).
	ListAPIKeys(ctx context.Context, userID int64) ([]ListAPIKeysRow, error)
	// POTA activator: parks activated from the operator-side MY_POTA_REF ADIF field.
	ListActivatedPOTAParks(ctx context.Context) ([]ListActivatedPOTAParksRow, error)
	// SOTA activator: summits activated (my_sota_ref from activator QSOs).
	ListActivatedSOTASummits(ctx context.Context) ([]ListActivatedSOTASummitsRow, error)
	ListActivationQSOsByUUIDAndProgram(ctx context.Context, arg ListActivationQSOsByUUIDAndProgramParams) ([]ListActivationQSOsByUUIDAndProgramRow, error)
	ListActivationsByProgram(ctx context.Context, arg ListActivationsByProgramParams) ([]ListActivationsByProgramRow, error)
	ListActiveSpots(ctx context.Context, arg ListActiveSpotsParams) ([]Spot, error)
	// Worker query: returns all station locations with a non-null lotw_cert_expiry.
	// Used by CertExpiryCheckJob to find certificates approaching expiry.
	// Runs as radioledger_worker role (see migration 013 for the SELECT policy).
	// No user filter — intentionally queries across all users.
	ListAllExpiringCerts(ctx context.Context) ([]ListAllExpiringCertsRow, error)
	// Detailed progress rows for a specific award type (for GET /v1/awards/:type).
	ListAwardProgressByType(ctx context.Context, awardType string) ([]ListAwardProgressByTypeRow, error)
	ListContestSessions(ctx context.Context, userID int64) ([]ListContestSessionsRow, error)
	ListContests(ctx context.Context) ([]ListContestsRow, error)
	// List credentials for a user — service names and metadata ONLY.
	// The encrypted credentials blob is intentionally excluded from this query.
	// Callers see which services are configured, but cannot retrieve the secrets.
	ListCredentials(ctx context.Context, userID int64) ([]ListCredentialsRow, error)
	ListDXCCByBand(ctx context.Context) ([]ListDXCCByBandRow, error)
	ListDXCCEntitiesProgress(ctx context.Context) ([]ListDXCCEntitiesProgressRow, error)
	ListDXCCEntityQSODetails(ctx context.Context) ([]ListDXCCEntityQSODetailsRow, error)
	// POTA hunter: parks worked (sig=POTA, sig_info has park reference).
	ListHuntedPOTAParks(ctx context.Context) ([]ListHuntedPOTAParksRow, error)
	ListInviteKeysByCreator(ctx context.Context, createdBy int64) ([]InviteKey, error)
	ListLogbookMembers(ctx context.Context, logbookUuid uuid.UUID) ([]ListLogbookMembersRow, error)
	ListLogbooksByUser(ctx context.Context, userID int64) ([]ListLogbooksByUserRow, error)
	ListMatchingSpotWatchRules(ctx context.Context, arg ListMatchingSpotWatchRulesParams) ([]ListMatchingSpotWatchRulesRow, error)
	ListNeededSpotsForUser(ctx context.Context, arg ListNeededSpotsForUserParams) ([]Spot, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// Paginated list of PSK reception reports for the authenticated user.
	// Cursor-based pagination using (spotted_at DESC, id DESC).
	ListPSKReceptionReports(ctx context.Context, arg ListPSKReceptionReportsParams) ([]PskReceptionReport, error)
	// Find PSK reception reports that match a specific QSO by sender callsign
	// and time window. Used by the /match/:qso_id endpoint.
	ListPSKReportsByCallsignAndWindow(ctx context.Context, arg ListPSKReportsByCallsignAndWindowParams) ([]PskReceptionReport, error)
	ListQSOsByLogbook(ctx context.Context, arg ListQSOsByLogbookParams) ([]ListQSOsByLogbookRow, error)
	ListSpotWatchRules(ctx context.Context, userID int64) ([]SpotWatchRule, error)
	// Lists all station callsigns for the authenticated user, active first.
	ListStationCallsigns(ctx context.Context, userID int64) ([]StationCallsign, error)
	// Lists all active station locations for the authenticated user, newest first.
	ListStationLocations(ctx context.Context, userID int64) ([]ListStationLocationsRow, error)
	// Returns only unread notifications for a user, newest first.
	// Used by GET /v1/notifications?unread=true.
	ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error)
	// Lists all callsigns for the authenticated user, primary first then newest first.
	ListUserCallsigns(ctx context.Context, userID int64) ([]UserCallsign, error)
	// Return users who have a callsign configured. Used by the PSK Reporter poller
	// to determine which callsigns to query.
	ListUsersWithCallsign(ctx context.Context) ([]ListUsersWithCallsignRow, error)
	ListWorkedGridSquares(ctx context.Context) ([]ListWorkedGridSquaresRow, error)
	// SOTA chaser: summits worked as chaser from sig/sig_info fields.
	ListWorkedSOTASummits(ctx context.Context) ([]ListWorkedSOTASummitsRow, error)
	ListWorkedStates(ctx context.Context) ([]ListWorkedStatesRow, error)
	// WPX: raw callsigns for prefix extraction (done in Go).
	ListWorkedWPXPrefixes(ctx context.Context) ([]ListWorkedWPXPrefixesRow, error)
	// WAZ: CQ zones worked from QSO records.
	ListWorkedZones(ctx context.Context) ([]ListWorkedZonesRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID int64) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	// Called after QSO mutations to flag all cached award progress for recalculation.
	MarkUserAwardsDirty(ctx context.Context, userID int64) error
	// Revoke an API key by UUID. Sets revoked_at to the current time.
	// RLS ensures only the owning user can revoke their own keys.
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeInviteKey(ctx context.Context, arg RevokeInviteKeyParams) (int64, error)
	SearchQSOs(ctx context.Context, arg SearchQSOsParams) ([]SearchQSOsRow, error)
	SetLogbookMemberRoleByUserID(ctx context.Context, arg SetLogbookMemberRoleByUserIDParams) (int64, error)
	SetLogbookOwnerUser(ctx context.Context, arg SetLogbookOwnerUserParams) (int64, error)
	SoftDeleteUserByID(ctx context.Context, id int64) (int64, error)
	// Transitions a job to processing status and sets started_at.
	StartImportJob(ctx context.Context, arg StartImportJobParams) (StartImportJobRow, error)
	// Record the last-used timestamp and source IP for an API key.
	// Called after every successful API key authentication.
	// Uses a direct id (internal PK) for efficiency — id is already known from GetAPIKeyByHash.
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateActivationByUUIDAndProgram(ctx context.Context, arg UpdateActivationByUUIDAndProgramParams) (Activation, error)
	// Updates lotw_cert_expiry on all active station locations matching the callsign
	// for the authenticated user. Called by POST /v1/desktop/cert-expiry.
	// Returns the number of rows updated (0 = no matching location found).
	UpdateCertExpiryByCallsign(ctx context.Context, arg UpdateCertExpiryByCallsignParams) (int64, error)
	UpdateContestSession(ctx context.Context, arg UpdateContestSessionParams) (UpdateContestSessionRow, error)
	// Record when a credential was last used for a sync operation.
	// Called by sync workers when they successfully use a stored credential.
	UpdateCredentialLastUsed(ctx context.Context, arg UpdateCredentialLastUsedParams) error
	// Updates rolling counters for a running import job. Called periodically by the worker.
	UpdateImportJobProgress(ctx context.Context, arg UpdateImportJobProgressParams) error
	UpdateLogbook(ctx context.Context, arg UpdateLogbookParams) (UpdateLogbookRow, error)
	UpdateLogbookMemberRoleByUserUUID(ctx context.Context, arg UpdateLogbookMemberRoleByUserUUIDParams) (UserRole, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdateQSO(ctx context.Context, arg UpdateQSOParams) (UpdateQSORow, error)
	UpdateSpotWatchRuleByUUID(ctx context.Context, arg UpdateSpotWatchRuleByUUIDParams) (SpotWatchRule, error)
	UpdateSpotWatchRuleLastNotified(ctx context.Context, arg UpdateSpotWatchRuleLastNotifiedParams) error
	// Updates a station callsign's metadata.
	UpdateStationCallsign(ctx context.Context, arg UpdateStationCallsignParams) (StationCallsign, error)
	// Updates a station location by UUID. Recomputes the PostGIS point when coordinates change.
	UpdateStationLocation(ctx context.Context, arg UpdateStationLocationParams) (UpdateStationLocationRow, error)
	// Updates a user callsign's metadata (primary flag, active status, validity dates).
	// Callsign text itself is immutable once created (create a new row for a new call).
	UpdateUserCallsign(ctx context.Context, arg UpdateUserCallsignParams) (UserCallsign, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UpdateUserPreferencesRow, error)
	// Upsert a single award_progress row. Used by AwardRefreshWorker.
	UpsertAwardProgress(ctx context.Context, arg UpsertAwardProgressParams) error
	// Queries for the callsign_cache table.
	//
	// callsign_cache stores the results of QRZ/HamDB lookups so that we do not
	// hammer external callbook APIs during ADIF imports or rapid QSO entry.
	// A 100k-QSO import without this = 100k API calls; QRZ rate-limits aggressively.
	//
	// Schema reference: docs/SCHEMA.md § callsign_cache
	// Cache TTL: 30 days (callsign data rarely changes; license class and grid are stable)
	//
	// This table is NOT tenant-scoped (no user_id, no RLS). All users share the same
	// cache of public callbook data. The data is public information from QRZ/HamDB.
	// Insert or update a callsign cache entry.
	// On conflict (same callsign), overwrites with fresh data and resets expiry.
	UpsertCallsignCache(ctx context.Context, arg UpsertCallsignCacheParams) (CallsignCache, error)
	// Auto-provision a contest record by ADIF contest code.
	// Inserts if not present; returns existing record if already there.
	UpsertContest(ctx context.Context, arg UpsertContestParams) (UpsertContestRow, error)
	// Queries for user_service_credentials (encrypted external service credentials).
	// Plaintext is NEVER stored or logged here. All encryption/decryption happens in
	// the Go crypto layer before calling these queries.
	//
	// Schema reference: docs/SCHEMA.md § user_service_credentials
	// Encryption spec: docs/ARCHITECTURE.md § "Credential Encryption: AES-256-GCM"
	// Insert or update an encrypted credential for a (user_id, service) pair.
	// ON CONFLICT updates the ciphertext, key_version, and metadata.
	// The UNIQUE(user_id, service) constraint ensures one active credential per service per user.
	UpsertCredential(ctx context.Context, arg UpsertCredentialParams) (UpsertCredentialRow, error)
	UpsertLogbookMemberRole(ctx context.Context, arg UpsertLogbookMemberRoleParams) (UserRole, error)
	// Insert a new PSK reception report, ignoring duplicates (same user, sender,
	// receiver, spotted_at). Called by the PSK Reporter poller worker.
	UpsertPSKReceptionReport(ctx context.Context, arg UpsertPSKReceptionReportParams) error
	UpsertSpot(ctx context.Context, arg UpsertSpotParams) error
	UpsertSpotNotificationPreference(ctx context.Context, arg UpsertSpotNotificationPreferenceParams) (SpotNotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
