// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spots.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSpotWatchRule = `-- name: CreateSpotWatchRule :one
INSERT INTO spot_watch_rules (
    user_id,
    source,
    reference,
    mode,
    band,
    enabled
)
VALUES (
    $1::bigint,
    $2::text,
    UPPER($3::text),
    $4::text,
    $5::text,
    COALESCE($6::boolean, TRUE)
)
RETURNING
    id,
    uuid,
    user_id,
    source,
    reference,
    mode,
    band,
    enabled,
    last_notified_at,
    created_at,
    updated_at
`

type CreateSpotWatchRuleParams struct {
	UserID    int64   `json:"user_id"`
	Source    string  `json:"source"`
	Reference string  `json:"reference"`
	Mode      *string `json:"mode"`
	Band      *string `json:"band"`
	Enabled   *bool   `json:"enabled"`
}

func (q *Queries) CreateSpotWatchRule(ctx context.Context, arg CreateSpotWatchRuleParams) (SpotWatchRule, error) {
	row := q.db.QueryRow(ctx, createSpotWatchRule,
		arg.UserID,
		arg.Source,
		arg.Reference,
		arg.Mode,
		arg.Band,
		arg.Enabled,
	)
	var i SpotWatchRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Source,
		&i.Reference,
		&i.Mode,
		&i.Band,
		&i.Enabled,
		&i.LastNotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpotWatchRuleByUUID = `-- name: DeleteSpotWatchRuleByUUID :execrows
DELETE FROM spot_watch_rules
WHERE uuid = $1::uuid
  AND user_id = $2::bigint
`

type DeleteSpotWatchRuleByUUIDParams struct {
	RuleUuid uuid.UUID `json:"rule_uuid"`
	UserID   int64     `json:"user_id"`
}

func (q *Queries) DeleteSpotWatchRuleByUUID(ctx context.Context, arg DeleteSpotWatchRuleByUUIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpotWatchRuleByUUID, arg.RuleUuid, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSpotsOlderThan = `-- name: DeleteSpotsOlderThan :execrows
DELETE FROM spots
WHERE spotted_at < $1::timestamptz
`

func (q *Queries) DeleteSpotsOlderThan(ctx context.Context, cutoffAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpotsOlderThan, cutoffAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpotNotificationPreference = `-- name: GetSpotNotificationPreference :one
SELECT
    id,
    user_id,
    enabled,
    cooldown_minutes,
    created_at,
    updated_at
FROM spot_notification_preferences
WHERE user_id = $1::bigint
`

func (q *Queries) GetSpotNotificationPreference(ctx context.Context, userID int64) (SpotNotificationPreference, error) {
	row := q.db.QueryRow(ctx, getSpotNotificationPreference, userID)
	var i SpotNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Enabled,
		&i.CooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSpots = `-- name: ListActiveSpots :many
SELECT
    id,
    source,
    callsign,
    reference,
    frequency_khz,
    band,
    mode,
    spotted_at,
    raw_payload,
    created_at,
    updated_at
FROM spots
WHERE spotted_at >= NOW() - INTERVAL '24 hours'
  AND ($1::text IS NULL OR source = $1::text)
  AND ($2::text IS NULL OR band = $2::text)
  AND ($3::text IS NULL OR mode = $3::text)
ORDER BY spotted_at DESC, id DESC
LIMIT $4::int
`

type ListActiveSpotsParams struct {
	SourceFilter *string `json:"source_filter"`
	BandFilter   *string `json:"band_filter"`
	ModeFilter   *string `json:"mode_filter"`
	LimitCount   int32   `json:"limit_count"`
}

func (q *Queries) ListActiveSpots(ctx context.Context, arg ListActiveSpotsParams) ([]Spot, error) {
	rows, err := q.db.Query(ctx, listActiveSpots,
		arg.SourceFilter,
		arg.BandFilter,
		arg.ModeFilter,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spot{}
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Callsign,
			&i.Reference,
			&i.FrequencyKhz,
			&i.Band,
			&i.Mode,
			&i.SpottedAt,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchingSpotWatchRules = `-- name: ListMatchingSpotWatchRules :many
SELECT
    r.id,
    r.uuid,
    r.user_id,
    r.source,
    r.reference,
    r.mode,
    r.band,
    r.enabled,
    r.last_notified_at,
    r.created_at,
    r.updated_at,
    COALESCE(p.enabled, TRUE) AS notifications_enabled,
    COALESCE(p.cooldown_minutes, 30)::int AS cooldown_minutes
FROM spot_watch_rules r
LEFT JOIN spot_notification_preferences p ON p.user_id = r.user_id
WHERE r.enabled = TRUE
  AND r.source = $1::text
  AND UPPER(BTRIM(r.reference)) = UPPER(BTRIM($2::text))
  AND (
      $3::text IS NULL
      OR r.mode IS NULL
      OR UPPER(BTRIM(r.mode)) = UPPER(BTRIM($3::text))
  )
  AND (
      $4::text IS NULL
      OR r.band IS NULL
      OR UPPER(BTRIM(r.band)) = UPPER(BTRIM($4::text))
  )
`

type ListMatchingSpotWatchRulesParams struct {
	Source    string  `json:"source"`
	Reference string  `json:"reference"`
	Mode      *string `json:"mode"`
	Band      *string `json:"band"`
}

type ListMatchingSpotWatchRulesRow struct {
	ID                   int64              `json:"id"`
	Uuid                 uuid.UUID          `json:"uuid"`
	UserID               int64              `json:"user_id"`
	Source               string             `json:"source"`
	Reference            string             `json:"reference"`
	Mode                 *string            `json:"mode"`
	Band                 *string            `json:"band"`
	Enabled              bool               `json:"enabled"`
	LastNotifiedAt       pgtype.Timestamptz `json:"last_notified_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	CooldownMinutes      int32              `json:"cooldown_minutes"`
}

func (q *Queries) ListMatchingSpotWatchRules(ctx context.Context, arg ListMatchingSpotWatchRulesParams) ([]ListMatchingSpotWatchRulesRow, error) {
	rows, err := q.db.Query(ctx, listMatchingSpotWatchRules,
		arg.Source,
		arg.Reference,
		arg.Mode,
		arg.Band,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchingSpotWatchRulesRow{}
	for rows.Next() {
		var i ListMatchingSpotWatchRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Source,
			&i.Reference,
			&i.Mode,
			&i.Band,
			&i.Enabled,
			&i.LastNotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NotificationsEnabled,
			&i.CooldownMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNeededSpotsForUser = `-- name: ListNeededSpotsForUser :many
SELECT
    s.id,
    s.source,
    s.callsign,
    s.reference,
    s.frequency_khz,
    s.band,
    s.mode,
    s.spotted_at,
    s.raw_payload,
    s.created_at,
    s.updated_at
FROM spots s
WHERE s.spotted_at >= NOW() - INTERVAL '24 hours'
  AND ($1::text IS NULL OR s.source = $1::text)
  AND ($2::text IS NULL OR s.band = $2::text)
  AND ($3::text IS NULL OR s.mode = $3::text)
  AND NOT EXISTS (
      SELECT 1
      FROM activations a
      WHERE a.user_id = $4::bigint
        AND (
            (s.source = 'pota' AND a.program = 'POTA')
            OR (s.source = 'sota' AND a.program = 'SOTA')
        )
        AND UPPER(BTRIM(a.reference)) = UPPER(BTRIM(s.reference))
  )
ORDER BY s.spotted_at DESC, s.id DESC
LIMIT $5::int
`

type ListNeededSpotsForUserParams struct {
	SourceFilter *string `json:"source_filter"`
	BandFilter   *string `json:"band_filter"`
	ModeFilter   *string `json:"mode_filter"`
	UserID       int64   `json:"user_id"`
	LimitCount   int32   `json:"limit_count"`
}

func (q *Queries) ListNeededSpotsForUser(ctx context.Context, arg ListNeededSpotsForUserParams) ([]Spot, error) {
	rows, err := q.db.Query(ctx, listNeededSpotsForUser,
		arg.SourceFilter,
		arg.BandFilter,
		arg.ModeFilter,
		arg.UserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spot{}
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Callsign,
			&i.Reference,
			&i.FrequencyKhz,
			&i.Band,
			&i.Mode,
			&i.SpottedAt,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpotWatchRules = `-- name: ListSpotWatchRules :many
SELECT
    id,
    uuid,
    user_id,
    source,
    reference,
    mode,
    band,
    enabled,
    last_notified_at,
    created_at,
    updated_at
FROM spot_watch_rules
WHERE user_id = $1::bigint
ORDER BY created_at DESC
`

func (q *Queries) ListSpotWatchRules(ctx context.Context, userID int64) ([]SpotWatchRule, error) {
	rows, err := q.db.Query(ctx, listSpotWatchRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpotWatchRule{}
	for rows.Next() {
		var i SpotWatchRule
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Source,
			&i.Reference,
			&i.Mode,
			&i.Band,
			&i.Enabled,
			&i.LastNotifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpotWatchRuleByUUID = `-- name: UpdateSpotWatchRuleByUUID :one
UPDATE spot_watch_rules
SET
    source = COALESCE($1::text, source),
    reference = CASE
        WHEN $2::text IS NULL THEN reference
        ELSE UPPER($2::text)
    END,
    mode = $3::text,
    band = $4::text,
    enabled = COALESCE($5::boolean, enabled),
    updated_at = NOW()
WHERE uuid = $6::uuid
  AND user_id = $7::bigint
RETURNING
    id,
    uuid,
    user_id,
    source,
    reference,
    mode,
    band,
    enabled,
    last_notified_at,
    created_at,
    updated_at
`

type UpdateSpotWatchRuleByUUIDParams struct {
	Source    *string   `json:"source"`
	Reference *string   `json:"reference"`
	Mode      *string   `json:"mode"`
	Band      *string   `json:"band"`
	Enabled   *bool     `json:"enabled"`
	RuleUuid  uuid.UUID `json:"rule_uuid"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) UpdateSpotWatchRuleByUUID(ctx context.Context, arg UpdateSpotWatchRuleByUUIDParams) (SpotWatchRule, error) {
	row := q.db.QueryRow(ctx, updateSpotWatchRuleByUUID,
		arg.Source,
		arg.Reference,
		arg.Mode,
		arg.Band,
		arg.Enabled,
		arg.RuleUuid,
		arg.UserID,
	)
	var i SpotWatchRule
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Source,
		&i.Reference,
		&i.Mode,
		&i.Band,
		&i.Enabled,
		&i.LastNotifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSpotWatchRuleLastNotified = `-- name: UpdateSpotWatchRuleLastNotified :exec
UPDATE spot_watch_rules
SET last_notified_at = $1::timestamptz,
    updated_at = NOW()
WHERE id = $2::bigint
`

type UpdateSpotWatchRuleLastNotifiedParams struct {
	LastNotifiedAt pgtype.Timestamptz `json:"last_notified_at"`
	RuleID         int64              `json:"rule_id"`
}

func (q *Queries) UpdateSpotWatchRuleLastNotified(ctx context.Context, arg UpdateSpotWatchRuleLastNotifiedParams) error {
	_, err := q.db.Exec(ctx, updateSpotWatchRuleLastNotified, arg.LastNotifiedAt, arg.RuleID)
	return err
}

const upsertSpot = `-- name: UpsertSpot :exec
INSERT INTO spots (
    source,
    callsign,
    reference,
    frequency_khz,
    band,
    mode,
    spotted_at,
    raw_payload,
    updated_at
)
VALUES (
    $1::text,
    UPPER($2::text),
    UPPER($3::text),
    $4::numeric,
    $5::text,
    $6::text,
    $7::timestamptz,
    COALESCE($8::jsonb, '{}'::jsonb),
    NOW()
)
ON CONFLICT (source, callsign, reference, spotted_at)
DO UPDATE SET
    frequency_khz = EXCLUDED.frequency_khz,
    band = EXCLUDED.band,
    mode = EXCLUDED.mode,
    raw_payload = EXCLUDED.raw_payload,
    updated_at = NOW()
`

type UpsertSpotParams struct {
	Source       string             `json:"source"`
	Callsign     string             `json:"callsign"`
	Reference    string             `json:"reference"`
	FrequencyKhz pgtype.Numeric     `json:"frequency_khz"`
	Band         *string            `json:"band"`
	Mode         *string            `json:"mode"`
	SpottedAt    pgtype.Timestamptz `json:"spotted_at"`
	RawPayload   []byte             `json:"raw_payload"`
}

func (q *Queries) UpsertSpot(ctx context.Context, arg UpsertSpotParams) error {
	_, err := q.db.Exec(ctx, upsertSpot,
		arg.Source,
		arg.Callsign,
		arg.Reference,
		arg.FrequencyKhz,
		arg.Band,
		arg.Mode,
		arg.SpottedAt,
		arg.RawPayload,
	)
	return err
}

const upsertSpotNotificationPreference = `-- name: UpsertSpotNotificationPreference :one
INSERT INTO spot_notification_preferences (
    user_id,
    enabled,
    cooldown_minutes,
    updated_at
)
VALUES (
    $1::bigint,
    $2::boolean,
    $3::int,
    NOW()
)
ON CONFLICT (user_id)
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    cooldown_minutes = EXCLUDED.cooldown_minutes,
    updated_at = NOW()
RETURNING
    id,
    user_id,
    enabled,
    cooldown_minutes,
    created_at,
    updated_at
`

type UpsertSpotNotificationPreferenceParams struct {
	UserID          int64 `json:"user_id"`
	Enabled         bool  `json:"enabled"`
	CooldownMinutes int32 `json:"cooldown_minutes"`
}

func (q *Queries) UpsertSpotNotificationPreference(ctx context.Context, arg UpsertSpotNotificationPreferenceParams) (SpotNotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertSpotNotificationPreference, arg.UserID, arg.Enabled, arg.CooldownMinutes)
	var i SpotNotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Enabled,
		&i.CooldownMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
