// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStatsBands = `-- name: GetStatsBands :many
SELECT
    q.band,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY q.band
ORDER BY count DESC, q.band ASC
`

type GetStatsBandsRow struct {
	Band  string `json:"band"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStatsBands(ctx context.Context) ([]GetStatsBandsRow, error) {
	rows, err := q.db.Query(ctx, getStatsBands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsBandsRow{}
	for rows.Next() {
		var i GetStatsBandsRow
		if err := rows.Scan(&i.Band, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByMonth = `-- name: GetStatsByMonth :many
SELECT
    TO_CHAR(q.datetime_on AT TIME ZONE 'UTC', 'YYYY-MM') AS period,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY period
ORDER BY period ASC
`

type GetStatsByMonthRow struct {
	Period string `json:"period"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetStatsByMonth(ctx context.Context) ([]GetStatsByMonthRow, error) {
	rows, err := q.db.Query(ctx, getStatsByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsByMonthRow{}
	for rows.Next() {
		var i GetStatsByMonthRow
		if err := rows.Scan(&i.Period, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByYear = `-- name: GetStatsByYear :many
SELECT
    EXTRACT(YEAR FROM q.datetime_on AT TIME ZONE 'UTC')::int AS year,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY year
ORDER BY year ASC
`

type GetStatsByYearRow struct {
	Year  int32 `json:"year"`
	Count int64 `json:"count"`
}

func (q *Queries) GetStatsByYear(ctx context.Context) ([]GetStatsByYearRow, error) {
	rows, err := q.db.Query(ctx, getStatsByYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsByYearRow{}
	for rows.Next() {
		var i GetStatsByYearRow
		if err := rows.Scan(&i.Year, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsCountriesOverTime = `-- name: GetStatsCountriesOverTime :many
WITH first_seen AS (
    SELECT
        COALESCE(NULLIF(BTRIM(q.country), ''), d.name) AS country_name,
        TO_CHAR(MIN(q.datetime_on AT TIME ZONE 'UTC'), 'YYYY-MM') AS first_period
    FROM qsos q
    JOIN logbooks l ON l.id = q.logbook_id
    LEFT JOIN dxcc_entities d ON d.entity_id = q.dxcc
    WHERE l.deleted_at IS NULL
      AND q.deleted_at IS NULL
      AND COALESCE(NULLIF(BTRIM(q.country), ''), d.name) IS NOT NULL
    GROUP BY COALESCE(NULLIF(BTRIM(q.country), ''), d.name)
), monthly_new AS (
    SELECT
        first_period AS period,
        COUNT(*)::bigint AS new_countries
    FROM first_seen
    GROUP BY first_period
)
SELECT
    period,
    SUM(new_countries) OVER (ORDER BY period ASC)::bigint AS unique_countries
FROM monthly_new
ORDER BY period ASC
`

type GetStatsCountriesOverTimeRow struct {
	Period          string `json:"period"`
	UniqueCountries int64  `json:"unique_countries"`
}

func (q *Queries) GetStatsCountriesOverTime(ctx context.Context) ([]GetStatsCountriesOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getStatsCountriesOverTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsCountriesOverTimeRow{}
	for rows.Next() {
		var i GetStatsCountriesOverTimeRow
		if err := rows.Scan(&i.Period, &i.UniqueCountries); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsModes = `-- name: GetStatsModes :many
SELECT
    q.mode,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY q.mode
ORDER BY count DESC, q.mode ASC
`

type GetStatsModesRow struct {
	Mode  string `json:"mode"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStatsModes(ctx context.Context) ([]GetStatsModesRow, error) {
	rows, err := q.db.Query(ctx, getStatsModes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsModesRow{}
	for rows.Next() {
		var i GetStatsModesRow
		if err := rows.Scan(&i.Mode, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsOperatingPatterns = `-- name: GetStatsOperatingPatterns :many
SELECT
    EXTRACT(DOW FROM q.datetime_on AT TIME ZONE 'UTC')::int AS day_of_week,
    EXTRACT(HOUR FROM q.datetime_on AT TIME ZONE 'UTC')::int AS hour_of_day,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY day_of_week, hour_of_day
ORDER BY day_of_week ASC, hour_of_day ASC
`

type GetStatsOperatingPatternsRow struct {
	DayOfWeek int32 `json:"day_of_week"`
	HourOfDay int32 `json:"hour_of_day"`
	Count     int64 `json:"count"`
}

func (q *Queries) GetStatsOperatingPatterns(ctx context.Context) ([]GetStatsOperatingPatternsRow, error) {
	rows, err := q.db.Query(ctx, getStatsOperatingPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsOperatingPatternsRow{}
	for rows.Next() {
		var i GetStatsOperatingPatternsRow
		if err := rows.Scan(&i.DayOfWeek, &i.HourOfDay, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsOverview = `-- name: GetStatsOverview :one
SELECT
    COUNT(*)::bigint AS total_qsos,
    COUNT(DISTINCT q.callsign)::bigint AS unique_callsigns,
    COUNT(DISTINCT COALESCE(NULLIF(BTRIM(q.country), ''), d.name)) FILTER (
        WHERE COALESCE(NULLIF(BTRIM(q.country), ''), d.name) IS NOT NULL
    )::bigint AS unique_countries,
    COUNT(DISTINCT NULLIF(BTRIM(q.state), ''))::bigint AS unique_states,
    COUNT(DISTINCT NULLIF(BTRIM(q.gridsquare), ''))::bigint AS unique_grids,
    COUNT(DISTINCT q.band)::bigint AS bands_used,
    COUNT(DISTINCT q.mode)::bigint AS modes_used,
    MIN(q.datetime_on)::timestamptz AS first_qso,
    MAX(q.datetime_on)::timestamptz AS last_qso
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
LEFT JOIN dxcc_entities d ON d.entity_id = q.dxcc
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
`

type GetStatsOverviewRow struct {
	TotalQsos       int64              `json:"total_qsos"`
	UniqueCallsigns int64              `json:"unique_callsigns"`
	UniqueCountries int64              `json:"unique_countries"`
	UniqueStates    int64              `json:"unique_states"`
	UniqueGrids     int64              `json:"unique_grids"`
	BandsUsed       int64              `json:"bands_used"`
	ModesUsed       int64              `json:"modes_used"`
	FirstQso        pgtype.Timestamptz `json:"first_qso"`
	LastQso         pgtype.Timestamptz `json:"last_qso"`
}

func (q *Queries) GetStatsOverview(ctx context.Context) (GetStatsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getStatsOverview)
	var i GetStatsOverviewRow
	err := row.Scan(
		&i.TotalQsos,
		&i.UniqueCallsigns,
		&i.UniqueCountries,
		&i.UniqueStates,
		&i.UniqueGrids,
		&i.BandsUsed,
		&i.ModesUsed,
		&i.FirstQso,
		&i.LastQso,
	)
	return i, err
}

const getStatsSummary = `-- name: GetStatsSummary :one
SELECT
    COUNT(*)::bigint AS total_qsos,
    COUNT(DISTINCT q.callsign)::bigint AS unique_callsigns,
    COUNT(DISTINCT COALESCE(NULLIF(BTRIM(q.country), ''), d.name)) FILTER (
        WHERE COALESCE(NULLIF(BTRIM(q.country), ''), d.name) IS NOT NULL
    )::bigint AS unique_countries,
    COUNT(DISTINCT NULLIF(BTRIM(q.gridsquare), ''))::bigint AS unique_grids,
    MIN(q.datetime_on)::timestamptz AS first_qso,
    MAX(q.datetime_on)::timestamptz AS last_qso
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
LEFT JOIN dxcc_entities d ON d.entity_id = q.dxcc
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
`

type GetStatsSummaryRow struct {
	TotalQsos       int64              `json:"total_qsos"`
	UniqueCallsigns int64              `json:"unique_callsigns"`
	UniqueCountries int64              `json:"unique_countries"`
	UniqueGrids     int64              `json:"unique_grids"`
	FirstQso        pgtype.Timestamptz `json:"first_qso"`
	LastQso         pgtype.Timestamptz `json:"last_qso"`
}

func (q *Queries) GetStatsSummary(ctx context.Context) (GetStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStatsSummary)
	var i GetStatsSummaryRow
	err := row.Scan(
		&i.TotalQsos,
		&i.UniqueCallsigns,
		&i.UniqueCountries,
		&i.UniqueGrids,
		&i.FirstQso,
		&i.LastQso,
	)
	return i, err
}

const getStatsTopCallsigns = `-- name: GetStatsTopCallsigns :many
SELECT
    q.callsign,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
GROUP BY q.callsign
ORDER BY count DESC, q.callsign ASC
LIMIT $1::int
`

type GetStatsTopCallsignsRow struct {
	Callsign string `json:"callsign"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetStatsTopCallsigns(ctx context.Context, lim int32) ([]GetStatsTopCallsignsRow, error) {
	rows, err := q.db.Query(ctx, getStatsTopCallsigns, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsTopCallsignsRow{}
	for rows.Next() {
		var i GetStatsTopCallsignsRow
		if err := rows.Scan(&i.Callsign, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsTopCountries = `-- name: GetStatsTopCountries :many
SELECT
    COALESCE(NULLIF(BTRIM(q.country), ''), d.name) AS name,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
LEFT JOIN dxcc_entities d ON d.entity_id = q.dxcc
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND COALESCE(NULLIF(BTRIM(q.country), ''), d.name) IS NOT NULL
GROUP BY COALESCE(NULLIF(BTRIM(q.country), ''), d.name)
ORDER BY count DESC, COALESCE(NULLIF(BTRIM(q.country), ''), d.name) ASC
LIMIT 10
`

type GetStatsTopCountriesRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStatsTopCountries(ctx context.Context) ([]GetStatsTopCountriesRow, error) {
	rows, err := q.db.Query(ctx, getStatsTopCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsTopCountriesRow{}
	for rows.Next() {
		var i GetStatsTopCountriesRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsTopCountriesLimited = `-- name: GetStatsTopCountriesLimited :many
SELECT
    COALESCE(NULLIF(BTRIM(q.country), ''), d.name) AS name,
    COUNT(*)::bigint AS count
FROM qsos q
JOIN logbooks l ON l.id = q.logbook_id
LEFT JOIN dxcc_entities d ON d.entity_id = q.dxcc
WHERE l.deleted_at IS NULL
  AND q.deleted_at IS NULL
  AND COALESCE(NULLIF(BTRIM(q.country), ''), d.name) IS NOT NULL
GROUP BY COALESCE(NULLIF(BTRIM(q.country), ''), d.name)
ORDER BY count DESC, COALESCE(NULLIF(BTRIM(q.country), ''), d.name) ASC
LIMIT $1::int
`

type GetStatsTopCountriesLimitedRow struct {
	Name  string `json:"name"`
	Count int64  `json:"count"`
}

func (q *Queries) GetStatsTopCountriesLimited(ctx context.Context, lim int32) ([]GetStatsTopCountriesLimitedRow, error) {
	rows, err := q.db.Query(ctx, getStatsTopCountriesLimited, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStatsTopCountriesLimitedRow{}
	for rows.Next() {
		var i GetStatsTopCountriesLimitedRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
