// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findQSOForEQSLMatch = `-- name: FindQSOForEQSLMatch :one
SELECT
    q.id,
    q.uuid,
    q.logbook_id,
    lb.user_id
FROM qsos q
JOIN logbooks lb ON lb.id = q.logbook_id
WHERE upper(q.callsign) = upper($1)
  AND q.band = $2
  AND q.mode = $3
  AND q.datetime_on BETWEEN ($4::timestamptz - INTERVAL '15 minutes')
                        AND ($4::timestamptz + INTERVAL '15 minutes')
  AND q.deleted_at IS NULL
LIMIT 1
`

type FindQSOForEQSLMatchParams struct {
	Upper   interface{}        `json:"upper"`
	Band    string             `json:"band"`
	Mode    string             `json:"mode"`
	Column4 pgtype.Timestamptz `json:"column_4"`
}

type FindQSOForEQSLMatchRow struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	LogbookID int64     `json:"logbook_id"`
	UserID    int64     `json:"user_id"`
}

// Look up a QSO by the composite key used for eQSL matching:
// their callsign, band, mode, and time window (±15 minutes).
// eQSL timestamps may be off by a few minutes — use a generous window.
func (q *Queries) FindQSOForEQSLMatch(ctx context.Context, arg FindQSOForEQSLMatchParams) (FindQSOForEQSLMatchRow, error) {
	row := q.db.QueryRow(ctx, findQSOForEQSLMatch,
		arg.Upper,
		arg.Band,
		arg.Mode,
		arg.Column4,
	)
	var i FindQSOForEQSLMatchRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.LogbookID,
		&i.UserID,
	)
	return i, err
}

const getPendingSyncQSOs = `-- name: GetPendingSyncQSOs :many

SELECT
    ss.id             AS sync_id,
    ss.qso_id,
    ss.retry_count,
    q.uuid            AS qso_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on,
    q.rst_sent,
    q.rst_rcvd,
    q.gridsquare,
    q.my_gridsquare,
    q.name,
    q.station_callsign,
    q.frequency_hz,
    lb.user_id
FROM sync_status ss
JOIN qsos q ON q.id = ss.qso_id
JOIN logbooks lb ON lb.id = q.logbook_id
WHERE ss.service = $1
  AND lb.user_id = $2
  AND ss.status IN ('pending', 'dirty', 'error')
  AND (ss.next_retry_at IS NULL OR ss.next_retry_at <= NOW())
  AND q.deleted_at IS NULL
ORDER BY ss.created_at ASC
LIMIT $3
`

type GetPendingSyncQSOsParams struct {
	Service string `json:"service"`
	UserID  int64  `json:"user_id"`
	Limit   int32  `json:"limit"`
}

type GetPendingSyncQSOsRow struct {
	SyncID          int64              `json:"sync_id"`
	QsoID           int64              `json:"qso_id"`
	RetryCount      int16              `json:"retry_count"`
	QsoUuid         uuid.UUID          `json:"qso_uuid"`
	Callsign        string             `json:"callsign"`
	Band            string             `json:"band"`
	Mode            string             `json:"mode"`
	DatetimeOn      pgtype.Timestamptz `json:"datetime_on"`
	RstSent         *string            `json:"rst_sent"`
	RstRcvd         *string            `json:"rst_rcvd"`
	Gridsquare      *string            `json:"gridsquare"`
	MyGridsquare    *string            `json:"my_gridsquare"`
	Name            *string            `json:"name"`
	StationCallsign *string            `json:"station_callsign"`
	FrequencyHz     *int64             `json:"frequency_hz"`
	UserID          int64              `json:"user_id"`
}

// Queries for the sync_status table and sync-related operations.
// Schema reference: docs/SCHEMA.md § sync_status
// These queries are used by sync workers (radioledger_worker role) and the sync status API.
// Fetch QSOs for a user+service that are pending/dirty or errored and eligible for retry.
// Used by the sync upload workers to find work. Runs as radioledger_worker role.
func (q *Queries) GetPendingSyncQSOs(ctx context.Context, arg GetPendingSyncQSOsParams) ([]GetPendingSyncQSOsRow, error) {
	rows, err := q.db.Query(ctx, getPendingSyncQSOs, arg.Service, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingSyncQSOsRow{}
	for rows.Next() {
		var i GetPendingSyncQSOsRow
		if err := rows.Scan(
			&i.SyncID,
			&i.QsoID,
			&i.RetryCount,
			&i.QsoUuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.DatetimeOn,
			&i.RstSent,
			&i.RstRcvd,
			&i.Gridsquare,
			&i.MyGridsquare,
			&i.Name,
			&i.StationCallsign,
			&i.FrequencyHz,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSyncHistory = `-- name: GetRecentSyncHistory :many
SELECT
    ss.id,
    ss.service,
    ss.status,
    ss.last_synced_at,
    ss.error_message,
    ss.last_error_code,
    ss.retry_count,
    q.uuid   AS qso_uuid,
    q.callsign,
    q.band,
    q.mode,
    q.datetime_on
FROM sync_status ss
JOIN qsos q ON q.id = ss.qso_id
JOIN logbooks lb ON lb.id = q.logbook_id
WHERE lb.user_id = $1
  AND ss.last_synced_at IS NOT NULL
ORDER BY ss.last_synced_at DESC
LIMIT $2
`

type GetRecentSyncHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentSyncHistoryRow struct {
	ID            int64              `json:"id"`
	Service       string             `json:"service"`
	Status        string             `json:"status"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	ErrorMessage  *string            `json:"error_message"`
	LastErrorCode *string            `json:"last_error_code"`
	RetryCount    int16              `json:"retry_count"`
	QsoUuid       uuid.UUID          `json:"qso_uuid"`
	Callsign      string             `json:"callsign"`
	Band          string             `json:"band"`
	Mode          string             `json:"mode"`
	DatetimeOn    pgtype.Timestamptz `json:"datetime_on"`
}

// Recent sync activity for a user, newest first. Used by GET /v1/sync/history.
func (q *Queries) GetRecentSyncHistory(ctx context.Context, arg GetRecentSyncHistoryParams) ([]GetRecentSyncHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRecentSyncHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSyncHistoryRow{}
	for rows.Next() {
		var i GetRecentSyncHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Status,
			&i.LastSyncedAt,
			&i.ErrorMessage,
			&i.LastErrorCode,
			&i.RetryCount,
			&i.QsoUuid,
			&i.Callsign,
			&i.Band,
			&i.Mode,
			&i.DatetimeOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncStatusSummary = `-- name: GetSyncStatusSummary :many
SELECT
    ss.service,
    COUNT(*) FILTER (WHERE ss.status IN ('pending', 'dirty', 'error')) AS pending_count,
    COUNT(*) FILTER (WHERE ss.status = 'error')               AS error_count,
    MAX(ss.last_synced_at)                                    AS last_sync_at,
    MAX(ss.updated_at)                                        AS last_updated_at
FROM sync_status ss
JOIN qsos q ON q.id = ss.qso_id
JOIN logbooks lb ON lb.id = q.logbook_id
WHERE lb.user_id = $1
GROUP BY ss.service
`

type GetSyncStatusSummaryRow struct {
	Service       string      `json:"service"`
	PendingCount  int64       `json:"pending_count"`
	ErrorCount    int64       `json:"error_count"`
	LastSyncAt    interface{} `json:"last_sync_at"`
	LastUpdatedAt interface{} `json:"last_updated_at"`
}

// Aggregate sync status per service for a user. Used by GET /v1/sync/status.
func (q *Queries) GetSyncStatusSummary(ctx context.Context, userID int64) ([]GetSyncStatusSummaryRow, error) {
	rows, err := q.db.Query(ctx, getSyncStatusSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSyncStatusSummaryRow{}
	for rows.Next() {
		var i GetSyncStatusSummaryRow
		if err := rows.Scan(
			&i.Service,
			&i.PendingCount,
			&i.ErrorCount,
			&i.LastSyncAt,
			&i.LastUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPendingSyncForQSO = `-- name: InsertPendingSyncForQSO :exec
INSERT INTO sync_status (qso_id, service, status, updated_at)
VALUES ($1, $2, 'pending', NOW())
ON CONFLICT (qso_id, service) DO NOTHING
`

type InsertPendingSyncForQSOParams struct {
	QsoID   int64  `json:"qso_id"`
	Service string `json:"service"`
}

// Insert a pending sync_status row for a single (qso_id, service) combination.
// ON CONFLICT DO NOTHING: if a pending row already exists, leave it alone.
// This is called by the QSO handler after create/update to enqueue sync work.
func (q *Queries) InsertPendingSyncForQSO(ctx context.Context, arg InsertPendingSyncForQSOParams) error {
	_, err := q.db.Exec(ctx, insertPendingSyncForQSO, arg.QsoID, arg.Service)
	return err
}
