// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    callsign,
    display_name,
    timezone,
    onboarding_complete
)
VALUES (
    $1,
    $2,
    CASE
        WHEN $3::text IS NULL THEN NULL
        ELSE UPPER($3::text)
    END,
    $4,
    COALESCE($5::text, 'UTC'),
    CASE
        WHEN $3::text IS NULL THEN FALSE
        ELSE TRUE
    END
)
RETURNING
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Callsign     *string `json:"callsign"`
	DisplayName  *string `json:"display_name"`
	Timezone     *string `json:"timezone"`
}

type CreateUserRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Callsign,
		arg.DisplayName,
		arg.Timezone,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createZitadelUser = `-- name: CreateZitadelUser :one
INSERT INTO users (
    email,
    zitadel_id,
    timezone
)
VALUES (
    LOWER(BTRIM($1::text)),
    $2,
    COALESCE($3::text, 'UTC')
)
RETURNING
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
`

type CreateZitadelUserParams struct {
	Email     string  `json:"email"`
	ZitadelID *string `json:"zitadel_id"`
	Timezone  *string `json:"timezone"`
}

type CreateZitadelUserRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateZitadelUser(ctx context.Context, arg CreateZitadelUserParams) (CreateZitadelUserRow, error) {
	row := q.db.QueryRow(ctx, createZitadelUser, arg.Email, arg.ZitadelID, arg.Timezone)
	var i CreateZitadelUserRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByCallsign = `-- name: GetUserByCallsign :one
SELECT
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
FROM users
WHERE upper(callsign) = upper($1)
  AND deleted_at IS NULL
`

type GetUserByCallsignRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByCallsign(ctx context.Context, callsign interface{}) (GetUserByCallsignRow, error) {
	row := q.db.QueryRow(ctx, getUserByCallsign, callsign)
	var i GetUserByCallsignRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailWithPassword = `-- name: GetUserByEmailWithPassword :one
SELECT
    id,
    uuid,
    email,
    password_hash,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
FROM users
WHERE LOWER(email) = LOWER($1)
  AND deleted_at IS NULL
`

type GetUserByEmailWithPasswordRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	PasswordHash       *string            `json:"password_hash"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithPassword, email)
	var i GetUserByEmailWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByZitadelID = `-- name: GetUserByZitadelID :one
SELECT
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
FROM users
WHERE zitadel_id = $1
  AND deleted_at IS NULL
`

type GetUserByZitadelIDRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByZitadelID(ctx context.Context, zitadelID *string) (GetUserByZitadelIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByZitadelID, zitadelID)
	var i GetUserByZitadelIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkUserZitadelIDByEmail = `-- name: LinkUserZitadelIDByEmail :one
UPDATE users
SET zitadel_id = $1,
    updated_at = NOW()
WHERE LOWER(email) = LOWER($2)
  AND deleted_at IS NULL
  AND zitadel_id IS NULL
RETURNING
    id,
    uuid,
    email,
    callsign,
    onboarding_complete,
    display_name,
    timezone,
    created_at,
    updated_at
`

type LinkUserZitadelIDByEmailParams struct {
	ZitadelID *string `json:"zitadel_id"`
	Email     string  `json:"email"`
}

type LinkUserZitadelIDByEmailRow struct {
	ID                 int64              `json:"id"`
	Uuid               uuid.UUID          `json:"uuid"`
	Email              string             `json:"email"`
	Callsign           *string            `json:"callsign"`
	OnboardingComplete bool               `json:"onboarding_complete"`
	DisplayName        *string            `json:"display_name"`
	Timezone           string             `json:"timezone"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LinkUserZitadelIDByEmail(ctx context.Context, arg LinkUserZitadelIDByEmailParams) (LinkUserZitadelIDByEmailRow, error) {
	row := q.db.QueryRow(ctx, linkUserZitadelIDByEmail, arg.ZitadelID, arg.Email)
	var i LinkUserZitadelIDByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.Callsign,
		&i.OnboardingComplete,
		&i.DisplayName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
  AND deleted_at IS NULL
`

type UpdatePasswordHashParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.PasswordHash, arg.ID)
	return err
}
